### ISSUE TITLE
V2.3.7 Visualization with GPU 4090 -> low FPS: 7~10

### ISSUE THREAD

**Issue by pianist1234567i** [deepmind/mujoco#1005]
run bin/simulate with model file `model/humanoid100/humanoid100.xml`.  I found the FPS is quite low and I have checked the GPU memory usage (200M). 

Hardware: GPU 4090, CPU i7-13900k

**Comment by kevinzakka** [comment]
Can you post more details please? In particular, can you run numbers with older versions and update the original post? Also are you building from source or just using the prebuilt binaries?

**Comment by pianist1234567i** [comment]
Thanks for you kindly reply. I have tested the version 2.1.0, 2.2.2, 2.3.7 (prebuilt binaries). All have low FPS. Besides, I cloned the github package and built it and it shows the same problem. (Ubuntu 20.04)

**Comment by saran-t** [comment]
Would you be able to check which version the slowdown first occurred? Just go back one-by-one through each binary release.

**Comment by pianist1234567i** [comment]
I found what caused this problem. I used the nvidia-drivier-520 and the FPS is decreased. Now I change the driver version to 535. For my computer, the FPS of simuate visualization increases to 60. Thanks for your kindly reply.
