### ISSUE TITLE
Question on Actuation Mechanism of "gear"ed "motor"s

### ISSUE THREAD

**Issue by warrenhanwen** [deepmind/mujoco#1010]
Hi,
First thank you for developing such a powerful simulator.

I've got a `motor` with `gear` ratio `n` defined in a `.xml` file, and I'm trying to understand if I apply a torque `T` to that motor via `mjData.ctrl`, is the actual torque at that joint `T` or `nT`, neglecting all other damping and friction effects.

Here is a sample conceptual `.xml` definition using `gear`ed `motor`:
```.xml
<motor name='motor-A'  joint='motor-A'  gear='25' ctrllimited='true' ctrlrange='-5 5'/>
```

Here's a simple conecptual code where the confusion comes from:
```Python
model = mujoco.MjModel.from_xml_string(xml, asset)
data = mujoco.MjData(model)
gear_ratio = ... # stores the gear ratio n in related entry
data.ctrl = torque # assigns the related entry to T
mujoco.mj_step(model, data)
print(f"data.act:{data.act.shape}\n{data.act}") # prints (0,) and []
print(f"data.qfrc_applied:{data.qfrc_applied.shape}\n{data.qfrc_applied}") # all 0
print(f"data.actuator_force:{data.actuator_force.shape}\n{data.actuator_force}") # equal to T
print(f"data.actuator_force * gear_ratio:{data.actuator_force.shape}\n"
      f"{data.actuator_force * gear_ratio}") # euqal to nT
print(f"data.qfrc_actuator:{data.qfrc_actuator.shape}\n{data.qfrc_actuator}") # equal to nT
```
I tried giving `T` to `mjData.ctrl`, and found that `mjData.actuator_force` prints the same `T`, and `mjData.act` has no elements, indicating that the `motor` has no internal states. But `mjData.qfrc_actuator` prints `nT`. So is the actual torque at the joint `T` or `nT`?

**Comment by yuvaltassa** [comment]
The force at the joint is `nT`.

Conceptually it's actuator force -> transmission -> joint, where in this case the transmission (gear) just scales the force. Note that setting `gainprm[0] = n` (you'll need a `general` actuator to do that) has the same overall effect but `gear` also scales `actuator_length`, while the gain only scales `actuator_force`.
