### ISSUE TITLE
Unitree A1 contacts jacobian 

### ISSUE THREAD

**Issue by Ahmad0Aldaher** [deepmind/mujoco#1027]
I am using the unitree A1 from the menagerie repo. I want to find the contacts jacobian for the four legs. how to do that. Also how to check the following contanct constrains in the contact points:
$$J(q)\dot{q}=0$$ $$J(q)\ddot{q}+\dot{J}(q)\dot{q}=0$$

**Comment by yuvaltassa** [comment]
You probably want to use [this function](https://mujoco.readthedocs.io/en/latest/APIreference/APIfunctions.html?highlight=mj_mulJacVec#mj-muljacvec), or look at the implementation and read the Jacobian data directly.

Note that the equations you wrote will not be satisfied exactly, as MuJoCo's constraint mechanism is always soft.
