### ISSUE TITLE
Moving the camera using keyboard events

### ISSUE THREAD

**Issue by KamatMayur** [deepmind/mujoco#1028]
Hi,
I'm a final year engineering student and I'm trying to use MuJoCo for my finaly year project.
I have prior experince with game development in Unreal Engine 4/5, but have never digged up into the inner workings of a physics engine or the rendering engine.

Firstly I apologize if my question is too stupid because I haven't been able to find any simillar issue.

I'm looking for some help with moving the camera using the keyboard events (WASD) and mouse in realtime.
The way I want to achieve this is by adding scaled values of the unit direction vectors(like the direction at which the camera is facing) to the global postion_vector of the camera.

So far i have manged to move and orient the camera using the `cam.azimuth`, `cam.elevation`, `cam.lookat` etc....But it isn't compatible with the above appoach.

I have also tried modifying it using ` model->cam_pos` but that didnt reflect any changes.
I also tried changing `data->cam_xpos` but it seems to get overwritten by the forward dynamics.

	//Code for camera movement when the camera mode is set to hover
	if (camera_mode_hover) {
		d->cam_xpos[1] += 0.001;	// doesn't work
		m->cam_pos[1] += 0.001;		// doesnt' work
		
	}

Any help is much appreciated!

**Comment by yuvaltassa** [comment]
I think you want to be moving the free camera, not the fixed cameras in the model. Look at [`simulate.cc`](https://github.com/deepmind/mujoco/blob/main/simulate/simulate.cc) and figure out how it does it. More generally, [engine_vis_interact.c](https://github.com/deepmind/mujoco/blob/main/src/engine/engine_vis_interact.c) contains all the interaction functions. A good place to start is the relevant [documentation chapter](https://mujoco.readthedocs.io/en/latest/programming/visualization.html#).

**Comment by yuvaltassa** [comment]
Maybe instead of writing your own thing, just build [simulate](https://mujoco.readthedocs.io/en/latest/programming/samples.html#sasimulate) from source and modify it to suit your needs?
