### ISSUE TITLE
Linearized model using mjd_transitionFD

### ISSUE THREAD

**Issue by Ahmad0Aldaher** [deepmind/mujoco#1029]
Does the mjd_transitionFD function give A and B matrices for specific state and control, considering contacts and other constraints?

**Comment by Ahmad0Aldaher** [comment]
Is there a way or function to find A and B matrices  for specific state and control, considering contacts and other constraints in continuous-time like (mjd_transitionFD)

**Comment by yuvaltassa** [comment]
You mean that you want an equivalent function for acceleration rather than next state?

That should be very easy to write. What do you need it for?

**Comment by Ahmad0Aldaher** [comment]
I need  the linearized model with respect to constraints and contacts in continuous-time case not discrete as following

$$ \dot{x}(t)=Ax(t)+B(t)$$

So is there a way to find these A and B

**Comment by yuvaltassa** [comment]
Are you using Python or C++?

**Comment by Ahmad0Aldaher** [comment]
I am  using Python

**Comment by yuvaltassa** [comment]
If you don't need high performance, a finite differencing loop in python will do the job just fine.

**Comment by Ahmad0Aldaher** [comment]
I am so sorry I did not catch what do you mean. What fucntions should I use to get these continuous-time A and B matrices

**Comment by yuvaltassa** [comment]
```py
# save state
mujoco.mj_forward(model, data)
# save qacc
for i in range(state_size):
  # set state, nudge state in direction i by eps
  mujoco.mj_forward(model, data)
  J[:, i] = (qacc_nudge - qacc) / eps
```
Basically follow the pattern [here](https://github.com/deepmind/mujoco/blob/f44c6575444fc393d74ba937ba432c51f55bba2e/src/engine/engine_derivative_fd.c#L327), but with forward instead of step.

**Comment by efecanalbay** [comment]
Hello, 

I am also trying to do similar implementation. I have a MuJoCo right leg model. I am simulating it with C++. For knee joint, I am applying a torque which is a curve similar to sinus wave and getting almost sinus angular data from knee joint.  As you can see from the plot, blue curve is plot of angular data at knee joint.
![angle_knee_joint](https://github.com/user-attachments/assets/a9a3a1ae-a164-4a2c-84cb-b65bc9a1c447)
I am also linearizing my model thanks to **mjd_transitionFD(m, d, epsilon, flg_centered, A1, B1, nullptr, nullptr);**. With this function I am obtaining A and B matrices. Then, I am trying to apply Euler's numerical integration to see if I can match simulated angle data before and after linearization with below code:

          mj_step(m, d);
          Eigen::MatrixXd A(2, 2); // A matrix for 2 states (angle (phi), angular velocity (phi_dot))
          Eigen::MatrixXd B(2, 1); // B matrix for 1 control input (torque)
          mjtNum* A1 = A.data();
          mjtNum* B1 = B.data();
          double epsilon = 1e-12;
          bool flg_centered = true;
          mjd_transitionFD(m, d, epsilon, flg_centered, A1, B1, nullptr, nullptr);
          Eigen::MatrixXd xdot = A*x_k_1 + B*torque;   //x_k_1 is the state vector and defined as x_k_1 << d->qpos[knee_joint_idx], d->qvel[knee_joint_idx]; outside of the loop
          Eigen::MatrixXd x_k =xdot*d->time + x_k_1;
          x_k_1= x_k;

Also, my simulation timestep is 0.006 and I am simulating 60-70 seconds.
Then, I am saving x_k_1 values in every loop and record it into an array. After that I am getting the below plot. I would expect red curve to be very close (approximated) plot to the blue curve (simulation angle data).
![image](https://github.com/user-attachments/assets/da5ff13a-de50-446d-a9f4-260014b49f8f)

Also, for now you may not mind measurement and filtered angle plots. They are for my real time measurements.
