### ISSUE TITLE
how to change background color using C++ API?

### ISSUE THREAD

**Issue by templarares** [deepmind/mujoco#114]
Hi mujoco team,

I was trying to change my mujoco scene's background color to [1,1,1]. It seems that this is set in the "master" member variable of the mjuiThemeColor data structure. But how exactly can I modify this value using the C++ api? Thanks!

**Comment by nimrod-gileadi** [comment]
Hi there,
mjuiThemeColor is not used as the simulation background - it's used to control the colours of the UI in the sample `simulate.cc`.

Through XML, what you can do is to define your model with a "skybox" texture (as in [this model](https://github.com/deepmind/mujoco/blob/main/model/humanoid/humanoid.xml#L30)), with `builtin="flat"` and `rgb1="1 1 1"`. The first "skybox" texture is used as the background for rendering.

If you don't want to go through XML, you'll have to modify the `tex_rgb` array in [`mjModel`](https://github.com/deepmind/mujoco/blob/main/include/mjmodel.h#L774). I guess it's not so obvious from the docs, but you could try something along these lines:

```c
static void setBackgroundRgb(mjModel* model, mjtByte r, mjtByte g, mjtByte b) {
  // Assuming you set name="skybox" on the texture in the XML. You could just set
  // id = 0 if it's the first texture in your XML file.
  int id = mj_name2id(model, mjOBJ_TEXTURE, "skybox");
  if (id == -1) {
    // TODO: handle error
  }
  int npixels = model->tex_height[id] * model->tex_width[id];
  for (int i = 0; i < npixels; i++) {
    int adr = model->tex_adr[id] + 3 * i;
    model->tex_rgb[adr + 0] = r;
    model->tex_rgb[adr + 1] = g;
    model->tex_rgb[adr + 2] = b;
  }
}
```
