### ISSUE TITLE
What are the units on the accelerometer sensor?

### ISSUE THREAD

**Issue by MotorCityCobra** [deepmind/mujoco#116]
I've heard it said a few times from the MuJoCo team that there are not units. But I am trying to wrap my head around how to simulate a real life Gy-521 accelerometer I have in MuJoCo.

**Comment by yuvaltassa** [comment]
If it helps, you can think of units in MuJoCo as determined by gravity. With the current default, (0, 0, -9.81) you can interpret all units as MKS. Set gravity to (0, 0, -981) and you can interpret all units as CGS.
