### ISSUE TITLE
Documentation Typo

### ISSUE THREAD

**Issue by kevinzakka** [deepmind/mujoco#118]
Should the sphere `rgba` highlighted below not be `0 0 1 1`?

<img width="742" alt="Screen Shot 2022-01-27 at 8 54 20 AM" src="https://user-images.githubusercontent.com/10518920/151405971-768c1727-96bd-4515-bd14-d8ff07eb3273.png">

**Comment by yuvaltassa** [comment]
Yes, indeed. Thanks!
Fixed internally. 

Apologies that we cannot yet push out fixes between releases. 
This will be remedied soon, once we open source.
