### ISSUE TITLE
What are units of accelerometer and gyroscope?

### ISSUE THREAD

**Issue by markub3327** [deepmind/mujoco#119]
Hello,

   in documentation is written about accelerometer and gyroscope, but nothing about their units.

Is gyroscope in deg/s or rad/s?
Is accelerometer in m/s2?

Thanks a lot.
Have a nice day.

**Comment by yuvaltassa** [comment]
Gyroscopes always report rad / s.

Accelerometers report length-units / s^2. The actual length units are generally undefined, though they can often be inferred from the value of gravity under the assumption that you are on Earth. For the default (0, 0, -9.81), if you are on the surface of Earth, the unit of length can be inferred to be Metres. However if you are in free space with no gravity, the length unit is completely open to your own interpretation, as are units of force and mass etc, as long as they are all consistent. To phrase this with an example: the dynamics of a 1 metre spaceship that weighs 1 Kg and has a 1 Newton thruster are **exactly equivalent** to those of a 1 cm spaceship that weighs 1 gram and has a 1 Dyn thruster.

**Comment by yuvaltassa** [comment]
That said, since this is a common question, we will add a section in the documentation to clarify.

Thanks for bringing this to our attention.

**Comment by yuvaltassa** [comment]
Following up, see [here](https://mujoco.readthedocs.io/en/latest/overview.html#units-are-undefined)

**Comment by markub3327** [comment]
@yuvaltassa 

Thanks, it's very clear... 🙂

Thanks.
