### ISSUE TITLE
Using Open Source MuJuCo in Gym

### ISSUE THREAD

**Issue by jkterry1** [deepmind/mujoco#14]
Hey,

I'm the new maintainer of [Gym](https://github.com/openai/gym) (I'm a PhD student at UMD, I have no formal affiliation with OpenAI). As you may know, Gym has been using MuJuCo for a long time in it's MuJuCo and Robotics environments, and was in the process of replacing these in full with Brax (originally PyBullet, but plans changed) due to MuJuCo's status as closed source and a host of massive maintenance issues with the MuJuCo environments and mujuco-py. Are you guys interested in Gym support, and if so would you be willing to reach out to me to set up a time to briefly chat about plans? My email is jkterry@umd.edu

**Comment by fenollp** [comment]
Sorry to hijack this after closure.

@jkterry1 could you point to an announcement regarding mujoco_py no longer being maintained? There have been 3 commits since your last comment.
Finally, where can we learn more about your exchanges with the MuJoCo team and possible roadmap?

Thanks
