### ISSUE TITLE
Report an issue with mj_ray()

### ISSUE THREAD

**Issue by hnyu** [deepmind/mujoco#15]
Hi, glad to hear that Mujoco is now free and open sourced!

I am a user of OpenAI's [safety gym](https://openai.com/blog/safety-gym/) which is built on Mujoco. The natural lidar in safety gym seems broken (can't exclude robot body parts when casting the ray to detect obstacles in the environment, resulting in false positives). This is due to Mujoco's mj_ray() issue as discussed in an old post by people at OpenAI on Mujoco's forum:

http://webcache.googleusercontent.com/search?q=cache:0_oDvIqG-qsJ:www.mujoco.org/forum/index.php%3Fthreads/interpretation-of-mj_ray-arguments.3853/+&cd=1&hl=en&ct=clnk&gl=us

This issue so far hasn't been fixed yet. As a result, safety gym by default uses pseudo lidar instead of natural lidar. I think this issue might be worth an inspection. Thanks!

**Comment by nimrod-gileadi** [comment]
Sorry for taking a while to get to this. Thanks for reporting.

I tried to reproduce the issue described in the post you linked (by using the same XML), and could see any problem with the output from MuJoCo. Have you tried this with a recent version?

One gotcha is that mj_ray can only be used after calling mj_kinematics (or mj_fwdPosition, or mj_forward). Could this be the issue in Safety Gym?
We'll update the documentation to mention this explicitly.

**Comment by hnyu** [comment]
> Sorry for taking a while to get to this. Thanks for reporting.
> 
> I tried to reproduce the issue described in the post you linked (by using the same XML), and could see any problem with the output from MuJoCo. Have you tried this with a recent version?
> 
> One gotcha is that mj_ray can only be used after calling mj_kinematics (or mj_fwdPosition, or mj_forward). Could this be the issue in Safety Gym? We'll update the documentation to mention this explicitly.

Safety Gym calls mujoco-py's code to do ray casting. 

https://github.com/openai/mujoco-py/blob/4830435a169c1f3e3b5f9b58a7c3d9c39bdf4acb/mujoco_py/mjsim.pyx#L401

And they seem to indeed call mj_forward before mj_ray():

https://github.com/openai/safety-gym/blob/master/safety_gym/envs/engine.py#L1042

Since I'm not a maintainer of mujoco-py or Safety Gym, I guess this issue can be closed for now. Thanks!

**Comment by hnyu** [comment]
Sorry I just tried the new version 210. It seems to have solved this issue!
