### ISSUE TITLE
Creation of object at run-time

### ISSUE THREAD

**Issue by aled96** [deepmind/mujoco#164]
Is it possible to create an object, like a cube, in which the dimensions are specified by the user with a ROS service or something similar?

In more details, I would like to run several simulations, one after the other, in which I need to specify the position and the dimension of an object at every initialization.
Thanks !

**Comment by yuvaltassa** [comment]
From Python you can use [PyMJCF](https://github.com/deepmind/dm_control/blob/master/dm_control/mjcf/README.md).

From C++ if you want to change **sizes** you'll need to modify your XML at runtime. We are planning a C++ model creation/modification API, but it is not yet ready.

If you want to change **positions** you can just write into `mjData.qpos` for free objects or `mjData.mocap_{pos,quat}` for mocap bodies (free bodies without dynamics).
