### ISSUE TITLE
unexpected behavior in simulation of rope attached to a robot

### ISSUE THREAD

**Issue by xibeisiber** [deepmind/mujoco#173]
Hi,
I want to simulate a rope attached to the end of iiwa. But something unexpected happened when I tried to let one joint of iiwa move.

The screencast is [here](https://github.com/xibeisiber/pics/blob/master/aa/screencast.mp4).
The xml file and script are zipped in [aa.zip](https://github.com/deepmind/mujoco/files/8215797/aa.zip) and can be viewed in [https://github.com/xibeisiber/pics/tree/master/aa](https://github.com/xibeisiber/pics/tree/master/aa).

I'm not sure what the problem is.
mujoco version: 2.1.0
Thanks for any help!

**Comment by xibeisiber** [comment]
solved by using qfrc_applied instead of set_joint_qpos...

**Comment by jiyooonp** [comment]
Hello, 
I am trying to simulate a ball on a string on my manipulator too, but I am not sure how to start making the XML file. Could you share your XML file if possible? 
Thank you so much!

**Comment by jiyooonp** [comment]
@yuvaltassa Thank you so much!
