### ISSUE TITLE
What is "LO"? How does it translate to a simple hinge joint?

### ISSUE THREAD

**Issue by MotorCityCobra** [deepmind/mujoco#174]
The documentation states "Another important constant is the optimal resting length of the muscle, denoted L0".

I'm trying to understand the equation for actuating a joint. Specifically from using `mjcb_act_gain`, `mjcb_act_dyn`, and `mjcb_act_bias`.    
[A part of the documentation covers some of the math seems to be specifically about muscles.](https://mujoco.readthedocs.io/en/latest/modeling.html#clengthrange)  
"Biological muscle length", "Resting muscle length", "Constant length".  

Will the new docs have a break down of the math for callback controls for a simple hinge joint?

**Comment by yuvaltassa** [comment]
Why are you installing callbacks at all? Why can't you use the built-in actuators?
The callbacks are only for advanced operation.
The muscle documentation is completely unrelated. Muscles actuate spatial tendons, not joints.

**Comment by MotorCityCobra** [comment]
> Why are you installing callbacks at all?

Because I want to control the actuators with an algorithm. Written into the C++.
