### ISSUE TITLE
How could I periodically apply holding torque to joints from the C++?

### ISSUE THREAD

**Issue by MotorCityCobra** [deepmind/mujoco#178]
I would like to apply damping to a joint, but not all the time.
I would like to make the damping conditional in order to simulate a stepper motor. My stepper motor in real life has a holding torque of 0.5 NM and I would like to simulate this in my model, which uses MKS.  

I have tried setting the damping on the joint in the XML file. It doesn't work out. The problem is the joint moves when I want it to hold still, there is distortion in the model if I raise the damping high enough for it to hold still, and raising the motor strength to overcome the damping in the XML seems like it might make for an inaccurate simulation.  

I don't see an option to periodically set damping in the [MuJoCo API Documentation](https://mujoco.readthedocs.io/en/latest/APIreference.html?highlight=actuator_velocity#). I probably missed it.  
I thought it might be in `data->efc_KBIP[0]`, but I couldn't get the joint to hold still with it. I also tried `m->dof_damping[0]` on the joint with no success. 
Is `extern mjfGeneric mjcb_passive;` an option? I'm not sure how to use this.  

Below is my code within the main function of simulate.cc, which calls on the joint to move half way open then stop during the `else` condition.  
```
int first_count = 50;
...
        if (m)
        {
            if ((int)((int)(d->time*1) % (int)1) == (int)0 && ((int)d->time > (int)2))
            {
                // If two seconds have passed and the motor hasn't been moving 50 steps
                if (first_count > 0)
                {
                    first_count--;
                    std::cout << first_count << "\n";
                    flip = -1; // for function that sets d->ctrl[0] to this value

                } else {
                    flip = 0; // for function that sets d->ctrl[0] to this value
                    m->dof_damping[0] = 10; // Line I wish to apply holding torque AKA damping!
                }
            }
        }
```

![34523462456334](https://user-images.githubusercontent.com/14045554/157585185-4284399b-004d-4bf5-ab5e-a0015bb29ed5.png)

**Comment by yuvaltassa** [comment]
Addressed in #184
