### ISSUE TITLE
How to build concave geometry in mujoco?

### ISSUE THREAD

**Issue by CarlDegio** [deepmind/mujoco#183]
I want to build a box with round hole, but I found it's difficult for mujoco. Is there some method to build concave geometry and run normally about it's contact dynamics. ( even use some design software? )

**Comment by yuvaltassa** [comment]
Holes and other concave things need to be constructed from unions of convex things. A box with a square hole is easily made from 4 boxes. The hole can be made progressively rounder by adding more boxes (note these boxes can overlap, as they would be siblings in the same body). Unfortunately there is currently no native procedural way to do this, but you could do it with [PyMJCF](https://github.com/deepmind/dm_control/blob/master/dm_control/mjcf/README.md).
