### ISSUE TITLE
Question about a MJCF element

### ISSUE THREAD

**Issue by jdj2261** [deepmind/mujoco#188]
Hello, I am a student who is studying pick and place of robot using Mujoco. 

I have a question about a MJCF element.

Like the picture below, I would like to research that a robot gripper grasps a bottle placed on a shelf.

However, the problem is that the robots' arm doesn't move into the empty space even though there is an empty space on the shelf.

So, I thought that if i change any parameter in the mujoco XML reference, it will be recognized as an empty space.

I am wondering what parameters need to be changed so that the arm of the robot can move into empty space.

<img width="1489" alt="image" src="https://user-images.githubusercontent.com/35681273/158527385-67f8f542-48da-4edc-906d-2ce9616a26e6.png">
The robot's arm cannot move inward.
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/35681273/158529534-e53eaca0-bcaf-46a8-a88b-d2ce635c5a8f.png">

The xml file of the shelf that is currently set up is as follows.

~~~xml
<mujoco model="shelf">
  <asset>
    <mesh file="meshes/shelf.stl" name="shelf" scale="0.9 0.9 0.9"/>
    <texture file="../textures/yellow-plaster.png" name="dark-wood"/>
    <material name="wood" reflectance="1.0"  texture="dark-wood" texuniform="true"/>
  </asset>
  <worldbody>
    <body name="shelf">
      <body name="collision">
        <geom pos="0 0 0" mesh="shelf" type="mesh" solimp="0.998 0.998 0.001" solref="0.001 1" density="150" friction="0.95 0.3 0.1" material="wood" group="1" condim="4"/>
      </body>
      <body name="visual">
        <geom pos="0 0 0" mesh="shelf" type="mesh" rgba="0 1 0 1" conaffinity="0" contype="0" group="1" mass="0.0001"/>
      </body>
    </body>
  </worldbody>
</mujoco>
~~~

Please answer about my question.
Thank you.

**Comment by yuvaltassa** [comment]
In `simulate`, hit the 'H' key to see the convex hulls of your meshes. This is what you are actually colliding with. A concave shape needs to be composed of a union of convex shapes (mesh or primitive). Load the [mug](https://github.com/deepmind/mujoco/blob/main/model/mug/mug.xml) example to see how that can be dove with primitives. Note the collision geometry is in group 3, so you'll need to hit the '3' key to see it.
