### ISSUE TITLE
Python bindings build scripts are missing CMake files

### ISSUE THREAD

**Issue by aftersomemath** [deepmind/mujoco#191]
`make_sdist.sh` attempts to copy `.cmake` files that are not in the repo or the mujoco binary release:
https://github.com/deepmind/mujoco/blob/147efb5192ce9e3a9e4ca5c6e87a57ef3eb2121b/python/make_sdist.sh#L54

Without these files `setup.py` errors out due to missing cmake functions. First occurrence is here:
https://github.com/deepmind/mujoco/blob/147efb5192ce9e3a9e4ca5c6e87a57ef3eb2121b/python/mujoco/CMakeLists.txt#L43

Also there is an extra `..` in `make_sdist.sh` line that copies the license file over:
https://github.com/deepmind/mujoco/blob/147efb5192ce9e3a9e4ca5c6e87a57ef3eb2121b/python/make_sdist.sh#L50

**Comment by saran-t** [comment]
Thanks! Sorry about this, we use a slightly different repo layout for our internal build, I'll get these fixed soon.
