### ISSUE TITLE
Unity plugin

### ISSUE THREAD

**Issue by neox395** [deepmind/mujoco#193]
Hello dear Team of Deepmind,

first of all thanks for all your effort you are pouring in the development for the unity-plugin.

I followed the instruction for unity on ubuntu 20.04. The file _MujocoBinaryRetriever.cs_ contains "depricated" code, since the filenames (e.g. "/.mujoco/mujoco-2.1.1/lib/libmujoco_nogl.so.2.1.1") for the new version are not valid anymore.

Cheers,
Gerhard

**Comment by erez-tom** [comment]
Thanks for flagging!  We'll update the file soon.

**Comment by saran-t** [comment]
Fixed in 286c23169d07a6562329ff329d41b3d24c347b63
