### ISSUE TITLE
Where does the simulator save data and model files?

### ISSUE THREAD

**Issue by nikhilweee** [deepmind/mujoco#196]
I'm running MuJoCo 2.1.0 on MacOS. After loading a model file I tried clicking on "Save Model" or "Save Data" several times but nothing happens. I wonder if this functionality is broken?

**Comment by yuvaltassa** [comment]
Hi,

It is not broken. In MacOS those files are saved by default to the `Resources` directory inside the application package (right-click, "Show package contents"). 

This is of course not ideal. What you want is to bring up the system save dialog, which should not be hard to do. If you'd like, you're welcome to send a PR for this.

**Comment by nikhilweee** [comment]
Thanks! I did search in the `bin` directory but didn't think of searching the entire package.
