### ISSUE TITLE
How to simulate a substance being broken in two, cut, or smashed?

### ISSUE THREAD

**Issue by MotorCityCobra** [deepmind/mujoco#197]
Does MuJoCo have such bodies?

I see the skins and the fabrics. But I'm not sure what this means, from the docs... " _MuJoCo skins are only used for visualization and do not affect the physics in any way. In particular, collisions involve the geoms of the bodies to which the skin is attached, and not the skin itself._"  
In the hammock XML example it seems like the humanoid is right up against the hammock fabric. From the quote above it seems like the documentation is saying the skin materials are some kind of animation.

**Comment by yuvaltassa** [comment]
You could create the pieces, weld them together, and disable the welds at run time. This will simulate the effect of breaking.

But more generally no, MuJoCo was not designed for this type of high-dof simulation and is focused rather on articulated systems.

**Comment by MotorCityCobra** [comment]
@yuvaltassa 
Hi, I saw your name on the Maximum a Posteriori Policy Optimisation paper and I wonder if you wouldn't mind me asking what you think is the best algorithm right now for a multi-objective humanoid robot with continuous controls. Sorry, I know this is probably the wrong place to ask. 
I was looking at the [MO-MPO algorithm](http://proceedings.mlr.press/v119/abdolmaleki20a/abdolmaleki20a.pdf).
