### ISSUE TITLE
Modify the connection relationship during operation

### ISSUE THREAD

**Issue by haoboluo** [deepmind/mujoco#20]
I would like to express my gratitude to the contributors of MuJoCo. This issue is posted to seek advice on changing the connection relationship online. 

At present, most simulation engines such as MuJoCo have defined fixed connection relationships before running, such as MJCF, URDF, etc. This limits the simulation of modular self-reconfigurable robots, which need to change the connection relationship between modules during operation, such as changing from a snake-shaped robot to a three-legged robot. In other words, the parent-child relationship, maybe also the joints, between the different links of the robot will change during the simulation, but the 3D position of the links will remain unchanged. For example, in the figure below, module 3 was originally connected to module 2. At a certain moment in the simulation, module 3 was disconnected from module 2 and then connected to module 1, but its 3D position remained unchanged. 

![图片](https://user-images.githubusercontent.com/44913369/137866389-588ae6bd-98da-49d5-98f7-0967299aa707.png)

Look forward to getting suggestions from the community.  Thanks in advance.

**Comment by rjeli** [comment]
you could define equalities for every possible connection and change whether they are active at runtime? not sure how that would affect stability of the kinematic tree.

**Comment by haoboluo** [comment]
> 

Hi, thanks for your suggestion! I tried the solution you gave, but I ended up using the new adhesion actuators. 

https://mujoco.readthedocs.io/en/latest/XMLreference.html#actuator-adhesion
