### ISSUE TITLE
Jacobian coordinate frame

### ISSUE THREAD

**Issue by chisarie** [deepmind/mujoco#205]
Hi, 

thank you very much for the effort of open sourcing Mujoco, and for the official python bindings!

From the documentation I understand that `mj_jac` returns the Jacobian of a given point with respect to the world coordinates.
Is there a way to calculate the Jacobian with respect to other coordinate frames? For example with respect to an obstacle? Or with respect to the base in case of a mobile manipulator?
If not, is there a way to "transform" the world frame Jacobian to another frame?

Thank you very much in advance!
Eugenio

**Comment by yuvaltassa** [comment]
No, you would have to write that transformation yourself.
Note that if your desired frame is oriented like the world there is nothing to do, the Jacobian is the same.
If it is rotated you just need to premultiply the Jacobian by the transposed orientation matrix of your frame.
