### ISSUE TITLE
Itereate over geoms?

### ISSUE THREAD

**Issue by livinamuk** [deepmind/mujoco#206]
As I understand the local pos and rot offset for geoms is stored within arrays in the `mjModel` object (since it never changes) and arrays in the `mjData` object contain the global pos and rot data once the simulation kicks off. My problem is the arrays aren't accessed via the same indices. 

How do I iterate over geoms in the `mjData` object? Currently I'm looking up their ID via `mj_name2id(mjOBJ_GEOM, name)` but this isn't really viable because geoms names are only optional.

Or better yet, how do I retrieve the ID of each geom in the `mjModel?`

**Comment by yuvaltassa** [comment]
Geom IDs range from 0 to `model->ngeom-1`; they are just indices.
So `for (int i=0; i < model->ngeom; i++)` would iterate over all geoms. Is this what you are asking?
