### ISSUE TITLE
Analytical derivatives?

### ISSUE THREAD

**Issue by Daniellayeghi** [deepmind/mujoco#220]
Hi,

Thanks for the great work. At some point before the acquisition there were talks of analytical derivatives being added. Is this at all on your roadmap? If so is it far down the line?

**Comment by yuvaltassa** [comment]
- Yes, definitely on our roadmap.
- True analytical derivatives, probably in 2023.
- Fast finite-difference derivatives (using various tricks) will be out soon (within ~2 months), with similar API to eventual analytical derivatives which will be drop-in replacement.
