### ISSUE TITLE
Touch Sensor not able to capture contact force During Collision.

### ISSUE THREAD

**Issue by leonasting** [deepmind/mujoco#228]
I am working on the simulation of basic collision and wanted to capture contact forces using the touch sensor.
I am only getting 0 as in sim.data.sensor data. Let me know if I'm doing something wrong. 
Linke to my code is present below
XML: 
https://github.com/leonasting/Object-Manipulation-Research/blob/main/multi_sensor_interaction/multi-sensor.xml
Python:
https://github.com/leonasting/Object-Manipulation-Research/blob/main/multi_sensor_interaction/test2.py

**Comment by yuvaltassa** [comment]
Touch sensors report contact forces that occur inside the volume of a site, as explained [here](https://mujoco.readthedocs.io/en/latest/XMLreference.html#sensor-touch). 

Your sites are too small. There is [no surface contact](https://mujoco.readthedocs.io/en/latest/computation.html#collision-detection) in MuJoCo, the sites need to cover a large volume to capture the few contacts.
