### ISSUE TITLE
Mujoco Unity integration

### ISSUE THREAD

**Issue by jespersmith** [deepmind/mujoco#23]
Awesome news about open sourcing Mujoco, thank you very much for providing it!

We're looking in our next gen simulation environment, and Unity + Mujoco would be a big contender. Are they any plans on supporting the Unity plugin?

**Comment by youngwoon** [comment]
There was [Unity plugin for MuJoCo 1.55](https://roboti.us/download.html), which enables high-quality rendering and configuring scenes and graphical options. There are several examples: [IKEA Furniture Assembly Environment](https://clvrai.com/furniture) and [DoorGym](https://github.com/PSVL/DoorGym). It would be great if you continue to support Unity-MuJoCo integration.

**Comment by begesij** [comment]
any updates on this? would love to use this for a thesis :)

**Comment by erez-tom** [comment]
We are working on a new Unity plugin that we plan to release in Q1.  This plugin defines Unity components for most MJCF elements, thereby allowing the user to author and simulate Unity scenes using MuJoCo (+import MJCF models and associated assets into Unity).

Our plugin uses Unity's native time-ticking mechanism (the MuJoCo step is called in FixedUpdate()), and doesn't rely on communication with an external process.
We're curious to hear from people who use Roboti's plugin for communication with external processes (e.g., ML in Python) -- we wonder whether you could use other solutions (such as Unity's [ml-agents](https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Python-API.md)) instead.

Please let us know, and stay tuned!

**Comment by erez-tom** [comment]
We released our plug-in today, please see the [announcement](https://github.com/deepmind/mujoco/discussions/125). We look forward to your feedback. We also added a few [open issues](https://github.com/deepmind/mujoco/labels/Unity), if you have appetite to tackle any of them please comment in the relevant page.

We hope you find this plug-in useful and fun!
