### ISSUE TITLE
Visualising joint limits in the simulator?

### ISSUE THREAD

**Issue by livinamuk** [deepmind/mujoco#230]
Is it possible to view the joint limits in the simulator?

**Comment by yuvaltassa** [comment]
No, it is not. 
Do you have a good example (from elsewhere) of joint limit visualisation?

**Comment by livinamuk** [comment]
This is from Ragdoll Dynamics, a ragdoll authoring plugin for Maya

![This is an image](https://www.principiaprogrammatica.com/dump/RagdollJoint.jpg)

and shown with 3 axes in this video https://youtu.be/fY9ocIZmgzA

**Comment by yuvaltassa** [comment]
This is nice, thanks. We'll see if we can add something similar.
