### ISSUE TITLE
Expose DOM

### ISSUE THREAD

**Issue by jonrmo** [deepmind/mujoco#241]
Currently, there's no way to know what Mujoco loaded from XML. To retrieve certain attributes, such as mesh path, a client application has to reread the XML and construct its own DOM since this information isn't accessable via mjModel. This is a lot of unnecessary work for a client app given that Mujoco already parses the XML into a model.

**Comment by yuvaltassa** [comment]
MuJoCo's internal DOM will be exposed when the codebase is open-sourced, although this is considered an internal API which initially will not be supported. We do have concrete plans to upgrade this API to be user-facing, but this will only happen after open-sourcing.
