### ISSUE TITLE
Question: Rendering actuators

### ISSUE THREAD

**Issue by vittorione94** [deepmind/mujoco#247]
I couldn't find the rendering function to visualise the actuators in action so I'm in doubt  on the meaning of the render.

Intro: When we render the actuators we have a colour range that goes from light blue (when negative) to orange (when positive). 

I was wondering in case of filtered dynamics such as muscles, the rendering system is representing the "raw" input to the engine (i.e. excitations) or the filtered state (i.e. activations)?

Note: muscles are just an example, this question is relevant for any kind of actuators that has a filtered [dyntype](https://mujoco.readthedocs.io/en/latest/XMLreference.html?highlight=actuator#actuator-general) (link to documentation).

I hope this question makes sense :)

Any clarifications would be much appreciated! 
Best,
-Vittorio

**Comment by yuvaltassa** [comment]
Actuator colours always correspond to `data.ctrl`, even if the actuator is stateful.

That said, it might make sense to visualise the actuator states (`data->act`) if they are stateful. Another possibility would be to add a completely new visualisation flag, specifically for this. What do you think is the preferred behaviour?

**Comment by vittorione94** [comment]
I see, thanks for your reply!

Having a flag specifically for this would make more sense to me :) since visualising `data.ctrl` on its own is still very useful.

**Comment by yuvaltassa** [comment]
Done in 066367f
