### ISSUE TITLE
./simulate is not working on RHEL 7.9

### ISSUE THREAD

**Issue by u6766669** [deepmind/mujoco#25]
I am a novice user of Mujoco, I try to run the simulator on the remote cluster but I met the following problem. I tried some of the online solutions, but no help. Although it reports problems related to GLX, the command "glxinfo" and "glxgears" works well.

@mercury2 bin$ ./simulate 
mujoco pro version 2.10 x 
error of failed request: badrequest (invalid request code or no such operation) 
major opcode of failed request: 151 (glx) 
minor opcode of failed request: 0 () 
serial number of failed request: 9 
current serial number in output stream: 9 
segmentation fault

**Comment by truatpasteurdotfr** [comment]
FYI: works for me on a remote CentOS-7 x86_64 using Nice DCV (https://download.nice-dcv.com/) with mujoco210-linux-x86_64.tar.gz.

**Comment by saran-t** [comment]
Can you try again with the new 2.1.1 release?

**Comment by kevinzakka** [comment]
Closing this for now. @truatpasteurdotfr feel free to open if you are still running into issues.
