### ISSUE TITLE
[Bug] `multiccd` option not a valid attribute of option

### ISSUE THREAD

**Issue by kevinzakka** [deepmind/mujoco#266]
Tried [`multiccd`](https://mujoco.readthedocs.io/en/latest/XMLreference.html#option-flag) for fun and got an error on both the MuJoCo app (2.1.5) and PyMJCF from dm_control:

```python
AttributeError: Line 12: error while parsing element <option>: 'multiccd' is not a valid attribute for <option>. # PyMJCF.
XML Error: Schema violation: unrecognized attribute: 'multiccd'. # App.
```

**Comment by kevinzakka** [comment]
Apologies, I realize this should have been under the flag attribute.

```xml
<option>
  <flag multiccd="enable"/>
</option>
```

**Comment by yuvaltassa** [comment]
Actually, while we're here, there is a bug (fixed internally, to be pushed soon): The multiCCD disable/enable button in `simulate` does not work.
