### ISSUE TITLE
How to change mujoco model parameters to pytorch tensors?

### ISSUE THREAD

**Issue by ZJP-c4cld** [deepmind/mujoco#267]
I want to construct a neural network in pytorch which outputs appropriate values of mujoco model parameters. But this requires that mujoco model parameters are converted into pytorch tensors and mujoco environments run well with these converted model parameters. I don't know how to achieve this goal. Anyone know how to do that?

**Comment by kevinzakka** [comment]
Hi @ZJP-c4cld, closing this. Please use the discussion dashboard for these sorts of questions.
