### ISSUE TITLE
What's wrong with my customed hopper xml model?

### ISSUE THREAD

**Issue by ZJP-c4cld** [deepmind/mujoco#280]
When I use python binding of mujoco to read my customed xml, an error occured as following:

File "/root/aliyun/mymirror/test.py", line 108, in test
    env_dm = suite.load(domain_name=env_name,task_name='hop')
  File "/root/anaconda3/envs/distralmirror37/lib/python3.7/site-packages/dm_control/suite/__init__.py", line 115, in load
    environment_kwargs, visualize_reward)
  File "/root/anaconda3/envs/distralmirror37/lib/python3.7/site-packages/dm_control/suite/__init__.py", line 149, in build_environment
    env = domain.SUITE[task_name](**task_kwargs)
  File "/root/anaconda3/envs/distralmirror37/lib/python3.7/site-packages/dm_control/suite/hopper_sunblaze.py", line 63, in hop
    physics = Physics.from_xml_string(*get_model_and_assets())
  File "/root/anaconda3/envs/distralmirror37/lib/python3.7/site-packages/dm_control/mujoco/engine.py", line 423, in from_xml_string
    model = wrapper.MjModel.from_xml_string(xml_string, assets=assets)
  File "/root/anaconda3/envs/distralmirror37/lib/python3.7/site-packages/dm_control/mujoco/wrapper/core.py", line 302, in from_xml_string
    model_ptr = _get_model_ptr_from_xml(xml_string=xml_string, assets=assets)
  File "/root/anaconda3/envs/distralmirror37/lib/python3.7/site-packages/dm_control/mujoco/wrapper/core.py", line 187, in _get_model_ptr_from_xml
    ptr = mujoco.MjModel.from_xml_string(xml_string, assets or {})
ValueError: Error: material 'geom' not found in geom 0
Object name = torso_geom, id = 0, line = 19, column = -1

My customed xml model is as following:

<mujoco model="hopper">
  <compiler angle="degree" coordinate="global" inertiafromgeom="true"/>
  <default>
    <joint armature="1" damping="1" limited="true"/>
    <geom conaffinity="1" condim="1" contype="1" margin="0.001" friction="0.8 .1 .1" material="geom" rgba="0.8 0.6 .4 1" solimp=".8 .8 .01" solref=".02 1"/>
    <motor ctrllimited="true" ctrlrange="-.4 .4"/>
  </default>
  <option integrator="RK4" timestep="0.002"/>
  <worldbody>
    
    <body name="torso">
      <joint armature="0" axis="1 0 0" damping="0" limited="false" name="ignore1" pos="0 0 0" stiffness="0" type="slide"/>
      <joint armature="0" axis="0 0 1" damping="0" limited="false" name="ignore2" pos="0 0 0" ref="1.25" stiffness="0" type="slide"/>
      <joint armature="0" axis="0 1 0" damping="0" limited="false" name="ignore3" pos="0 0 0" stiffness="0" type="hinge"/>
      <geom fromto="0 0 1.45 0 0 1.05" name="torso_geom" size="0.05" type="capsule"/>
      <body name="thigh">
        <joint axis="0 -1 0" name="thigh_joint" pos="0 0 1.05" range="-150 0" type="hinge"/>
        <geom fromto="0 0 1.05 0 0 0.6" name="thigh_geom" size="0.05" type="capsule"/>
        <body name="leg">
          <joint axis="0 -1 0" name="leg_joint" pos="0 0 0.6" range="-150 0" type="hinge"/>
          <geom fromto="0 0 0.6 0 0 0.1" name="leg_geom" size="0.04" type="capsule"/>
          <body name="foot">
            <joint axis="0 -1 0" name="foot_joint" pos="0 0 0.1" range="-45 45" type="hinge"/>
            <geom fromto="-0.13 0 0.1 0.26 0 0.1" name="foot_geom" size="0.06" type="capsule"/>
          </body>
        </body>
      </body>
    </body>
  </worldbody>
  <actuator>
    <motor ctrllimited="true" ctrlrange="-1.0 1.0" gear="200.0" joint="thigh_joint"/>
    <motor ctrllimited="true" ctrlrange="-1.0 1.0" gear="200.0" joint="leg_joint"/>
    <motor ctrllimited="true" ctrlrange="-1.0 1.0" gear="200.0" joint="foot_joint"/>
  </actuator>
</mujoco>

So what's wrong with my customed hopper xml model? How should I modify my xml model?

**Comment by yuvaltassa** [comment]
The error is pretty clear, no?
```
ValueError: Error: material 'geom' not found in geom 0
Object name = torso_geom, id = 0, line = 19, column = -1
```
You are referencing a non-existent material.
