### ISSUE TITLE
Custom Soft Body

### ISSUE THREAD

**Issue by tudorjnu** [deepmind/mujoco#283]
Currently MuJoCo allows the creation of soft bodies based on the primitive objects provided (i.e. square, cylinder ...). 

It would be amazing if we could use custom meshes for the creation of such objects or particle based systems. For example one could simulate clothing using such option or other soft elements for soft robotics. 

Thank you!

**Comment by yuvaltassa** [comment]
Agreed!

We have some plans in this regard, but it's still early days.
