### ISSUE TITLE
Consistency between 2.2.0 tag and 2.2.0 binaries and changelog

### ISSUE THREAD

**Issue by traversaro** [deepmind/mujoco#296]
Hello everyone, and thanks a lot for open sourcing mujoco! 

I am trying to build mujoco [2.2.0](https://github.com/deepmind/mujoco/releases/tag/2.2.0) from source. I was expecting it to install the headers in `${CMAKE_INSTALL_PREFIX}/include/mujoco/<...>.h` as this is how headers are arranged in the 2.2.0 binaries, and because the 2.2.0 changelog report, at point 7:

> 7. Public headers have been moved from /include to /include/mujoco/, in line with the directory layout common in other open source projects. Developers are encouraged to include MuJoCo public headers in their own codebase via #include <mujoco/filename.h>.

However, installing 2.2.0 results in headers installed in `${CMAKE_INSTALL_PREFIX}/include/<...>.h`, and if one checks the source code this is indeed expected, as the line in https://github.com/deepmind/mujoco/blob/2.2.0/CMakeLists.txt#L176 is: 
~~~
    PUBLIC_HEADER DESTINATION ${CMAKE_INSTALL_INCLUDEDIR} COMPONENT dev
~~~
instead of 
~~~
    PUBLIC_HEADER DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/mujoco" COMPONENT dev
~~~
as modified in https://github.com/deepmind/mujoco/commit/098b125d02d6115578a795d1da0f17811df4cf53 . 

Perhaps this is just an artifact of the initial open source release, but I tought it was worth reporting it to as other users may be confused. 

As an additional context, I find there were some changes that were ìn `main` but not in `2.2.0` that prevented to compile mujoco with gcc on Linux, that you can find at https://github.com/conda-forge/staged-recipes/blob/c6a893a35f34e799522e8be3509a9aa0c1a7bf09/recipes/mujoco/main_backport.patch .

**Comment by saran-t** [comment]
I've just moved the `2.2.0` tag to 098b125d02d6115578a795d1da0f17811df4cf53 so the source code archive (mujoco-2.2.0.zip and mujoco-2.2.0.tar.gz) should now build and install correctly. Sorry about the confusion.

**Comment by traversaro** [comment]
Thanks a lot @saran-t @nimrod-gileadi !

**Comment by saran-t** [comment]
I've flagged the package as out of date on AUR.

**Comment by traversaro** [comment]
> I've flagged the package as out of date on AUR.

Great, thanks!
