### ISSUE TITLE
What is the best way to import a Fusion360 model?

### ISSUE THREAD

**Issue by DinoDany** [deepmind/mujoco#317]
My end goal is rendering and controlling a robot in Unity using mujoco physics. The robot was designed on Fusion360. My question is: What would be the best practice? Importing the model to mujoco first and importing the mujoco scene into unity? or importing the model directly to unity and adding the scripts from the unity engine?  In case I have to import first to mujoco, is there an established pipeline to convert the model to a mujoco-friendly format?

Thank you so much.

**Comment by kevinzakka** [comment]
@DinoDany Drive by comment, what are the issues you get when you try to load the URDF into the native visualizer? Can potentially help if it's not true incompatibilities.

**Comment by kevinzakka** [comment]
@DinoDany A zip file to debug would be great!

**Comment by DinoDany** [comment]
@kevinzakka Right, here it is. It is just a small test. Thank you so much
[Test_0_descriptionv1.zip](https://github.com/deepmind/mujoco/files/8821264/Test_0_descriptionv1.zip)

**Comment by kevinzakka** [comment]
Hi @DinoDany, I was able to load it into the MuJoCo simulate app by doing the following:

1. Adding a `<mujoco><compiler discardvisual="false" meshdir="../meshes/"/></mujoco>` clause right after the `<robot>`.
2. Changing all absolute mesh paths to just be relative to `meshes`.

It loads fine now but there's some jittering. Here's a zip file containing the URDF: [Test_0.urdf.zip](https://github.com/deepmind/mujoco/files/8824425/Test_0.urdf.zip)

**Comment by DinoDany** [comment]
@kevinzakka wow, thank you so much. You are a life saver, why do you think it is so jittering?

**Comment by DinoDany** [comment]
@erez-tom Do you have any resources that I can read to learn more about the mapping between MuJoCo and PhysX? Thank yoooouuu :)

**Comment by DinoDany** [comment]
@kevinzakka I see. ME team just gave me that model to test the conversions from Fusion-MuJoCo-Unity but it was just a quick test so maybe that-s why they are intersecting. Im going to try with the actual models and I will let you know how it went. :D

**Comment by DinoDany** [comment]
@kevinzakka So, my more complex models don't work >( I get a segmentation fault (core dumped). Do you know why this happens? I attached the file in case you need to debug. Thank you so much for all your help :) 
[Kinematic_description.zip](https://github.com/deepmind/mujoco/files/8847084/Kinematic_description.zip)

**Comment by kevinzakka** [comment]
@DinoDany Is there an actual URDF file I can debug with?

**Comment by kevinzakka** [comment]
@DinoDany So your joint types do not correspond to joint types that exist in MuJoCo, see [here](https://mujoco.readthedocs.io/en/latest/XMLreference.html#body-joint).

But more generally, you discovered a bug! @yuvaltassa There is a segmentation fault that occurs because we do not check that the joint type returned -1, see [here](https://github.com/deepmind/mujoco/blob/main/src/xml/xml_urdf.cc#L309). I'll submit a PR!

**Comment by DinoDany** [comment]
Woow! This is the first bug I catch ever. Thank you so much for all your help :)
