### ISSUE TITLE
Static world geometry using URDF and Python bindings

### ISSUE THREAD

**Issue by surgura** [deepmind/mujoco#333]
Using the new Python bindings and URDF, how do I create a robot and a static environment, such as the ground and some walls? I can successfully load a robot using URDF.

```
<?xml version="1.0" ?>
<robot name="robot_0">
    <link name="origin">
...
</robot>
```

```
model = mujoco.MjModel.from_xml_string(urdf, assets)
data = mujoco.MjData(model)

for _ in range(100000):
    mujoco.mj_step(model, data)
    print(data.geom_xpos)

viewer.close()
```

Do I need to describe the environment in the same URDF too? Or is there an API for adding objects? On the ROS website I cannot find information about adding static geometry to URDF. Thank you in advance.

Additionally, the root link of the robot appears to hang in the air at position (0,0,0). Is there a way to resolve that? The robot behaves as expected in Isaac Gym.

**Comment by kevinzakka** [comment]
Hi @surgura,

Highly recommend you go through the [tutorial](https://colab.research.google.com/github/deepmind/dm_control/blob/main/dm_control/mujoco/tutorial.ipynb) first. If you still have questions after that, feel free to post them here and I can try to answer.

**Comment by yuvaltassa** [comment]
Hi @surgura, none of us is a URDF expert so I don't think you'll be able to get a good answer to this from the development team, but here are 2 points I can think of:
1. URDF is a very bare-bones format and using it would greatly limited in what you could model in MuJoCo. I strongly recommend against this.
2. SDF, which could be a described as a much improved generalisation of URDF can, amongst many other things, properly describe the robot environment. [Here](https://github.com/gazebosim/gz-mujoco/tree/main/sdformat_mjcf) is a work-in-progress tool for converting between SDF and MJCF.

**Comment by yuvaltassa** [comment]
MuJoCo has an `<include>` directive documented [here](https://mujoco.readthedocs.io/en/latest/XMLreference.html#include). Unfortunately while usable ([here](https://github.com/deepmind/mujoco/tree/main/model/hammock) is an example), it is also quite limited. Until we improve native MJCF composability (which is on our roadmap), `dm_control` remains your best option for procedural composability.

Unless you are very comfortable with C++, in which case you could use the MuJoCo compiler directly to make your models as in the implementation of procedural composite bodies [here](https://github.com/deepmind/mujoco/blob/main/src/user/user_composite.cc), but that API is undocumented and unsupported at the moment.

**Comment by surgura** [comment]
Thank you. I will use the approach described here https://mujoco.readthedocs.io/en/latest/modeling.html?highlight=mjcf#urdf-extensions
and load my urdf files, then save them to mjcf and compose a larger mjcf from those.
