### ISSUE TITLE
Auto Inertia Computation of concave shapes, meshes and thin bodies

### ISSUE THREAD

**Issue by rohit-kumar-j** [deepmind/mujoco#338]
### Discussed in https://github.com/deepmind/mujoco/discussions/318

<div type='discussions-op-text'>

<sup>Originally posted by **rohit-kumar-j** June  2, 2022</sup>
By default, does mujoco support auto inertia computation from an STL file loaded as a body? Like a [hollow vase](https://cults3d.com/en/3d-model/home/vase-006)? (assuming uniform density)
</div>

**Comment by yuvaltassa** [comment]
The answer is: 
1. Currently, no. Only convex STLs will get the correct inertia.
2. We are working on better computation that will work for all well formed meshes, convex or concave.
Leaving open, will update here when this is implemented.

**Comment by yuvaltassa** [comment]
Note this is now implemented, but not as a default option in order to not break existing models.

There is also an option to put all the inertia on the surface of the mesh.

**Comment by arpit15** [comment]
@yuvaltassa can you kindly mention here where to get started for options to create models with concave meshes?

**Comment by arpit15** [comment]
I found ` shellinertia="true"` as the parameter to set inertia at surfaces. However, its unclear how to properly set up concave meshes.

**Comment by yuvaltassa** [comment]
There are two options for colliding with concave meshes:

1. Use a convex decomposition package like https://github.com/SarahWeiii/CoACD
2. Use Signed Distance Fields.
