### ISSUE TITLE
Model problem in Mujoco - Bulges exist on each joint 

### ISSUE THREAD

**Issue by JackTony123** [deepmind/mujoco#339]
Hello everyone,

Recently I build up a model on the newest Mujoco 2.2.0 for WAM robot arm and hand The arm looks good but the hand there exists something weird for that
![Problem_for_mujoco_WAM](https://user-images.githubusercontent.com/97269869/173127381-2dbdb901-1fc7-4bdb-bc90-dc60f70cb408.png)
I don't know why there exist bulges on each joint. Looks so weird. Did someone meet the same problem like that? How to deal with that? Thanks!

**Comment by kevinzakka** [comment]
Can you attach a zip file?

**Comment by JackTony123** [comment]
[wam7_Pro.zip](https://github.com/deepmind/mujoco/files/8881741/wam7_Pro.zip)

**Comment by kevinzakka** [comment]
These are related to the ` <geom mesh="bhand_finger_med_link_convex"/>` elements in the XML file.

**Comment by JackTony123** [comment]
> 

Thanks for your reply Kevin! That helps me so much! Not only for this element, but also for the other <geom mesh> parts, Now the model is normal. Thanks again! 
![Without_problem](https://user-images.githubusercontent.com/97269869/173146169-8bb62165-ed1c-4641-9e89-dfe992deda57.png)
