### ISSUE TITLE
Can not open STL file for custom environment int Colab

### ISSUE THREAD

**Issue by aliemil** [deepmind/mujoco#346]
Hey all,
I am trying to run my custom mujoco environment int google colab, but if I try to create the model from the xml it return that it cannot open the STL's (meshes) included.

To be said, on the local jupyter notebook/lab it runs without a problem.
Has anyone an idea what might cause the issue? 

![image](https://user-images.githubusercontent.com/74488721/173667717-c4ca4c78-db26-4545-97c6-6472704e2a41.png)

**Comment by kevinzakka** [comment]
Hey @aliemil, can you share the Colab? I can debug better that way.

**Comment by aliemil** [comment]
@kevinzakka The error seems to have been pretty silly. It started to run just by turning on the GPU on runtime. 
But thanks for the effort! :)
