### ISSUE TITLE
Does mujoco_py works with Mujoco2.2.0?

### ISSUE THREAD

**Issue by zhihaocheng** [deepmind/mujoco#347]
Hi,

Thanks for open source Mujoco, which is really helpful. I have tried to install Mujoco2.2.0 via building from source. How can I install mujoco_py if I build Mujoco from source? I failed to find relevant information because the installlation of mujoco_py is still based on a precomplied Mujoco.

**Comment by saran-t** [comment]
`mujoco_py` is no longer being maintained and will not work with MuJoCo 2.2.0. We recommend that you migrate to the `mujoco` package instead, which is developed and released alongside MuJoCo itself.
