### ISSUE TITLE
Getting started with sensors

### ISSUE THREAD

**Issue by mwinnick4** [deepmind/mujoco#353]
Hi,

I am first learning on how to use Mujoco and I am having some trouble with the sensors feature. The documentation isn't the most clear on how to start using sensors and then display the results of a contact events in the simulate window. For mow, I am just using the Hello World given by Mujoco (https://mujoco.readthedocs.io/en/latest/overview.html?highlight=hello.xml#examples) and trying to add a sensor on the bottom plane. The goal for now is for when the block hits the bottom "floor"/plane, the contact sensor would show readings that there was a contact event. Thank you for your help in advance! 

-Max

**Comment by kevinzakka** [comment]
Hi, @mwinnick4, one helpful thing you can start with is creating a site and visualizing it in the simulate window. Visualization is so helpful, and the simulate app makes this so easy to do!

For example, I added a box site in transparent blue and made it as wide and large as the plane:

<img width="1508" alt="Screen Shot 2022-06-21 at 7 02 07 PM" src="https://user-images.githubusercontent.com/10518920/174910675-9271b79b-df83-42c2-8156-6ca1d31c3bba.png">

Next, I added a touch sensor that references that site. When toggling the sensor button on the left pane, I can now visualize an impulse as the block falls down.

https://user-images.githubusercontent.com/10518920/174910429-83559a6b-856b-4329-a7d1-389dc708a357.mp4

Try using the [docs](https://mujoco.readthedocs.io/en/latest/XMLreference.html#sensor-touch) to do this. I'll add a hidden solution at the end of this response that you can toggle if you get stuck or want to confirm. Cheers 😊

<details>
  <summary>XML file</summary>
  
  ```XML
<mujoco>
  <worldbody>
    <light diffuse=".5 .5 .5" pos="0 0 3" dir="0 0 -1"/>
    <geom type="plane" size="1 1 0.1" rgba=".9 0 0 1"/>
    <site name="plane_contact" type="box" size="1 1" rgba="0 0 1 0.3"/>
    <body pos="0 0 1">
      <joint type="free"/>
      <geom type="box" size=".1 .2 .3" rgba="0 .9 0 1"/>
    </body>
  </worldbody>
  <sensor>
    <touch site="plane_contact"/>
  </sensor>
</mujoco>
  ```
</details>
