### ISSUE TITLE
Trying to compile python bindings from source

### ISSUE THREAD

**Issue by berniekirby** [deepmind/mujoco#354]
**How to ask for help**

Hi,

I'm an engineer and I'm trying to use MuJoCo for just compiling for some one else

I'm looking for some help with compiling python bindings

The error during compilation is:

      [ 25%] Built target absl_time_zone
      In file included from /tmp/pip-req-build-ucz75bg8/mujoco/enums.cc:22:
      /tmp/pip-req-build-ucz75bg8/mujoco/enum_traits.h:204:48: error: ‘mjGAIN_AFFINE’ is not a member of ‘mjtGain’ {aka ‘mjtGain_’}
        204 |     std::make_pair("mjGAIN_AFFINE", ::mjtGain::mjGAIN_AFFINE),
            |                                                ^~~~~~~~~~~~~

Several days ago the repo gave errors regarding "#pragma not allowed here" but that's in the past. The above is the current issue.
gcc == 12.1.0, It's on an old Centos6 cluster if that makes a difference.

**Comment by saran-t** [comment]
I suspect that you've downloaded the prebuilt MuJoCo 2.2.0 binary but are trying to build the Python bindings from `main`, where the new enum value was added recently (and crucially after our 2.2.0 release) in 307cf692e5bc3e22b3fb55a0ec0a7f2953eca348.

You have two options: either move your local Git repo to the state at our 2.2.0 release via `git checkout 2.2.0` and build the Python bindings from there, or build MuJoCo itself from `main` as well.

**Comment by berniekirby** [comment]
It's all source downloaded. I mean in the last couple of hours! (git cloned). prebuilt does not work on old Centos6 so it has to be compiled from source. Thank's for making it available at last!
Have complied and run successfully main mujoco but python bindings allude us with the given error...

**Comment by berniekirby** [comment]
Sure:
git clone.....
cd mujoco
(here we have so load some "environment" modules to get the software we need to use. Suffice to say:
we have gcc/12.1.0, cmake 3.21.0 and some other things available...
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/mujoco/2.2.0
make 
make install
cd ..
cd python
./make_sdist.sh

pip wheel dist/mujoco-2.2.0.tar.gz

Builds lots of stuff but errors out.
Back in the error list we see this:

    /tmp/pip-req-build-ucz75bg8/mujoco/enum_traits.h:204:48: error: ‘mjGAIN_AFFINE’ is not a member of ‘mjtGain’ {aka ‘mjtGain_’}
        204 |     std::make_pair("mjGAIN_AFFINE", ::mjtGain::mjGAIN_AFFINE),

**Comment by berniekirby** [comment]
I would be really great to have a Centos6/RHEL6 version. I know it's years old but some clusters like this cannot just "upgrade" the OS on a whim - although I've been arguing for that to happen for a number of years now!

**Comment by saran-t** [comment]
There are some pretty questionable security implications that comes with running an EoL operating system that no longer receives any update but, I guess that argument won't necessarily fly :)

**Comment by berniekirby** [comment]
Yes agree!!!
but be that as it may it is what it is. It's an isolated cluster. I can't change that. The people that own it are currently unwilling to change. There are literally thousands of bits of software that does the jobs they need and so they evaluate the risk and dollars to change accordingly.

**Comment by berniekirby** [comment]
The issue will be forced eventually because some some commercial software (eg ANSYS and MATLAB) is no longer supported on such an old OS. Anyway that doesn't help us here with this issue. mujoco compiles and runs. It's just building the python interface that is a problem...

**Comment by saran-t** [comment]
It seems that the Python build is somehow picking up MuJoCo headers from the wrong place. As documented [here](https://github.com/deepmind/mujoco/tree/main/python), you should set `MUJOCO_PATH` to `/usr/local/mujoco/2.2.0` when running `pip wheel`.

**Comment by berniekirby** [comment]
It's  nearly midnight here. I'll try tomorrow. I have indeed set MUJOCO_PATH already, Thanks for your help! Will revisit later on.

**Comment by saran-t** [comment]
Can you run `pip wheel` with the verbose flag and paste the full output somewhere? That might help us troubleshoot where it's getting the mujoco headers from.

**Comment by berniekirby** [comment]
Hi,
Got further this morning. I removed all installations and re cloned it rebuilt it all and now it builds and installs:
Successfully installed absl-py-1.1.0 glfw-2.5.3 mujoco-2.2.0 numpy-1.21.6 pyopengl-3.1.6

Thank you very much.
