### ISSUE TITLE
Provide official Python bindings

### ISSUE THREAD

**Issue by saran-t** [deepmind/mujoco#36]
MuJoCo should come with a canonical Python package that provides access to its C API. The package should be hosted on PyPI and installable via `pip install mujoco`.

The official bindings will be developed and continuously tested alongside MuJoCo itself. When this is done, we intend to reimplement our own RL framework `dm_control` on top of the new bindings.

The current plan is to create brand new bindings using pybind11.

**Comment by kfields** [comment]
I was thinking of doing it myself with a binding generator I've been working on, but from what I'm looking at this API needs a major overhaul.

I would suggest looking at [bgfx](https://github.com/bkaradzic/bgfx) as an exemplary role model.  Very homogenous.  It only took me two days to bind it!  C++ on the inside with a C API calling inward.  [Dear ImGui](https://github.com/ocornut/imgui) was also an easy target.

Let me know if you guys need any help.  This is so exciting!!!

**Comment by Amir-Arsalan** [comment]
@saran-t Thanks for all the efforts. A request: could you please make it possible to do seamless GPU rendering in headless mode as well? I have been using `mujoco-py` and could not enable headless GPU rendering. I know it seems possible to do this using `dm_control` but I remember as far as I remember `dm_control` did not have the flexibility that `mujoco-py` had so I had to stick with `mujoco-py` and tolerate the slow rendering.

**Comment by saran-t** [comment]
@Amir-Arsalan the rendering infrastructure is something that I'll be looking into, however given that GL context setup is currently left up to user code, I'm not sure if the logic for setting up headless GPU rendering will end up as part of MuJoCo's Python bindings.

Can you elaborate on what aspect of `dm_control` you find lacking compared to `mujoco-py`? (Note that `mujoco-py` just provides Python bindings whereas `dm_control` is also a fully fledged RL environment framework. Did you mean OpenAI Gym?)

**Comment by Amir-Arsalan** [comment]
@saran-t No I meant `mujoco-py`. I don't clearly remember the details but I think in `mujoco-py` I could access some of the underlying MuJoCo functionalities but I didn't have access to them in `dm_control`. I think they were related to camera 'rendering settings or maybe something like `model = mujoco_py.load_model_from_xml(xml_path); mujoco_py.MjSim(model).get_state().qpos`

**Comment by saran-t** [comment]
Got it. The `dm_control` bindings actually expose all of MuJoCo's API and structs (via `ctypes`), however I'll freely admit that the low-level bindings aren't very well-documented or very Pythonic since they're intended for internal use. The lack of documentation and non-intuitive bindings API are both things that we'll be looking to fix in the new bindings. Thanks for the feedback!

In the meantime, if you do want to try out the `dm_control` low-level bindings again please feel free to raise an issue at https://github.com/deepmind/dm_control/issues and we'll help you figure out how to achieve whatever it is that you need.
