### ISSUE TITLE
What could be the cause of mjWARN_BADQACC?

### ISSUE THREAD

**Issue by XinyuWang2** [deepmind/mujoco#383]
Hi, I am having a weird behavior in the mujoco simulator. The scenario is described below:
1. Two objects(box) are combined through a weld constraint. The smaller one is inside another. 
2. The smaller one can be controlled by slide actuators. 

Ideally, they should move together, slowly because of a small action, which does happen in most of the other scenarios.
However, for this rare one, all of a sudden, they move so abruptly. 

These are xyz locations of the smaller box in 5 consecutive physics.steps.  
[-0.54017543 -0.06785287  0.04978686] -> (activate constaint and keep it for later steps) -> step() -> 
[-0.54133    -0.0676916   0.04982307]  -> (movement between this and last step is indeed small), step() ->
[0.85014079 0.50555359 1.88797865] <------ magic happens from here !!
[-16.61497857 -17.21111811   1.36517479]
[1049.15584802 1045.70554427    5.04508734]

Actually, I have set joint range limit and the working space is surrounded by walls and a ceiling(the space is rather small, about 2x2x2). So ideally they should at least stay inside this space. 

Probably this is related to setting constraints. I found a previous post that says weird behavior might happen when objects are very small. But it didn't change anything when I change from one 0.05, one 0.01 box to one 0.05, one 0.03 box.

**Comment by yuvaltassa** [comment]
We can't reproduce without a model.

I suspect the two objects are contacting each other and the huge contact forces are causing divergence?
Activate contact force visualisation ('F' in `simulate`) to diagnose.

**Comment by Balint-H** [comment]
Just in case, but have you disabled collisions between the two objects?

**Comment by yuvaltassa** [comment]
Thanks @Balint-H,

Yes, that's what I meant.

**Comment by XinyuWang2** [comment]
Yes, having contacts is expected.
I think the main reason is that during the constraint activation, quaternion for relpose is [1, 0, 0, 0] and this correction step would lead to bad acc in some rare cases (e.g. there are so many rotations to make an object quaternion to [1, 0, 0, 0]). 
Fortunately, I later solved my issue by setting relpose by changing eq_data in the runtime. 

I also make a model that can reproduce the error. 

<mujoco model="base">
    <compiler boundmass="1e-05" boundinertia="1e-11" coordinate="local" angle="radian" eulerseq="xyz"/>
    <option timestep="0.002" density="1.2" viscosity="2e-05" impratio="20.0" cone="elliptic"/>
    <visual>
        <headlight ambient="0.3 0.3 0.3" diffuse="0.5 0.5 0.5" specular="0 0 0"/>
        <map znear="0.01"/>
    </visual>
    <asset>
        <texture name="texblock" type="cube" file="block.png" gridsize="3 4" gridlayout=".U..LFRB.D.."/>
        <material name="matblock" texture="texblock" rgba=".5 .5 .5 0.5"/>
    </asset>
    <default>
        <default class="cursor">
            <joint type="slide" pos="0 0 0" limited="true" range="-1 1" damping="0.5"/>
        </default>
        <default class="block">
            <geom type="box" size="0.05 0.05 0.05" friction="1 10 0.5" solref="0.001 1"/>
        </default>
    </default>
    <worldbody>
        <geom name="floor" type="plane" size="2 2 0.10" rgba="0.7 0.7 0.7 1"/>
        <body name="cursor" pos="0 0 0.05">
            <geom name="cursor_geom" type="sphere" size="0.01" rgba="1 0 0 0.5" margin="0.01" gap="10.0"/>
            <joint name="cursor_joint_x" class="cursor" axis="1 0 0"/>
            <joint name="cursor_joint_y" class="cursor" axis="0 1 0"/>
            <joint name="cursor_joint_z" class="cursor" axis="0 0 1" range="0.01 0.5"/>
            <inertial pos="0 0 0" mass="0.018" diaginertia="0.00017 0.00017 0.00017"/>
        </body>
        
        <body name="block0" pos="0 0 0" quat="0.001 0.707 0.0 0.707">
            <geom name="block_geom_0" class="block" material="matblock"/>
            <freejoint name="block_joint_0"/>
            <inertial pos="0 0 0" mass="0.01" diaginertia="0.00017 0.00017 0.00017"/>
        </body>
    </worldbody>
    <equality>
        <weld active="true" solref="0.01 0.3" solimp="1 1 0.5 0.5 2" body1="cursor" body2="block0" relpose="0 0 0 1 0 0 0"/>
    </equality>
    <actuator>
        <motor name="cursor_joint_x" ctrllimited="true" ctrlrange="-0.3 0.3" joint="cursor_joint_x"/>
        <motor name="cursor_joint_y" ctrllimited="true" ctrlrange="-0.3 0.3" joint="cursor_joint_y"/>
        <motor name="cursor_joint_z" ctrllimited="true" ctrlrange="-0.2 0.2" joint="cursor_joint_z"/>
    </actuator>
</mujoco>
