### ISSUE TITLE
Automatically generate the API reference

### ISSUE THREAD

**Issue by nimrod-gileadi** [deepmind/mujoco#4]
The API reference ([doc/APIreference.rst](https://github.com/deepmind/mujoco/blob/main/doc/APIreference.rst)) is currently written by hand. This means it immediately goes out of date with any changes to the API.

We need a solution for auto-generating the API reference that satisfies the following requirements:

  - It is complete: either every function is automatically included, or we get a build error if anything is missing.
  - Code snippets defining structs should automatically be included.
  - Function signatures are automatically included (either as a code snippet, or in a different standard form).
  - We have control of the ordering and grouping of functions / data types.
  - We can write extra bits of reStructuredText around the automatically generated functions (e.g the blurbs about "primitive types" or "physics callbacks").

**Comment by benelot** [comment]
As far as I can tell, mujoco is written in C/C++, right? It seems you could read the documentation from the source with doxygen and then bridge it into sphinx via breathe (https://devblogs.microsoft.com/cppblog/clear-functional-c-documentation-with-sphinx-breathe-doxygen-cmake/). What would give you the ability to generate modern documentation directly from source.
