### ISSUE TITLE
What are the max lengths of things like `d->cinert` and `d->qfrc_actuator`

### ISSUE THREAD

**Issue by MotorCityCobra** [deepmind/mujoco#412]
How would you calculate the max lengths of these, depending on the number of pieces and joints in one's model?

**Comment by kevinzakka** [comment]
Did you check the MjData docs?

**Comment by MotorCityCobra** [comment]
Yes. I must have missed something. I typically just see a comment on the same line that says 1x, 4x. I’m not seeing detailed descriptions.

**Comment by MotorCityCobra** [comment]
`d->cvel` has a note for `nbody x 6`.  
But I have 14 bodies. `m->nbody` is 14.  
But it looks like there are maybe 360 numbers in this `d->cvel` object.  
This is why I'm asking, I must be missing something. 6 * 14 is 84 and 360 / 84 is not an integer. So, I must be missing something.

**Comment by saran-t** [comment]
> But it looks like there are maybe 360 numbers in this `d->cvel` object.

What makes you think that there are 360 numbers in `cvel` ?

**Comment by MotorCityCobra** [comment]
Because there are numbers in all positions indexed up to 360.

**Comment by saran-t** [comment]
You're technically reading out of bounds here. In C/C++ there's nothing to stop you from reading from memory locations that are beyond the end of the array.

In this particular case, `mjData` arrays are located next to each other, so what's happening is you're getting data from other arrays. More generally, this sort of thing can lead to you getting garbage or crashing the entire process through SIGSEGV.

**Comment by MotorCityCobra** [comment]
> there's nothing to stop you from reading from memory locations that are beyond the end of the array.

I see. Thank you. Coming from Python and not knowing much about C/C++ I thought I was / would be getting zeros after I was out of bounds. Thank you.
