### ISSUE TITLE
Build binary for linux aarch64

### ISSUE THREAD

**Issue by brandimarte** [deepmind/mujoco#42]
Currently only Linux x86 binaries are available. It would be nice to have it for aarch64 architecture.

**Comment by zyp57783** [comment]
The same question!

**Comment by yuvaltassa** [comment]
We completely agree 👍 
Stay tuned.

**Comment by Br3hman** [comment]
Looking forward to get 64 bit too. Mainly because I would like to try on windows subsystem Linux WSL. I was stupid enough to updated to windows 11 and I can't run any simulation anymore. I am not sure what is the connection but I will either switch back to windows 10 or use WSL.

**Comment by saran-t** [comment]
@Br3hman just to be clear, this issue is about AArch64 (i.e. ARM) binaries. Our existing x86 binaries are already 64-bit.

**Comment by Br3hman** [comment]
@saran-t thank you for pointing out. I will try to fix issue at my mind with WSL. It doesnt give me enough information to go on with it so far only say that "Illegal instruction". Maybe I am missing something. Sorry for spamming this thread.
Thanks 
Bilal

**Comment by Chandanpanda** [comment]
Absolutely! Needed for Jetson platform...

**Comment by saran-t** [comment]
AArch64 build is now available as part of our 2.1.1 release.

**Comment by Br3hman** [comment]
This is great. Thanks, I will try it out today. Cheers.

**Comment by Br3hman** [comment]
@saran-t in the next release could you also provide windows build binaries too as a wish list from my side.
