### ISSUE TITLE
what is the new substitution of MjViewer from the old mujoco_py?

### ISSUE THREAD

**Issue by Bunnyhop-peach** [deepmind/mujoco#440]
Hi,

I'm a student trying to use MuJoCo for robot arm controller tests.

I'm looking for some help with migrating the mujoco_py code to the deepmind mujoco.

Here is an example code that explains my question:(python)
self._sim = mjp.MjSim(self._model)
self._viewer = mjp.MjViewer(self._sim) if render else None

So, is there any way to have the same interactive window in deepmind mujoco?

Thanks~

**Comment by yuvaltassa** [comment]
We hope the long term replacement will be be based on @aftersomemath's WIP at #419 (or similar), will keep you posted as soon as it's ready. 

Cheers

**Comment by yuvaltassa** [comment]
I should have mentioned, `dm_control` does have a [Python-based viewer](https://github.com/deepmind/dm_control/tree/main/dm_control/viewer). Did you try using that?

Closing.

**Comment by Bunnyhop-peach** [comment]
> I should have mentioned, `dm_control` does have a [Python-based viewer](https://github.com/deepmind/dm_control/tree/main/dm_control/viewer). Did you try using that?
> 
> Closing.

Not yet, I'll have a look at it, thanks ;-)

**Comment by yuvaltassa** [comment]
See #576
