### ISSUE TITLE
Issue of Tunneling

### ISSUE THREAD

**Issue by miyukin73** [deepmind/mujoco#441]
Hi,

I'm a student and I'm trying to use MuJoCo for my research.

I'm looking for some help with "Tunneling".

Here is a video, illustrating my question:

(1) If the cup moved slowly, the balls in the cup didn't exit.

https://user-images.githubusercontent.com/63595993/185095546-a9573cd5-5f65-4ba1-aae7-fe795cc2c122.mov

(2) However, if the cup moved quickly, the ball  slipped through the cup.

https://user-images.githubusercontent.com/63595993/185095700-c632153b-1b05-444c-929f-803e2fc51e7e.mov

Is it possible to solve this problem?
Thank you in advance.

**Comment by yuvaltassa** [comment]
Make the cup thicker and/or reduce the timestep.
