### ISSUE TITLE
How to implement actuator's action 'change' boundary?

### ISSUE THREAD

**Issue by pjhae** [deepmind/mujoco#444]
Hi,

I'm a student  and I'm trying to use MuJoCo for robot control.

I'm looking for some help with **action 'change' boundary** ( not action boundary itself)

Here is a model which explains my question:

    <actuator>
        <position class="hexy" name="FR1" joint="FR1" ctrlrange="-0.6 0.6"/>
        <position class="shin" name="FR2" joint="FR2" ctrlrange="-1.2 -0.2"/>
        <position class="foot" name="FR3" joint="FR3" ctrlrange="-0.2 0.6"/>
        <position class="hexy" name="MR1" joint="MR1" ctrlrange="-0.6 0.6"/>
        <position class="shin" name="MR2" joint="MR2" ctrlrange="-1.2 -0.2"/>
        <position class="foot" name="MR3" joint="MR3" ctrlrange="-0.2 0.6"/>
    </actuator>

</details>

From above code, there is 6 actuators. and I set the boundary like ' ctrlrange="-0.6 0.6" ' for six actuators.

But, considering **real robot deployment** , there is also **action change limit due to overloading of motors.**

for example, 'FR1" motor's action(position) should satisfy this equation :

**|| Action_fr1_{t+1}    -    Action_fr1_{ t }  ||   < 0 .1** 

How can I implement this equation on mujoco settings?

Thank you for reading my question!  : )

**Comment by traplotz** [comment]
Have you tried using velocity control instead and limiting the range of each joint? 
For example, <joint name="FR1" type="??" axis="?? ?? ??" limited="true" range"-0.6 0.6"/>
