### ISSUE TITLE
Unable to access mujoco forum

### ISSUE THREAD

**Issue by Ankur-Deka** [deepmind/mujoco#45]
The link https://mujoco.org/forum/index.php doesn't seem to work anymore. Could you please make it accessible again? I found a discussion on a doubt at this link through google search only to realize that the link doesn't work anymore.

![image](https://user-images.githubusercontent.com/29336467/140622486-d9b32ff3-f00a-493e-a731-46b2d8c2c431.png)

![image](https://user-images.githubusercontent.com/29336467/140622502-75e43e0d-36eb-4e44-aa84-df073bc4e674.png)

**Comment by yuvaltassa** [comment]
In order to access the old forum, replace `mujoco.org` with `roboti.us` in your URL.
We might set up a redirect on `mujoco.org`, thanks for pointing this out.

**Comment by saran-t** [comment]
I've set up a redirect page on mujoco.org so that you're sent to the right place rather than 404s.

**Comment by Ankur-Deka** [comment]
Thank you @yuvaltassa and @saran-t

**Comment by pab47** [comment]
The older forum on this link does not seem to work anymore: https://roboti.us/forum/index.php
I tried different browsers (chrome/safari) with no luck. There was a wealth of information on that forum.

**Comment by yuvaltassa** [comment]
Just delete the 's' from 'https', it works.

**Comment by pab47** [comment]
Thanks. Just putting the complete linking for easy navigation. Please close the ticket.
http://www.roboti.us/forum/index.php
