### ISSUE TITLE
How to make env with gym

### ISSUE THREAD

**Issue by yingchengyang** [deepmind/mujoco#458]
Hi,

I'm a phd student and I'm trying to use MuJoCo for research.

I'm looking for some help with mujoco and gym.

Can I directly use the following instructions?

pip install gym
pip install mujoco

import gym
env = gym.make("Ant-v3")

That's all! Thank you.

**Comment by kevinzakka** [comment]
The latest `v4` environments in Gym use the official (aka this repository) Python bindings. So all you need to do is `pip install "gym[mujoco]"`, as described [here](https://github.com/openai/gym#mujoco-environments).

**Comment by yingchengyang** [comment]
Thanks a lot!

**Comment by BaiYunpeng1949** [comment]
Hi

I am also a rookie trying to use mujoco + gym. How can I customize my mujoco environment which is inherited from gym.Env and could be used as normal gym environments in reinforcement learning? Should I follow the templates stating 'myEnv' class like [here](https://github.com/openai/gym/blob/master/gym/envs/mujoco/mujoco_env.py) (from line 28)? Or could you please recommend me some examples?

Many thanks!
