### ISSUE TITLE
mujoco_up  with  "distutils.errors.CompileError: .......failed with exit code 2"  "distutils.errors.DistutilsExecError:"

### ISSUE THREAD

**Issue by liyuanhao-star** [deepmind/mujoco#460]
Hi,

I'm a student and I'm trying to use MuJoCo for doing reinforcement learning in robotics

I'm looking for some help with the question as stated in the question

After I installed the "mujoco_py",when I import this package, this problem occurred:
![屏幕截图 2022-08-29 202557](https://user-images.githubusercontent.com/65451831/187200646-8b213061-c4c4-47ff-af91-a6586b754fe6.png)

**Comment by saran-t** [comment]
`mujoco_py` is a third-party package that we do not support, and that project is now dormant. Can you use the `mujoco` package instead?

**Comment by liyuanhao-star** [comment]
> `mujoco_py` is a third-party package that we do not support, and that project is now dormant. Can you use the `mujoco` package instead?

Thank you for your answer. I will try your suggestion
