### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by NgChucky** [deepmind/mujoco#470]
Please add an option to download the MuJoCo documentation at Read The Docs as HTML or PDF.

**Comment by kevinzakka** [comment]
Note you can build your own docs via:

```
git clone https://github.com/deepmind/mujoco.git
cd mujoco/doc
pip install -r requirements.txt
make html
```

Then just open `_build/html/index.html` in your favorite browser.

**Comment by NgChucky** [comment]
Thanks!

**Comment by YadavAkhileshh** [comment]
Hi!  @thowell  I'd like to work on this. I've investigated the repo 
and found the TODO comment at .readthedocs.yml. I plan to enable 
PDF/HTML downloads by fixing the LaTeX configuration. May I work on this?
