### ISSUE TITLE
Initializing a simulation with a desired contact force?

### ISSUE THREAD

**Issue by stracovskylu** [deepmind/mujoco#474]
I'm interested in finding out how I can initialize a mujoco simulation to some initial state where an object is held in a grasp. From what I read on the mujoco docs and some fiddling I've done, I believe I can change the initial force of some contact by tweaking the poses of both geoms to adjust the contact penetration and of course changing the forces applied to each geom from actuators etc... However this does seem quite roundabout, especially considering that contact penetrations and the contact normal forces sometimes vary in ways I can't immediately make sense of. Can I have some advice on how to go about initializing a simulation with a desired contact force? Hopefully there is a better way than what I described?

**Comment by erez-tom** [comment]
There is no better way.  As you say, the contact force is a function of the position and actuation, so you have to search over this space to find a combination (there are probably infinitely many) that generates the desired force.  Note that the contact force is a differentiable function of the state and action, so you could use gradient-based optimization.  Changing the contact solver parameters (`solref`, `solimp`) can make the contacts softer (and therefore the optimization easier), so you could use a continuation method.
