### ISSUE TITLE
Initialize objects in collision free random states

### ISSUE THREAD

**Issue by Ankur-Deka** [deepmind/mujoco#48]
### Discussed in https://github.com/deepmind/mujoco/discussions/47

<div type='discussions-op-text'>

<sup>Originally posted by **Ankur-Deka** November  6, 2021</sup>
I am using mujoco-py. The current approach I am using is to initialize in random states and then check for collision using a script which is similar to the following.

```
'''
code to initialize in random state
'''

try:
          self.sim.forward()
except mujoco_py.MujocoException as e:
          continue
contacts = self.get_contacts(object)
if len(contacts) > 0:
          print('collision detected, try sampling a new state')
```

It works most of the time but once in a while it fails. The object is initialized in a collision state and gets thrown away in the scene and the snippet above doesn't detect the collision. Since I am calling sim.forward (and NOT sim.step), [there shouldn't be any integration in time as per documentation](https://github.com/deepmind/mujoco/blob/1f7eaae62e0cd45a71cf7a593fa5605720765167/include/mujoco.h#L154) and correspondingly the plate shouldn't have been thrown away. How can I avoid the object being thrown away or how can I correctly sample collision free random states using an alternate approach?
</div>

**Comment by yuvaltassa** [comment]
We are not very familiar with `mujoco-py` but you are definitely doing the right thing, so keep looking for a bug. `step` is being called somewhere if your object is moving. I recommend printing values of `data.time` to figure out where the integration happens.
