### ISSUE TITLE
Add Mujoco to Conda-forge

### ISSUE THREAD

**Issue by pseudo-rnd-thoughts** [deepmind/mujoco#480]
Are there any plans to add mujoco to conda forge? 
It is generally recommended that all submodules on conda should also be on conda.
Therefore, having mujoco on conda would allow a number of RL projects to be on conda as well

**Comment by traversaro** [comment]
There is a mujoco feedstock: https://github.com/conda-forge/mujoco-feedstock , even if (at least at the moment) it is not mantained by the original mantainer team of mujoco.

**Comment by pseudo-rnd-thoughts** [comment]
Sorry, I didn't see it.
