### ISSUE TITLE
You can apply external Cartesian forces to body CoMs using `xfrc_applied`, or at a site using site transmission. Check the documentation for details.

### ISSUE THREAD

**Issue by kpydv** [deepmind/mujoco#489]
You can apply external Cartesian forces to body CoMs using `xfrc_applied`, or at a site using site transmission. Check the documentation for details.

_Originally posted by @yuvaltassa in https://github.com/deepmind/mujoco/issues/485#issuecomment-1249449917_

I checked the documentation I did not find any way to apply xfrc_applied at the site.
Please help me out.

**Comment by yuvaltassa** [comment]
Here's how to do it with a site transmission. This is explained [here](https://mujoco.readthedocs.io/en/latest/computation.html#transmission), example model [here](https://github.com/deepmind/mujoco/blob/main/test/engine/testdata/refsite.xml).

Put a site `force_site` where you want to apply your force. Put a reference site `reference_site` say at the origin of the world. then if you make an actuator like

```xml
<actuator>
  <motor name="y"  site="force_site" refsite="reference_site" gear="0 1 0 0 0 0"/>
</actuator>
```

then the actuator will apply forces in the `Y` axis (of the reference site).
