### ISSUE TITLE
Legacy Mujoco Forum NOT sending confirmation email

### ISSUE THREAD

**Issue by nrkumar93** [deepmind/mujoco#497]
I am trying to download the attachment from [this forum post](https://www.roboti.us/forum/index.php?threads/replaying-kinematics-using-mj_inverse-output-to-drive-actuators.3821/). It needs me to create a Mujoco account to access the files. 

But I am unable to even after creating an account because I don't receive the confirmation email. I have tried many emails. 

Any help in getting those attachments is appreciated.

**Comment by saran-t** [comment]
I'll raise this issue with Roboti.

**Comment by yuvaltassa** [comment]
This is now fixed.
