### ISSUE TITLE
Generate detail convex hull in mesh geom

### ISSUE THREAD

**Issue by azharauliasaputra** [deepmind/mujoco#499]
I would like to build an object from STL file which have detail surface triangulation not only for geom visualization.
Could you let me know how to set it in the XML file?

**Comment by kevinzakka** [comment]
Hi @azharauliasaputra, one way to do this is to disable collisions for your visual meshes and enable them for your collision meshes. You then define 2 geoms in your body, one for the visual one and one for the collision one.

The [mujoco_menagerie](https://github.com/deepmind/mujoco_menagerie) repo has nice examples of how to do this. In particular, check out the [`panda.xml`](https://github.com/deepmind/mujoco_menagerie/blob/main/franka_emika_panda/panda.xml) file.
