### ISSUE TITLE
Violation of mjtSTAGE contract by mj_Euler()

### ISSUE THREAD

**Issue by yuvaltassa** [deepmind/mujoco#5]
MuJoCo provides an explicit contract related to the `mjtSTAGE` enum: All computations requiring only position and velocity (`mjSTAGE_POS` and `mjSTAGE_VEL`) happen in `mj_step1()`, while computations related to accelerations and forces (`mjSTAGE_ACC`) happen in `mj_step2()`.

This contract is violated by the mass-matrix modification that happens in `mj_Euler()` related to implicit integration of joint damping, since the output computation depends only on positions. This issue shows up, for example, when trying to perform efficient finite-differencing of `mj_step()` skipping position-related computations when differencing velocities or controls.

**Comment by emotodorov** [comment]
This is by design actually. The "contracts" implemented via mjSTAGE_xxx apply to the continuous-time dynamics (mj_forward and mj_inverse).  Also, mj_Euler restores the mass matrix and its factorization after the modifications.
