### ISSUE TITLE
Allowing overlap between geoms while still checking for collisions

### ISSUE THREAD

**Issue by LitMSCTBB** [deepmind/mujoco#502]
Hi,

I'm a student and I'm trying to use MuJoCo for a motion planning example. I have a body that would represent the `chassis` of my vehicle. I make the chassis move via program, and when it collides with a geom that is in my `obstacles` body, the vehicle would stop, as expected. However, I want it to continue moving through the geom itself, while still maintaining the collision data that is given by `d->contact` in the API. Is there any way to do this via XML or programming?

Here is a very simplified model that fits my scenario:

```XML
<mujoco>
  <worldbody>
    <light diffuse=".5 .5 .5" pos="0 0 3" dir="0 0 -1" />
    <geom type="plane" size="5 5 0.1" rgba=".9 .9 .9 1" />
    <body name="chassis" pos="-5 -4 0.2" euler='0 90 0'>
      <joint type="free" />
      <geom type="box" size=".05 .2 .5" rgba=".9 .9 0 1" />
    </body>
    <body name="obstacles" pos="0 0 0" euler="0 0 0">
      <!-- <joint type="free" /> -->
      <geom name="obs-0" type="box" size="0.375 0.175 0.5" pos="-4.375 -4.525 0.5" rgba=".9 0 0 1" />
      <geom name="obs-1" type="box" size="1.2 1.3 0.5" pos="-1.2000000000000002 2.8 0.5" rgba=".9 0 0 1" />
      <geom name="obs-2" type="box" size="2.75 0.85 0.5" pos="0.25 -3.85 0.5" rgba=".9 0 0 1" />
      <geom name="obs-3" type="box" size="0.975 0.575 0.5" pos="-3.975 0.4249999999999998 0.5" rgba=".9 0 0 1" />
      <geom name="obs-4" type="box" size="1.25 0.975 0.5" pos="1.25 1.0250000000000004 0.5" rgba=".9 0 0 1" />
      <geom name="obs-5" type="box" size="0.275 1.175 0.5" pos="4.725 -2.675 0.5" rgba=".9 0 0 1" />
      <geom name="obs-6" type="box" size="0.65 0.625 0.5" pos="2.8499999999999996 2.825 0.5" rgba=".9 0 0 1" />
      <geom name="obs-7" type="box" size="1.15 1.05 0.5" pos="-3.1 -1.2000000000000002 0.5" rgba=".9 0 0 1" />
    </body>
  </worldbody>
</mujoco>
```
Appreciate any help.

Thanks

**Comment by yuvaltassa** [comment]
Yes. You can do this using the margin/gap mechanism.

Look at [this video](https://youtu.be/BcHZ5BFeTmU) and note the colour of the contact cylinders. Orange are active, force-producing contacts, while blue are "excluded" contacts which produce no force but can be used for other things (adhesion actuators in the video). Inspect the [model](https://github.com/deepmind/mujoco/tree/main/model/adhesion) shown in the video and search the documentation for more info.
