### ISSUE TITLE
Setting up MuJoCo (Python Bindings)

### ISSUE THREAD

**Issue by SerhiiBahdas** [deepmind/mujoco#506]
**Setting up MuJoCo (Python Bindings)**
Hello,

I'm a PhD student in Neuroscience and I'm trying to use MuJoCo to create a multi-DOF human arm model.

I'm looking for some help with using Python Bindings. After importing MuJoCo `import mujoco` and trying to use its modules, for example, `MjModel`, I always get an error shown on the screenshots below. I can't wait to start coding, but this minor issue prevents me from doing so. 

Example from Spyder (using it through Anaconda):
<img width="632" alt="Screen Shot 2022-09-27 at 3 26 56 PM" src="https://user-images.githubusercontent.com/48978895/192619035-5c82c493-f13e-470a-b7ea-5f3a48da5496.png">

Example from Terminal:
<img width="783" alt="Screen Shot 2022-09-27 at 3 23 07 PM" src="https://user-images.githubusercontent.com/48978895/192619055-5af6ebe9-5240-48a0-ac78-56ba0420c71f.png">

Thanks a lot, 
Serhii

**Comment by saran-t** [comment]
A bit of a guess here, but I think your Anaconda installation is using Intel binaries rather than Apple Silicon. Are you using an Apple Silicon machine?

**Comment by SerhiiBahdas** [comment]
Hi Saran, 

Thanks a lot for getting back to me this fast! Yes, I am using an M1 Mac, and I overlooked that I installed the Intel-based Anaconda. I wiped it out, reinstalled Anaconda, and everything works now! Thank you! 🙌

<img width="717" alt="Screen Shot 2022-09-28 at 12 51 49 AM" src="https://user-images.githubusercontent.com/48978895/192690858-d6084952-9be4-4aeb-b044-a3b93bf24ce6.png">
