### ISSUE TITLE
In there any plan to implement sensors like ballquat and ballangvel?

### ISSUE THREAD

**Issue by zhihaocheng** [deepmind/mujoco#509]

**Comment by yuvaltassa** [comment]
What do you mean? They are [already](https://mujoco.readthedocs.io/en/latest/XMLreference.html#sensor-ballquat) [implemented](https://mujoco.readthedocs.io/en/latest/XMLreference.html#sensor-ballangvel)?

**Comment by zhihaocheng** [comment]
Thanks very much. I think I had some misunderstandings in the past.
