### ISSUE TITLE
CPU Q6600 - program cannot start

### ISSUE THREAD

**Issue by father-fat** [deepmind/mujoco#510]
mujoco-2.2.2(2.2.1)-windows-x86_64\bin\simulate.exe fails to run on windows 10/7 without messages.

**Comment by saran-t** [comment]
That CPU is [15 years old](https://www.intel.co.uk/content/www/uk/en/products/sku/29765/intel-core2-quad-processor-q6600-8m-cache-2-40-ghz-1066-mhz-fsb/specifications.html), and specifically it doesn't support AVX.

You'll need to [build MuJoCo from source](https://mujoco.readthedocs.io/en/latest/programming.html#building-mujoco-from-source).
