### ISSUE TITLE
How to have different frictional coefficients in the same axis ?

### ISSUE THREAD

**Issue by TextZip** [deepmind/mujoco#514]
Hi,

I'm a (student) and I'm trying to use MuJoCo for deep reinforcement learning.

### Issue 
I'm looking for some help with implementing different frictional coefficients for forward movement and backward movement along the same axis.

### Use Case 
I am currently exploring locomotion in snake-like robots and as mentioned in this [paper](https://iopscience.iop.org/article/10.1088/1748-3190/ab9e51). 

> The frictional anisotropy is given as the ratio and difference between the friction coefficients for the forward and backward motion. Since the friction coefficients in the forward direction are always smaller than in the backward direction the frictional anisotropy is always positive (or larger as one). For the investigated seven species, the average friction coefficient in the backward direction is typically about 10% larger than in the forward direction. On N. atra, frictional anisotropy even reaches 20%. 

I was able to find an implementation of an anisotropic friction coefficient in #67 , but it is between different axis.

Is there any way this can be implemented?
Thanks in advance

**Comment by yuvaltassa** [comment]
Unfortunately no, this cannot be implemented in native MuJoCo.

The only solution I can imagine is to manually change the friction coefficient at runtime as a function of velocity.
If this is something that you want to try, make a toy model and code that does this, don't use the full snake model. Besides being easier to understand and debug, it will be easier for us to help you if you get stuck.

**Comment by diuuuuuuuuuuuuuu** [comment]
Well, I want to know how to manually change the friction coefficient at runtime as a function of velocity?

**Comment by yuvaltassa** [comment]
@diuuuuuuuuuuuuuu in Python or C?

Say in Python:
```py
model.geom({geom name or id}).friction[0] = my_fun(data.qvel)
```

Or something along those lines. Note that the actual properties of a contact are combined according to some rules between the two participating geoms (unless using the explicit `<pair>` [clause](https://mujoco.readthedocs.io/en/latest/XMLreference.html#contact-pair)), as explained [here](https://mujoco.readthedocs.io/en/latest/modeling.html#contact-parameters).

**Comment by diuuuuuuuuuuuuuu** [comment]
@yuvaltassa  Yes. In Python. I will try. Thank you very much!
