### ISSUE TITLE
Help with actuators

### ISSUE THREAD

**Issue by dreamxjei** [deepmind/mujoco#516]
Hi,

I'm an engineer and I'm trying to use MuJoCo for visualizing and manipulating a Universal Robot UR3e robot.

I'm looking for some help with actuators - specifically, examples I have looked at and loaded work perfectly, with each joint controllable. I have tried building my own XML using the official files from Universal Robot's website (https://www.universal-robots.com/download/mechanical-e-series/ur3e/robot-ur3e-jt-file-e-series/) which I converted to STLs, also attached. I noticed that to get any movement, I need to set kp to obscenely high values, and the resulting motion oscillates.

Here is a model which explains my question - I included only ground and base to make things easier:

<details>
  <summary>minimal XML</summary>

```XML
<mujoco model="ur3e">
    <compiler inertiafromgeom="auto" angle="degree" meshdir="./mesh/ur3e/collision/" texturedir="./mesh/ur3e/visual/" />
    <option gravity="0 0 -9.81" collision="predefined" />
    <asset>
        <mesh name="ground"     file="GroundModel.stl" />
        <mesh name="base"       file="BaseOffModel.stl" />
    </asset>
    <default>
        <default class="ur3e_actuator">
            <position ctrllimited="true" kp="1000000" ></position >
        </default>
    </default>
    <worldbody>
    <body name="ground" pos="0 0 0">
        <geom type="mesh" contype="0" conaffinity="0" group="1" rgba="0.7 0.7 0.7 1" mesh="ground" />
        <geom type="mesh" rgba="0.7 0.7 0.7 1" mesh="ground" />
        <body name="base_link" pos="0 0 151.85">
            <joint name="base_joint" pos="0 0 0" axis="0 0 1" limited="true" range="-360 360" />
            <geom type="mesh" contype="0" conaffinity="0" group="1" rgba="0.7 0.7 0.7 1" mesh="base" />
            <geom type="mesh" rgba="0.7 0.7 0.7 1" mesh="base" />
        </body>
    </body>
    </worldbody>
    <actuator>
        <position class="ur3e_actuator" name="base_pos" joint="base_joint" ctrlrange="-360 360" gear="1000" ></position >
    </actuator>
</mujoco>
```

</details>

Here is a screenshot where I set the actuator to 360 degrees but resulting rotation is a fraction of that, as well as the two relevant STL models:
![image](https://user-images.githubusercontent.com/36979947/194394945-920608b9-de70-472c-bbaa-8fb9b0f8c206.png)

[collision.zip](https://github.com/deepmind/mujoco/files/9727640/collision.zip)

Thank you very much.

**Comment by kevinzakka** [comment]
Hi @dreamxjei, the masses are absurdly high in your model (you can check by inspecting `body_subtreemass` in the file generated by `PRINT MODEL`. You should specify them using proper inertial tags, see [the official URDF files](https://github.com/ros-industrial/universal_robot/tree/kinetic-devel/ur_e_description) for those.

FYI, the MuJoCo team recently released a [UR5e MJCF](https://github.com/deepmind/mujoco_menagerie/tree/main/universal_robots_ur5e) in [MuJoCo Menagerie](https://github.com/deepmind/mujoco_menagerie). The README in there details the steps that were taken to convert the URDF file to a working XML one. Should be almost identical if you want to create an XML for the UR3.
