### ISSUE TITLE
How to connect two bodies using two joints

### ISSUE THREAD

**Issue by awef2** [deepmind/mujoco#519]
Hi,

I'm a student and I'm trying to use MuJoCo for muscle simulation.

I'm looking for some help with joints.

I am trying to make a "mouth" or "eye" where I have a uniform upper "lip" and a uniform lower "lip". To allow the mouth to open and close, the points of connection should be at the corners of the lips.  

Here is an image of the mouth when it is fully open: 

![aA](https://user-images.githubusercontent.com/115386003/194737518-8013388d-a36c-493e-913d-5fe625f0f1b7.png)

I have tried adding ball joints to the corners. Here is my model:

![www](https://user-images.githubusercontent.com/115386003/194737455-1611ca58-1fc4-4bfb-af2b-c53dab138600.PNG)
This is the error I get: `Error: ball followed by rotation in body ''
Object name = , id = 1, line = 11, column = -1`

As a result, I have also tried looking at using two hinges. Here is my model:

![adds](https://user-images.githubusercontent.com/115386003/194737567-f64cb93c-b611-49e0-a0fb-951a6ca385db.PNG)

However, then I get this error: `WARNING:absl:Inertia matrix is too close to singular at DOF 0. Check model. Time = 0.0000.`

How should I proceed?

**Comment by yuvaltassa** [comment]
You are getting the latter error because your two hinges are parallel, which is probably not what you want.
