### ISSUE TITLE
Body break simulation

### ISSUE THREAD

**Issue by antonioaa1979** [deepmind/mujoco#525]
Hi, I am playing with MuJoCo to experiment with RL agents, just for fun. I am using the dm_control python wrapper.

I was wondering if it is possible to use some tricks to somehow simulate a body breakage at runtime? I am thinking for example to have 2 bodies linked by a joint, and once a certain force is sensed on the joint, I could dynamically 'remove' the joint to let the 2 bodies 'fall apart'. Is this somehow achievable? Any directions?

Thanks very much,
Antonio

**Comment by Balint-H** [comment]
As suggested by https://github.com/deepmind/mujoco/issues/197, you could potentially use weld constraints for this. If you have kinematic chain A-B-C, you could create A-B1 and B2-C and disable collisions (and rendering) for B2. Then you can deactivate the weld between B1 and B2 by changing `eq_active` in the model.

**Comment by TheMessik** [comment]
@antonioaa1979 have you been able to get it working? I've been trying to bring this idea into life, without much success. See below my attempt
```
<mujoco model="BrittleStarMorphology">
  <compiler angle="radian"/>
  <default>
    <default class="/">
      <geom contype="1" conaffinity="0" condim="3"/>
    </default>
  </default>
  <worldbody>
    <body name="main">
      <geom type="box" size="1 1 1"/>
      <body name="A" pos="1.5 0.5 0.5">
        <joint pos="-1.5 0.5 0.5" name="A_in_plane" class="/" type="hinge" axis="0 0 1" limited="true" stiffness="1.1084000000000001" range="-0.52359877559829882 0.52359877559829882" armature="0.45000000000000001" damping="5.5084"/>
        <joint pos="-1.5 0.5 0.5" name="A_out_plane" class="/" type="hinge" axis="0 -1 0" limited="true" stiffness="1.1084000000000001" range="-0.52359877559829882 0.52359877559829882" armature="0.45000000000000001" damping="5.5084"/>
        <geom type="box" size="0.5 0.5 0.5"  rgba="1 0 0 1"/>
      </body>
      <body name="B" pos="2.5 0.5 0.5">
          <geom type="box" size="0.5 0.5 0.5" rgba="0 1 0 1"/>
          <joint name="B_in_plane"  pos="-0.5 0.5 0.5" class="/" type="hinge" axis="0 0 1" limited="true" stiffness="1.1084000000000001" range="-0.52359877559829882 0.52359877559829882" armature="0.45000000000000001" damping="5.5084"/>
          <joint name="B_out_plane" pos="-0.5 0.5 0.5" class="/" type="hinge" axis="0 -1 0" limited="true" stiffness="1.1084000000000001" range="-0.52359877559829882 0.52359877559829882" armature="0.45000000000000001" damping="5.5084"/>
        </body>

    </body>

    <camera name="side_camera" class="/" mode="track" pos="0 -2 2.5" quat="0.93969262078590843 0.34202014332566871 0 0"/>
  </worldbody>
    <equality>
      <weld body1="A" body2="B" anchor="2.5 0.5 0.5"/>
    </equality>
  <actuator>
  </actuator>
  <sensor>
  </sensor>
</mujoco>
```
After adding the weld constraint, I'd expect for body B to move when body A is moved using body A's joints, but I don't see this happen in the mujoco viewer.
Any help would be greatly appreciated.

**Comment by antonioaa1979** [comment]
Hi, long time since i did this, but i indeed followed the recommendation of the first answer from @Balint-H, in python code:

self.physics.named.model.eq_active[0] = 0

**Comment by yuvaltassa** [comment]
Should be `data.eq_active[]`. The attribute in model is `model.eq_active0[]`, i.e. the value of ``data.eq_active` upon load.

**Comment by Balint-H** [comment]
Could you provide a video of the two cases? The simplest issue I can imagine would be due to added collisions between the geoms of the two B bodies (previously they dont occur because they are on the same body, you can try disabling collisions between those geoms)

**Comment by TheMessik** [comment]
Nested:

https://github.com/google-deepmind/mujoco/assets/54912465/64533f6c-dd0f-44fa-9cef-26ad4914debb

Welded:

https://github.com/google-deepmind/mujoco/assets/54912465/fc691163-16ef-4130-a41c-6f58339c7114

Adding
```xml
    <contact>
        <exclude body1="B1" body2="B2"/>
    </contact>
```
seems to have no effect

**Comment by Balint-H** [comment]
Ah, it's clear now, B2 is missing a freejoint. It is unable to move in space therefore, and so is B1 (since it is welded)
