### ISSUE TITLE
I'm on Linux and I think I need to kill the MuJoCo process because it's freezing. How?

### ISSUE THREAD

**Issue by MotorCityCobra** [deepmind/mujoco#530]
Is there a way to kill the MuJoCo process by its PID in the Linux commandline? On Ubuntu.

**Comment by kevinzakka** [comment]
```bash
pidof simulate  # prints out PID
kill -9 PID
```

works for me

**Comment by kevinzakka** [comment]
Above is assuming you are trying to kill the simulate binary. Do you mean generally running a script that calls mujoco?
