### ISSUE TITLE
MJMODEL.txt not found

### ISSUE THREAD

**Issue by pab47** [deepmind/mujoco#539]
I am using mujoco222 on mac. After I load the xml by dropping in the simulate app and try to "print model" I am unable to locate the MJMODEL.TXT file. It used to be outputted in the Resources folder in the Mujoco app (v 2.2.0 and before) (Right click -> show in finder), but does not seem to be saving there anymore. I think there are similar issues with the other tabs like "Print data". 

Would it be possible to create the print model such that once clicked, the user is pointed where to save the MJMODEL.txt file? This functionality is in the "save xml" button but not in the print model or the print data button.

**Comment by kevinzakka** [comment]
Is this still an issue? FYI it's working fine for me on 2.2.3.

**Comment by pab47** [comment]
Hello Kevin, I updated to 2.3.0 on Mac. On loading the model in simulate app and pressing save xml does NOT generate the MJMODEL.txt anywhere on my computer (I did a search by date).

Are you using a mac too? If yes, where is the MJMODEL.txt generated for you?

**Comment by yuvaltassa** [comment]
You need to look inside the package. Right click on the simulate app and select "show package contents", it's in there somewhere, in the resources directory, IIRC.

We can and should fix this, thanks for the reminder. In the meantime find it there.
