### ISSUE TITLE
How to use the basic class mujoco.GLContext

### ISSUE THREAD

**Issue by KJaebye** [deepmind/mujoco#544]
I'm learning to use mujoco and trying to load and render a model.

I followed Rendering part of the MuJoCo official documentation. I tried to use class mujoco.GLContext to replace glfw, but I still need to use glfw lib functions like glfw.swap_buffers() and glfw.window_should_close() to control the video stream since there is no method in class GLContext to do so. GLContext is so short:

```
"""An OpenGL context created via GLFW."""

import glfw


class GLContext:
  """An OpenGL context created via GLFW."""

  def __init__(self, max_width, max_height):
    glfw.init()
    glfw.window_hint(glfw.VISIBLE, 0)
    self._context = glfw.create_window(width=max_width, height=max_height,
                                       title='Invisible window', monitor=None,
                                       share=None)

  def make_current(self):
    glfw.make_context_current(self._context)

  def free(self):
    if self._context:
      if glfw.get_current_context() == self._context:
        glfw.make_context_current(None)
      glfw.destroy_window(self._context)
      self._context = None

  def __del__(self):
    self.free()
```

My question is: If import glfw is indispensable, what is the meaning of class mujoco.GLContext?

**Comment by saran-t** [comment]
Sorry for the late reply. These `GLContext` classes are only intended for offscreen rendering.
