### ISSUE TITLE
How to simulate a constant speed conveyor belt?

### ISSUE THREAD

**Issue by joaopfg** [deepmind/mujoco#547]
Hi, I am a beginner in Mujoco. I'm using the C API and I want to simulate a constant speed conveyor belt. For this, a first model I want to try is a static box in the ground, with a force field applied in a particular direction in a rectangular parallelepiped just above it and a damping in the opposite direction so that I get the speed constant when the damping becomes equal to the force (like a free body falling through the air). What is the easiest way to simulate it using Mujoco's C API ? Any simpler idea to simulate a constant speed conveyor belt ?

Thanks in advance

**Comment by quagla** [comment]
Hi, do you actually want to model the belt or do you only care that the objects are moving? I believe with your suggestion you also want to remove friction so that objects are sliding on the ground or did I get your description incorrectly?

**Comment by joaopfg** [comment]
@quagla Hi, my final goal is to get something closer to a real belt. But since I'm a beginner with Mujoco and with this kind of modelling, I'm trying to be less ambitious for now and just get a simpler model in which the objects move. Yes, you are right, I also need to remove friction to get the constant speed in the model I mentioned.

**Comment by quagla** [comment]
You may want to play with this file to start with: 

https://github.com/deepmind/mujoco/blob/main/test/engine/testdata/activation.xml

Turn on Actuator and Activation in the Rendering panel to understand what is going on. Activation is coloring the actuator with the value of the internal state so it will give you an indication of when the body is about to accelerate after you increase an input with the sliders. You probably want something similar to the slider `site` but tangential to the face. You should be able to do all these changes in the XML.

**Comment by yuvaltassa** [comment]
What you are proposing is basically the right thing. Make a long box (possibly a series of adjacent boxes would be better for collision detection), give it a slider joint with large damping and add a general actuator. By doing something like
```xml
<actuator>
  <general joint="conveyor" gainprm="0" biasprm="x">
</actuator>
```
You will get an actuator that exerts a constant force `x`, but whose control signal does nothing (unless you want to control the conveyor speed, in which case don't zero out the gain).

One additional trick that might be useful, if you need you conveyor to run for a long time, you can manually (in code) make the slider value jump back to the beginning after it reaches some threshold. This will not affect the contacts (since you won't touch the velocity), so the sim will continue as if nothing happened. This will give you an "infinite" conveyor.

Feel free to post your test models here if something doesn't make sense.

**Comment by joaopfg** [comment]
Thanks for help. I'm having a hard time trying to understand the ideas. I will try to highlight the points which I'm not understanding.

So, if I understood, I can attach a joint to a body and, if the joint is of type slide, it restricts the movement of the body to the direction of a fixed vector in the space. 

Then, I can attach an actuator to the joint. The actuator has a length li(q) defined by the type of transmission and its parameters. **  What is the intuition behind naming li as length ?**

The gradient ∇li is an nv-dimensional vector of moment arms. **What does it mean ? Could you describe a bit more or point me to some learning resource, please ?**

The actuator is a function that receives an input ui (which I can control in the code), an activation state wi and outputs a force pi according to the formula pi = (a*wi or a*ui) + b0 + b1*li + b2*li(.). **What is the intuition behind the activation state ?** 

The force pi is mapped to joint coordinates by a vector of moment arms determined by the transmission. If I understand the mapping takes pi and ∇li and gives ∇li * pi , right ? **What is the intuition behind that ?**

I guess I'm missing some theory. I would appreciate if you can indicate me some learning resources to understand all this better .

**Comment by yuvaltassa** [comment]
> So, if I understood, I can attach a joint to a body and, if the joint is of type slide, it restricts the movement of the body to the direction of a fixed vector in the space.

Correct.

> Then, I can attach an actuator to the joint. The actuator has a length li(q) defined by the type of transmission and its parameters. * What is the intuition behind naming li as length ?

Correct. $l$ stands for "length" and $l_i$ means "the length of actuator $i$".

> The gradient ∇li is an nv-dimensional vector of moment arms. What does it mean ? Could you describe a bit more or point me to some learning resource, please ?

The moment arm matrix is the analytic Jacobian of the length vector. This is a  `nu x nv` [matrix](https://github.com/deepmind/mujoco/blob/f905c7fb7f8bad6dcfdb6e10d6f4fa4e1e61bd0b/include/mujoco/mjdata.h#L237) of which each row is the gradient $\frac{\partial l_i}{\partial q}$. 

> The actuator is a function that receives an input ui (which I can control in the code), an activation state wi and outputs a force pi according to the formula pi = (awi or aui) + b0 + b1li + b2li(.). What is the intuition behind the activation state ? Can you give me some intuition about why the formula is like this, please ?

The activation state is an **optional** internal state of the actuator. MuJoCo natively supports integrators and filters. You don't need this.

> The force pi is mapped to joint coordinates by a vector of moment arms determined by the transmission. If I understand the mapping takes pi and ∇li and gives ∇li * pi , right ? What is the intuition behind that ?

The moment arm matrix projects from forces in actuator space (`mjData.actuator_force`) to the joint space (`mjData.qfrc_actuator`).

> I guess I'm missing some theory. I would appreciate if you can indicate me some learning resources to understand all this better .

I recommend reading [`mj_fwdActuation`](https://github.com/deepmind/mujoco/blob/f905c7fb7f8bad6dcfdb6e10d6f4fa4e1e61bd0b/src/engine/engine_forward.c#L156).

**Comment by joaopfg** [comment]
@yuvaltassa Thanks. How is the actuator length calculated ?

I tried a proof concept based on what you said but can't get the conveyor moving. Is it because the length is set to zero by default and so the formula pi =  a * ui + b0 + b1 * li + b2 * li(.) gives zero ?

Here is the XML:

```
<mujoco>
    <compiler autolimits="true"/>
    <option density="1000"/>

    <worldbody>
        <geom type="plane" size="10 10 .1" rgba="1 1 1 1"/>
        <light pos="0 0 20"/>
        <body pos="0 0 1">
            <geom type="box" size="1 5 1"/>
            <joint name="conveyor" type="slide" pos="0 -10 0" axis="0 1 0" damping="1000"/>
        </body>
        <body pos="0 0 3">
            <geom type="box" size="1 1 1"/>
            <freejoint/>
        </body>
    </worldbody>

    <actuator>
        <general name="conveyor" joint="conveyor" gainprm="0" biasprm="10000"/>
    </actuator>
</mujoco>
```

If I set the `gainrpm` instead of `biasrpm`,  I can move the conveyor by passing a non-zero control input though. That's why I think the problem is in the actuator length.

**Comment by yuvaltassa** [comment]
My bad, you need to add `biastype="affine"`, the default is `none` so you bias gets ignored. See docs [here](https://mujoco.readthedocs.io/en/latest/XMLreference.html#actuator-general)

**Comment by joaopfg** [comment]
@yuvaltassa Thanks, what about the actuator length ? Is it calculated when the body moves with respect to the joint position ? I can't find this calculation in the source code. Can you point me to the method, please ?

**Comment by yuvaltassa** [comment]
Method is [here](https://github.com/deepmind/mujoco/blob/c7960385bec6bee443f459f7b1905e007d4ec993/src/engine/engine_core_smooth.c#L611).

`mjData.dof_damping[i] = x`
