### ISSUE TITLE
Is it possible to write a for loop to add bodies in the MJCF XML file ?

### ISSUE THREAD

**Issue by joaopfg** [deepmind/mujoco#553]
Hi, suppose I want to generate `n` consecutive boxes in the scene. Is there some mechanism to write a for loop in the MJCF XML file ?

**Comment by yuvaltassa** [comment]
The [composite](https://mujoco.readthedocs.io/en/latest/XMLreference.html#body-composite) tag does something like this, in particular look at the `particle` composite type.

Unfortunately I think it is quite limited as it currently only gives you 3 slider joints. @quagla, is there a way to make that free joints, in the current implementation?

**Comment by yuvaltassa** [comment]
So the commit solved this for adding an array of boxes, but we are thinking about a more general `<replicate>` element that will allow you to replicate anything along a grid (e.g. make multiple copies of robots). Will update here when that happens.

**Comment by joaopfg** [comment]
@yuvaltassa Thanks ! It would be good if the `<replicate>` also gives the possibility of not being limited by a grid. For example, if I want to add many robots around a circular conveyor belt. I am thinking in something similar to the `loop` element ones that some web frameworks use. For example, Angular's [ngFor](https://blog.angular-university.io/angular-2-ngfor/) .

**Comment by yuvaltassa** [comment]
What would you say to a choice of either grid of you can provide a mesh and <replicate> will use the vertices?

**Comment by yuvaltassa** [comment]
Now that I write it I see that even if we use the normals for "z-orientation of thing", we have an indeterminism w.r.t the xy axes. So maybe mesh to not the most general thing. But maybe this is not so bad?

**Comment by joaopfg** [comment]
@yuvaltassa I think just giving the possibility of parameterizing the loop is already very powerful.  For example, I could represent `n` robots around a circle of radius `r` in the xy plane with the following syntax:

```
<for begin="0" end="2*pi", step="(2*pi)/n">
    <body pos="r*cos(theta)  r*sin(theta)  0" quat="...">...<body/>
<for/>
```

What do you think ?

**Comment by yuvaltassa** [comment]
I think it would be easier to provide a Python code sample that makes this shape as a mesh 🙂

Basically if we're going to do something more general anyway, I'd rather avoid MJCF schema inflation if I can.

**Comment by joaopfg** [comment]
@yuvaltassa I see your point about MJCF schema inflation. Indeed, makes sense. I would be happy with meshes. I think a natural extension could be a set of unitary vectors and their corresponding origin points. Like this, one could fill an arbitrary volume with bodies in arbitrary orientations.

**Comment by Niels-Frederik** [comment]
I really like the idea of a `<replicate>` tag, even with just the option of a grid. Is this still in the pipeline?

**Comment by yuvaltassa** [comment]
@Niels-Frederik if you're happy with Python, you can use dm_control's [pyMJCF](https://github.com/deepmind/dm_control/blob/main/dm_control/mjcf/README.md).

**Comment by Niels-Frederik** [comment]
I have actually just switched to C++ due to the simulated environment being rather large, and performance being quite critical. Is the best approach then to just simply generate the XML string of the model dynamically through c++?
