### ISSUE TITLE
Programmatically defining an mjModel

### ISSUE THREAD

**Issue by marctuscher** [deepmind/mujoco#56]
Hi, 

is there any sample code how to programmatically define an mjModel: e.g. given a kinematic structure with geometric shapes (spheres, meshes, boxes, etc.), how to build the corresponding mjModel without translation into an XML file. 

Best
Marc

**Comment by yuvaltassa** [comment]
No, not at the moment.
After open sourcing you will be able to use the model compiler directly if you like, but we are still undecided if this API will be officially supported.
