### ISSUE TITLE
Is there an example script that saves a video of an episode to a video file?

### ISSUE THREAD

**Issue by MotorCityCobra** [deepmind/mujoco#562]
I've done some searching and don't see an example for the C++ MuJoCo.

**Comment by ThoenigAdrian** [comment]
https://github.com/deepmind/mujoco/blob/main/sample/record.cc
https://mujoco.readthedocs.io/en/latest/programming.html#sarecord

![image](https://user-images.githubusercontent.com/16619270/200100083-6cb5b79e-7ce2-47a5-bfeb-cdae1eff5924.png)
