### ISSUE TITLE
How to control actuator forces not in xml file

### ISSUE THREAD

**Issue by awef2** [deepmind/mujoco#563]
Hi,

I'm a student and I'm trying to use MuJoCo for a robot project.

I'm looking for some help with controlling actuator force.

Here is a model which explains my question:

```
model=<mujoco model="model">
    <asset>
        <texture name="grid" type="2d" builtin="checker" rgb1=".1 .2 .3" 
        rgb2=".2 .3 .4" width="300" height="300"/>
        <material name="grid" texture="grid" texrepeat="8 8" reflectance=".2"/>
    </asset>
    <worldbody>
        <light directional="true" cutoff="4" exponent="20" diffuse="1 1 1" specular="0 0 0" pos=".9 .3 2.5" dir="-.9 -.3 -2.5 "/>
        <camera name="closeup" pos="0 -0.1 0.08" xyaxes="1 0 0 0 1 3"/>
        <!-- ======= Ground ======= -->
        <geom size=".2 .2 .01" type="plane" material="grid"/>
        <body pos="0 0 .01">
            <freejoint/>   
            <geom name="a" type="sphere" pos="0 0 0" size=".005 .005" rgba="1 0 0 1"/>
            <site name="start" pos="0 0 0" size=".001"/>
        </body>
        <body pos="0 0 .06">
            <freejoint/>   
            <geom name="b" type="sphere" pos="0 0 0" size=".005 .005" rgba="1 0 0 1"/>
            <site name="end" pos="0 0 0" size=".001"/>
        </body>
    </worldbody>
    <tendon> 
        <spatial name="connect" limited="true" range="0.04999 0.05" width=".002" rgba="0 0 1 1">
            <site site="start"/>
            <site site="end"/>
        </spatial>    
    </tendon>
    <actuator>
        <position
        name="start_end" tendon="connect"
        ctrllimited="true" ctrlrange="0 0.0001"
        kp="0"/>
    </actuator>
</mujoco>
"""
```

And here is the model. 
![image](https://user-images.githubusercontent.com/115386003/200149264-fea5fa26-6503-4185-b4ea-f6836c475164.png)

I have an actuator "start_end" which tries to pull the balls together. 

I have my python code here: 
```
scene_option = mujoco.wrapper.core.MjvOption()
scene_option.flags[enums.mjtVisFlag.mjVIS_JOINT] = True

physics = mujoco.Physics.from_xml_string(model)
PIL.Image.fromarray(physics.render(camera_id='closeup'))


# Turn off gravity
physics.model.opt.gravity[0] = 0
physics.model.opt.gravity[1] = 0
physics.model.opt.gravity[2] = 0

duration = 1    # (seconds)
framerate = 50  # (Hz)

# Visualize the joint axis
scene_option = mujoco.wrapper.core.MjvOption()
scene_option.flags[enums.mjtVisFlag.mjVIS_JOINT] = True

# Simulate and display video.
frames = []

while physics.data.time < duration:
  physics.step()
  physics.named.data.actuator_force["start_end"] = 30
  physics.named.data.ctrl["start_end"] = 30
  if len(frames) < physics.data.time * framerate:
    pixels = physics.render(scene_option=scene_option, camera_id='closeup')
    frames.append(pixels)
    
display_video(frames, framerate)
```
And here is a colab link: [https://colab.research.google.com/drive/1xJzVOIZ3AQtosQ8jI_u5Cbm7Yjki0HcG?usp=sharinghttps://colab.research.google.com/drive/1xJzVOIZ3AQtosQ8jI_u5Cbm7Yjki0HcG?usp=sharing](url)

Currently, in the xml file, the kp of the actuator is 0. However, I have tried changing the kp in my python script with both the lines 
```
physics.named.data.actuator_force["start_end"] = 30
``` 
and 
```
physics.named.data.ctrl["start_end"] = 30
```
However, the actuator still does not move. How do I control the actuator without setting the kp value in the xml file?

**Comment by yuvaltassa** [comment]
`kp` is just the coefficient. If you want to set it programmatically (why would you want to do that?), you would change `mjModel.actuator_gainprm` and `mjModel.actuator_biasprm` as explained [here](https://mujoco.readthedocs.io/en/latest/XMLreference.html#actuator-position) and [here](https://mujoco.readthedocs.io/en/latest/computation.html#actuation-model).

If you want to set the control value programmatically you would set `MjData.ctrl`, but with `kp=0`, no force is output.

I think you have several misunderstanding which I cannot parse from your issue description. Try looking at our [LQR colab](https://colab.research.google.com/github/deepmind/mujoco/blob/main/python/LQR.ipynb), there is some actuation happening there.

We will soon add a basic MuJoCo tutorial that will hopefully help with these basic issues.
