### ISSUE TITLE
Reading names when importing model from URDF

### ISSUE THREAD

**Issue by zgawlowicz** [deepmind/mujoco#566]
Hi,
I'm using MuJoCo through Python binding and I have a problem with loading the existing URDF model.
What I've noticed in the code and behaviour is that when bodies are created, the names from URDF are assigned to them, but when single geom objects this is not happening, there is an explicit assignment of empty string here: [link](https://github.com/deepmind/mujoco/blob/main/src/xml/xml_urdf.cc#L439). This, in conjunction with the fact that everything connected with a fixed joint in URDF is treated as a single body makes it really hard to work with specifying contact pairs and so on, because I have a body that consists of 40 geoms and I don't have their respective names, so can't specify contact between selected parts of the body and another moving part.
Is this something that was overlooked / is a bug in the URDF parser or is it done intentionally?
I can create a minimal URDF xml in case you need to reproduce it, but if it's done by design then it probably won't be needed.

Thank you in advance for help.

**Comment by yuvaltassa** [comment]
I think this is an oversight, I can't see why it would be done intentionally.

If you create a minimal URDF we can take a closer look, or you can just submit a PR, if it is obvious to you how to fix this.

Cheers
