### ISSUE TITLE
The legacy mujoco forum cannot register an account

### ISSUE THREAD

**Issue by 2371745431** [deepmind/mujoco#571]
I want to download files on the legacy mujoco forum. Therefore, I need to sign up for an account. But I only see the login interface, and did not find the registration interface.

**Comment by yuvaltassa** [comment]
File downloads should still work.

Which files specifically are you trying to download?

**Comment by 2371745431** [comment]
> 文件下载应该仍然有效。
> 
> 您具体要下载哪些文件？
Sorry, I still can't download the file. Click to download the file still prompted to login or register. Here is the link of the file I want to download:
https://roboti.us/forum/index.php?threads/6-bar-tensegrity-robot-model-optimization.3773/
https://roboti.us/forum/index.php?threads/modeling-of-highly-stiff-yet-elastic-structures.3822/#post-4988
https://roboti.us/forum/index.php?threads/nested-body-and-joint-type-for-tensegrity.3547/#post-4327

**Comment by 2371745431** [comment]
> File downloads should still work.
> 
> Which files specifically are you trying to download?
Is mujoco not support the modeling of parallel mechanisms? Suppose I want to create a triangle mechanism. The link should be named base_link-link1-link2 in sequence. How can I complete the closed chain and build the joint between link2 and base_link?

**Comment by 2371745431** [comment]
> File downloads should still work.
> 
> Which files specifically are you trying to download?

Sorry, I still can't download the file. Click to download the file still prompted to login or register. Here is the link of the file I want to download:
https://roboti.us/forum/index.php?threads/6-bar-tensegrity-robot-model-optimization.3773/
https://roboti.us/forum/index.php?threads/modeling-of-highly-stiff-yet-elastic-structures.3822/#post-4988
https://roboti.us/forum/index.php?threads/nested-body-and-joint-type-for-tensegrity.3547/#post-4327

**Comment by 2371745431** [comment]
> File downloads should still work.
> 
> Which files specifically are you trying to download?

Is mujoco not support the modeling of parallel mechanisms? Suppose I want to create a triangle mechanism. The link should be named base_link-link1-link2 in sequence. How can I complete the closed chain and build the joint between link2 and base_link?

**Comment by yuvaltassa** [comment]
Try downloading the files now.

**Comment by yuvaltassa** [comment]
Parallel mechanisms are supported. Look for example at the [Robotiq gripper](https://mujoco.readthedocs.io/en/latest/models.html#grippers-hands)

**Comment by 2371745431** [comment]
> 
Sorry, the file still cannot be downloaded. After clicking the file, the system prompts to register or log in.

**Comment by 2371745431** [comment]
> Try downloading the files now.

![image](https://user-images.githubusercontent.com/93893027/202846630-757d7575-0c67-49c5-8a4e-41de099bd0bf.png)

**Comment by yuvaltassa** [comment]
Try again?
Should be okay now, I hope 🤞

**Comment by yuvaltassa** [comment]
Links appear to work. Closing.

**Comment by 2371745431** [comment]
> 



> Links appear to work. Closing.
Thanks for replying ! I can download files on the forum now. Thanks!
