### ISSUE TITLE
Ground Reaction Force and ZMP

### ISSUE THREAD

**Issue by kpydv** [deepmind/mujoco#579]
Hi 
![biped](https://user-images.githubusercontent.com/48467350/201289590-4fa59cd8-fbb6-40a9-bd0c-9bc21ac6e459.png)

Three joint torques and one external force at the hip are used in this planar biped.
I'd like to compute the ZMP and ground reaction forces.
Could you please assist me?

**Comment by yuvaltassa** [comment]
Are you using Python or C?

Iterate over the `mjData.contact` array to read contact positions and [`mj_contactFroce`](https://mujoco.readthedocs.io/en/latest/APIreference.html#mj-contactforce) to read the contact forces.

**Comment by kpydv** [comment]
@yuvaltassa  Thanks for your response,
I am using mujoco-py 

> Are you using Python or C?
