### ISSUE TITLE
No module named mujoco.simulate

### ISSUE THREAD

**Issue by UTINK** [deepmind/mujoco#580]
Hi,

I'm beginner to use MuJoCo.  I followed the official doc and installed the mujoco with python bindings in my conda virtual env.
I want to  launch the GUI and executed "python -m mujoco.simulate" in terminal or applied  "from mujoco import simulate" in Pycharm, 
but showed error "No module named mujoco.simulate" or "ImportError: cannot import name 'simulate' from 'mujoco' (D:\anaconda3\envs\gym\lib\site-packages\mujoco\__init__.py)".

![image](https://user-images.githubusercontent.com/56284816/201655280-5b76da13-7e86-47a2-820c-ae7a0ad942f1.png)

![image](https://user-images.githubusercontent.com/56284816/201654502-7a014b26-275b-4614-81d4-957529259d8d.png)

**Comment by yuvaltassa** [comment]
Not yet available, see #576.
