### ISSUE TITLE
Is Mujoco a strict Markov Decision Process ?

### ISSUE THREAD

**Issue by Tony-chenjw** [deepmind/mujoco#582]
Hi,

I'm new to mujoco environment and I'm doing experiments on mujoco (specifically, on Hopper-v3 environment). I use Python and access mujoco/mujoco-py through [gym](https://www.gymlibrary.dev/environments/mujoco/) lib. 

Now I'm confused that is Mujoco a Fully Observable Markov Decision Process? Since I once looked up the source code and found there are actually many hidden variables maitained by mujoco in [**mjData**](https://mujoco.readthedocs.io/en/latest/APIreference.html#mjdata). I suppose that these hidden variables, like **qacc_smooth**, **qM** and etc., would affect the state transition? If that is true, then I would consider Mujoco environment as Partially Observable MDP. Thus, another point to my confusion is that: Would different hidden variables result in different state transitions(next_obs) even though their obs are the same?

Any suggestion on my confusion? Thanks in advance !

**Comment by erez-tom** [comment]
MuJoCo's computation is deterministic.  See https://mujoco.readthedocs.io/en/latest/computation.html?highlight=deterministic#the-state
Depending on which sensors/observations you make available to your agent, your specific scenario is either fully-observable or not; and depending on your initialization procedure (and perhaps injected noise), the specific environment is either deterministic or not.  I'm not familiar with Hopper-v3 nor mujoco-py, so I can't comment on those specific cases.
