### ISSUE TITLE
Collapsible subsections in right TOC sidebar in Docs

### ISSUE THREAD

**Issue by vaxenburg** [deepmind/mujoco#586]
**Is your feature request related to a problem? Please describe.**

The right TOC sidebar in the new docs theme is far too long and not useful, especially in long reference sections such as [API Reference](https://mujoco.readthedocs.io/en/latest/APIreference.html#). A lot of scrolling is required to reach the destination and it's also hard to find in the long list now. It makes using the TOC to navigate efficiently through the long reference sections almost impossible.

**Describe the solution you'd like**

Please consider making sublevel elements collapsible, and collapsed by default. The previous docs theme worked perfectly fine -- upon opening everything was collapsed and the TOC showed only the first level elements. It was very easy to navigate. In the same API Reference section, the first level of elements looked like this, and you could reach your desired section in a couple of clicks:

<img width="284" alt="image (4)" src="https://user-images.githubusercontent.com/46580141/202315480-f86c7924-b151-4483-b75b-3a5e223c62c3.png">

**Comment by kevinzakka** [comment]
Looking into this, thanks for flagging @vaxenburg!

**Comment by vaxenburg** [comment]
Any update on this, by any chance?

**Comment by kevinzakka** [comment]
Hi @vaxenburg, the docs are slowly being broken up to alleviate this issue (e.g., 090c25988ae2d4df2525ab9ef93658824ffe6b86).

**Comment by yuvaltassa** [comment]
Closing for now.

**Comment by vaxenburg** [comment]
Sounds good, thanks @kevinzakka !
