### ISSUE TITLE
Why when I insert an object very big in the scene, my fixed camera also becomes very big ?

### ISSUE THREAD

**Issue by joaopfg** [deepmind/mujoco#588]
Hi, quick question probably easy to solve but I can't find the right parameter to adjust.

In my simulation, I am simulating a conveyor belt as a box with a very big y dimension (like `size=".1 300 .1"`) with a slide joint (as per the discussion [here](https://github.com/deepmind/mujoco/issues/547)). But all the other things in the scene are much smaller (like `size=".1 .1 .1"`). 

If I add fixed cameras in the world body (like `<camera name="camera1" pos="-.75 -1.5 1" axisangle="1 0 0 1.5708"/>`) and I try to render it, it's very big. But if I remove the conveyor belt, it gets to a good size compared to the objects in the scene. I guess the compiler tries to scale the dimensions of the fixed cameras to the size of the biggest dimension in the scene. How to avoid that ?

**Comment by kevinzakka** [comment]
Read about extent [here](https://mujoco.readthedocs.io/en/latest/XMLreference.html?highlight=extent#statistic).
