### ISSUE TITLE
How to check if there is no body in a certain region of the space ?

### ISSUE THREAD

**Issue by joaopfg** [deepmind/mujoco#594]
Hi, 

in one of the control callbacks of my simulation I need to implement a logic to check if there is no body in a certain region of the space (let's say, in a cube of the space). Is there some way to do this kind of check in MuJoCo ?

Thanks in advance

**Comment by kevinzakka** [comment]
Pointing you to [relevant code](https://github.com/deepmind/dm_control/blob/e3d4c0aecfd710cd7428eb77af203dc5fbdacc0f/dm_control/entities/props/position_detector.py#L42) in dm_control.

**Comment by joaopfg** [comment]
@kevinzakka Hey, thanks for pointing out. But I am using the C API. Is there some way to do it in the C API ?
