### ISSUE TITLE
About Semantic Segmentation

### ISSUE THREAD

**Issue by Lucky-hqj** [deepmind/mujoco#595]
Hi, I'm a novice using mujoco. How to use Python Bindings to obtain semantic map?

**Comment by yuvaltassa** [comment]
What is a semantic map?

**Comment by Lucky-hqj** [comment]
> What is a semantic map?


Sorry, there is something wrong with my statement. I mean, image semantic segmentation.

**Comment by yuvaltassa** [comment]
We will shortly (likely next week) make a colab available with an example of this functionality. 
I will leave this issue open until this happens.
Cheers

**Comment by Lucky-hqj** [comment]
> We will shortly (likely next week) make a colab available with an example of this functionality. I will leave this issue open until this happens. Cheers

OK.I'm looking forward to it.Thank you very much for your contribution.

**Comment by kbayes** [comment]
The colab is now online (located in the Python subdir, or find the link in the README).  See the advanced graphics section for segmentation.  Let us know if anything is unclear or missing, so we can improve it for other users.
