### ISSUE TITLE
How to get the total mass of a box with many bodies inside ?

### ISSUE THREAD

**Issue by joaopfg** [deepmind/mujoco#610]
Hi,

in my simulation I have a rectangular box in which I can put many bodies inside. Some bodies can be entirely covered by others inside the box. I want to create a custom sensor that can estimate the total mass of the box. 

So far, I have an algorithm that plays with `mj_ray` method and the arrays `geom_bodyid` and `body_mass`. Basically, it fires some rays into the box and sum the masses of the different bodies that the rays can catch. But it misses some bodies (when they are totally covered inside the box), so it does not serve my purpose.

Any idea on how to do this ?

Thanks in advance

**Comment by Balint-H** [comment]
User here, do you see the naive approach iterating through all eligible geoms and checking their CoM position to be unsuitable?
