### ISSUE TITLE
[Basic Question] "data.qvel[0] = XX" is an appropriate way to specify objects' rotation velocity?

### ISSUE THREAD

**Issue by miyukin73** [deepmind/mujoco#614]
Hello, 

I want to rotate a cup like bellow.

https://user-images.githubusercontent.com/63595993/204808939-4ca9ac88-c6e3-4068-8e44-d6c73160d69e.mp4

When I do the above, I wrote as follows:

```
model = mujoco.MjModel.from_xml_path(target_img_path)
data = mujoco.MjData(model)
data.qvel[0] = 10
```

Is this an appropriate way to specify rotational speed by `data.qvel[0] = XX` ?

Sorry for the basic question, but thank you in advance.

**Comment by Balint-H** [comment]
That will set the velocity once, but it will change if you don't set it every frame. For something like this, also consider using a [mocap body](https://mujoco.readthedocs.io/en/stable/modeling.html?highlight=motion%20capture#mocap-bodies) to define its rotation every frame.

**Comment by miyukin73** [comment]
I got it.

Thank you so much for your help!
