### ISSUE TITLE
I would be interested to know more about the modeling strategy of the rope(tendon) within Mujuco

### ISSUE THREAD

**Issue by WhiteFireFox** [deepmind/mujoco#617]
Hi,

I'm a student and I'm trying to use MuJoCo for modeling the rope which is used in my robot.

I'm looking for some help with the modeling strategy of the rope(tendon) within Mujuco. Could you give me a brief introduction to its modeling strategy in this issue? Besides, are there any related papers that can be recommended to me?

Thank you for your kind help!

**Comment by yuvaltassa** [comment]
Your question is not very specific, I'm not sure how to help you.
You can examine [this model](https://github.com/deepmind/mujoco/tree/main/test/engine/testdata/catenary.xml) and [this model](https://github.com/deepmind/mujoco/tree/main/test/engine/testdata/tendon_springlength.xml), note that the lengthspring feature is not yet in an official release, this will likely happen next week.
