### ISSUE TITLE
How to get distance between two geoms before collision for collision avoidance

### ISSUE THREAD

**Issue by st168992** [deepmind/mujoco#635]
Hi,

I'm a student and I'm trying to use MuJoCo for **collision prevention/avoidance**.

What I need accordingly, is the shortest distance at any given time between geom1 and geom2. This info would then be used to tell the system to stop the movement before actual contact happens.

I originally thought I could get the relevant data from d->contact[].dist but as far as I understand mjContact only stores data when a collision already happens, meaning only negative values get saved in d->contact[].dist due to penetration. Is this correct? 

A workaround that comes to mind would be using sensordata by attaching sites to the relevant geoms. This workaround however wouldn't have the precision I'm looking for.

Any help is appreciated!

**Comment by kevinzakka** [comment]
Out of curiosity, why does the distance between two geom sites not have the precision you need? What do you mean by precision in this case?

**Comment by saran-t** [comment]
@st168992 it sounds like all you really need is for inactive contacts to be detected within a certain distance of actual contacts, rather than being able to query closest distance between arbitrary geoms.

The `gap` and `margin` attributes of the `<geom>` element (see [here](https://mujoco.readthedocs.io/en/stable/XMLreference.html#body-geom)) is exactly what you want for this.

**Comment by st168992** [comment]
> Out of curiosity, why does the distance between two geom sites not have the precision you need? What do you mean by precision in this case?

What I mean by precision is that I'd have a hard time recreating the meshes from my build with the available geom-types for sites. The consequence would be a lack of precision in collision-detection when compared to the real system (which obviously isn't approximated by sites). I know it's a bit nitpicky though lol.

**Comment by st168992** [comment]
@saran-t & @yuvaltassa Thanks, that looks promising!
 I will test it in the coming week and get back at you.

**Comment by st168992** [comment]
@saran-t @yuvaltassa so I just tried it and... it works! Thanks.

One additional question though: 

I am printing ncon additionally which is described as _number of detected contacts._
Is it correct that detected contacts means active as well as inactive contacts? 
Consequentially, if I set a value as margin, ncon will be 1 as soon as I'm within the margin, correct?

**Comment by yuvaltassa** [comment]
Yes.

**Comment by yuvaltassa** [comment]
Positive margin M means "inflate the geom by M". If you only have margin then contacts will be detected and force will be created to resolve the collision.

Positive gap G means "start computing forces only after the penetration is larger than G".

So if you want contacts to be detected, but forces not created, you need both margin and gap.

**Comment by yuvaltassa** [comment]
I recommend making a simple pedagogical model to play with these values and understand them.

If you make something nice, we can include it in the documentation 🙂

**Comment by yuvaltassa** [comment]
Almost. The gap should be on the outside, _taking away_ from the margin. If I have a geom with margin 1.5 and gap 0.5, contacts will be detected at distance 1.5, but contact forces will be generated at distance 1.0

Makes sense?

**Comment by hubernikus** [comment]
From the documentation, it seems that the `gap`-paremeters is measured from the outside, hence it should be the orange-region in the above drawing. 

Or am I missing something?
