### ISSUE TITLE
Question about 【composite type="particle】

### ISSUE THREAD

**Issue by miyukin73** [deepmind/mujoco#642]
Hello.

I would like to use `composite type="particle"` to display multiple spheres in a simulation environment.

If I use "particle", I would consider all the spheres as an aggregate and define the xml file as follows for example
```
<mujoco model="mug with balls">
  <worldbody>
    <composite type="particle" count="5 5 5" spacing="0.011" offset=".005 .003 .15">
      <geom size=".005" rgba=".8 .2 .1 1" solref=".005 1"/>
    </composite>
  </worldbody>
</mujoco>
```

My question is, 
if I use composite type="particle", can I specify the position of each individual sphere?

Also, I think the joints of the spheres are only SLIDE and not rotated.

Is it possible to set the joints?

[Screencast from 2022年12月10日 18時56分06秒.webm](https://user-images.githubusercontent.com/63595993/206848408-f1eba941-e6a8-46ef-ae20-9902ac551e5a.webm)

Thank you in advance.

**Comment by quagla** [comment]
Hi @miyukin73,

It is unfortunately not possible at the moment to set the position of each individual particles. A possible workaround would be to load the model you proposed, then save it from MuJoCo and edit the positions by hand. When you save it, you will see that the composite is expanded into each individual particle. Does that make sense?

Yes it's possible to set the joints, see https://github.com/deepmind/mujoco/blob/main/model/composite/particle_free.xml and  https://github.com/deepmind/mujoco/blob/main/model/composite/particle_free2d.xml
