### ISSUE TITLE
Importing Mujoco Menagerie Robotiq Gripper causes Unity error (`required attribute missing: 'anchor'`)

### ISSUE THREAD

**Issue by james-giammona** [deepmind/mujoco#647]
Hi,

I'm a research engineer at a humanoid robotics company and I'm trying to use the MuJoCo Unity plug-in to dynamically simulate opening and closing the Robotiq gripper from the Mujoco Menagerie in Unity.

When trying to import and run the MJCF for the Robotiq 85mm 2-Finger Adaptive Gripper from the [Mujoco Menagerie](https://github.com/deepmind/mujoco_menagerie/tree/main/robotiq_2f85), I've run into a `Failed to creat Mujoco runtime` error caused by a `XML Error: required attribute missing: 'anchor'`. However, the `2f85.xml` file does contain anchors.

When importing this file using `Assets->Import MuJoCo Scene`, there were some interesting messages that may be relevant:
```
"anchor in connect connect_45 ignored. Set Transforms in the editor."
"anchor in connect connect_46 ignored. Set Transforms in the editor."
```

I have made [a repository](https://github.com/james-giammona/mujoco-unity-error-repro) to reproduce the error I encountered. Please let me know if there are any errors getting this reproduction to succeed.

Best,
James

Tagging @ericjang for visibility

**Comment by erez-tom** [comment]
I believe I know what's going wrong, and I hope to push a fix later today or tomorrow.  Meanwhile, you can can hard-code something like `mjcf.SetAttribute("anchor", "0 0 0");` in the function `MjConnect.ToMjcf`.  If that doesn't get you unstuck, please let me know.

**Comment by Balint-H** [comment]
I'm not sure about the Unity version of the `connect` constraint, but at least for `weld`s you have to provide a Unity transform to the serialized 
`offset` property in the inspector when the corresponding GameObject is selected. Is there an availabile slot when you sellect the connect GameObject? It should read `None`, you can create and position a transform with the appropriate values to assign there.

**Comment by erez-tom** [comment]
Right -- that's how @Balint-H and I fixed it for the weld, but forgot to also address the connect constraint.  In my tentative fix I added a Transform property to define the anchor, but I'm having hard time testing it because the the Robotiq model's meshes are too big...  @james-giammona : Did you simplify the meshes in your minimal repro?
