### ISSUE TITLE
Robotiq Gripper closing behavior is incorrect in Unity+MuJoCo

### ISSUE THREAD

**Issue by james-giammona** [deepmind/mujoco#654]
Hi,

I'm a research engineer at a humanoid robotics company and I'm trying to use the MuJoCo Unity plug-in to dynamically simulate opening and closing the Robotiq gripper from the Mujoco Menagerie in Unity. [I previously reported an error](https://github.com/deepmind/mujoco/issues/647) I ran into that I was able to work past with the suggested hard-coded fix.

I'm now able to simulate the opening and closing behavior in both Unity (using MuJoCo) and with stand-alone MuJoCo. Unfortunately, the Unity simulation is not closing properly when actuated (and seems to start in an overextended state initially).

I've attached a video recording of the gripper actuation in Unity and in MuJoCo for comparison. Both of these are using the same `2f85.xml` file from my [minimal repo](https://github.com/james-giammona/mujoco-unity-error-repro) which has sub-sampled meshes for some of the gripper parts.

While poking around, I noticed that Unity and MuJoCo had different behavior when I deleted all equality constraints, unless I also turned off the Limits flag in the MuJoCo simulation and then the behavior of both was much closer (with the outer arm bars hanging fully down and oscillating continuously) so my guess is that the limits may not be being set properly in Unity during initialization?

Please let me know if you'd like any other information or further videos.

MuJoCo video:

https://user-images.githubusercontent.com/120140073/207705455-1250b791-ce36-430b-af31-7292dd01b499.mp4

Unity video:

https://user-images.githubusercontent.com/120140073/207705506-ae97acd2-54ca-4a63-a2c8-db1bfe79d7e4.mp4

**Comment by Balint-H** [comment]
I think this could be related to #512, as whether a joint limit is enabled does not seem to be imported, which could explain why behaviour matches when disabling limits in the standalone. You could try manually toggling the limits on in the Unity Editor!

**Comment by Balint-H** [comment]
Took a bit of tracking down, but found what was causing the pose issue! It looks like `springref` attribute is not converted to degrees on import, resulting in insufficient torque from them. For now you can multiply the `Equilibrium Pose` by 57.29578 manually for both spring joints (setting it to slightly more than 150 degrees). 

Thanks for finding this! I'll send a PR fixing it.

**Comment by Balint-H** [comment]
Interesting I don't get this behaviour, could you try reimporting the scene (and updating the joint limits, actuator limits, and spring reference)?
