### ISSUE TITLE
How to reproduce bimanual cable insertion task uploaded to Youtube

### ISSUE THREAD

**Issue by keiohta** [deepmind/mujoco#669]
Hi,

I'm an engineer trying to use MuJoCo for cable manipulation.

I'm looking for some help reproducing the simulation of the bimanual cable insertion task uploaded to https://www.youtube.com/watch?v=4J4tO8bb70I.
Would it be possible to share the source codes or the XML file of this simulation?

**Comment by quagla** [comment]
Hi, unfortunately that environment is not open sourced at the moment. I would suggest to look into https://github.com/ARISE-Initiative/robosuite and see if you can find something similar.
