### ISSUE TITLE
Help installing MuJoCo on FPGA

### ISSUE THREAD

**Issue by alvinli6** [deepmind/mujoco#670]
Hi,

I'm a student researcher and I'm looking for some help installing MuJoCo on an FPGA.

Here is a screenshot of the error I'm getting when I run pip install mujoco:

![image](https://user-images.githubusercontent.com/82617252/209254930-5ce4ee77-3849-4936-bd77-374bec43de2b.png)

Does anyone have any idea how to fix this? Thank you so much in advance! I'm pretty new to interacting with the GitHub community, I apologize if I posted this in the wrong place.

**Comment by saran-t** [comment]
Can you please give us more detail on exactly what platform you're trying to build for?

**Comment by alvinli6** [comment]
@saran-t Hello, thanks for getting back to me! I’m trying to install on the PYNQ-Z2 board.

**Comment by saran-t** [comment]
I know very little about FPGAs, however I'd be very surprised if you can get MuJoCo to run on the board...

If nothing else, the MuJoCo Python package is just bindings into C code, there's very little actual Python code. Having said that, if you want to try it, please consult [our documentation](https://mujoco.readthedocs.io/en/latest/python.html#building-from-source) for instructions on how to build from source.

**Comment by yuvaltassa** [comment]
Also, while the bindings have some fairly modern C++, the MuJoCo engine itself is pure ANSI C and will compile on anything, including FPGA. If you decide you can do without Python, we can help you compile MuJoCo itself.

**Comment by kevinzakka** [comment]
Closing for now, @alvinli6 feel free to re-open if you run into newer issues.
