### ISSUE TITLE
Is there any way to create a composite model from import obj/stl file?

### ISSUE THREAD

**Issue by KunZHANG1994** [deepmind/mujoco#674]
I would like to import an existing obj file as soft model.
I have tried the composite model, but not work. 
I would like to know is there any way to create a composite model from import .obj/.stl file?
Does current version of Mujoco support to import a existing obj file as soft model?

**Comment by quagla** [comment]
Hi, that's not supported yet. Is your aim to have a 3d soft body (i.e. tetrahedral mesh) or a surface (like a cloth)?

**Comment by KunZHANG1994** [comment]
> Hi, that's not supported yet. Is your aim to have a 3d soft body (i.e. tetrahedral mesh) or a surface (like a cloth)?

Hi, thanks for your reply. I would like to simulate a 3D space closed surface, not a single piece of cloth. I have made a mesh file of cloth from blender. Is that possible? or Mujoco will further support?

**Comment by quagla** [comment]
Yes it will be possible in the next release but with the caveat that the equilibrium configuration for the bending stiffness will be assumed to be the flat configuration (an angle pi across triangles). For a closed surface probably it won't matter that much because you could try setting the bending stiffness to zero since the deformations are dominated by stretching.

**Comment by KunZHANG1994** [comment]
> 
Cool, very exciting news. By the way, when will be the next release available?

**Comment by quagla** [comment]
Probably in a couple of weeks, but if you build from source you might be able to access the new feature earlier.

**Comment by KunZHANG1994** [comment]
OK！ Thanks！

**Comment by quagla** [comment]
We just made a new release but unfortunately the feature you requested did not make the deadline. You should keep an eye for it in the next month. I hope this does not change your plans in using MuJoCo.

**Comment by KunZHANG1994** [comment]
> @KunZHANG1994 We just made a new release but unfortunately the feature you requested did not make the deadline. You should keep an eye for it in the next month. I hope this does not change your plans in using MuJoCo.

OK, Thx for telling me these. I changed my working schedule and waiting your new feature update.

**Comment by Shamp0o** [comment]
Is this supported, yet? Couldn't find anything related to this in the elease notes of 2.3.3 and neither could I find a pull request.

**Comment by quagla** [comment]
We are working on a larger feature that will include this, so I'm afraid it has been delayed. Apologies for this.

**Comment by dblanm** [comment]
@quagla  any update on when will this be released?

**Comment by quagla** [comment]
Unfortunately it won't be part of the next release. I've had this code ready for a while but unfortunately it's pending on a `composite` refactoring that has been delayed.

**Comment by quagla** [comment]
Hi @dblanm and @KunZHANG1994 happy to let you know that this is now supported! Let me know if it works as you expected.
