### ISSUE TITLE
Adaptive dead zone for actuated tension-only tendons

### ISSUE THREAD

**Issue by wangsd01** [deepmind/mujoco#694]
Recently the springlength parameter help to build a dead zone for tension-only tendons, as requested in the following issue.
https://github.com/deepmind/mujoco/issues/520

I was wondering if I can add an actuator to the tendon to retract/release the cable,  the dead zone would adapt to the length change? If so, which actuator should I use in this case? Thanks!

**Comment by yuvaltassa** [comment]
If you connect an actuator to this tendon, do you get the desired behaviour?
If not, what behavior are you expecting?
Please reply with a loadable model, otherwise your request is difficult to parse.
```xml
<actuator>
  <position tendon="my_tendon"/>
</actuator>
```

**Comment by yuvaltassa** [comment]
Closing.
