### ISSUE TITLE
Mujoco act different according to the 'group' attribute in xml.

### ISSUE THREAD

**Issue by friedmainfunction** [deepmind/mujoco#702]
**How to ask for help**

Hi,

I'm a (student) and I'm trying to use MuJoCo for physical simulation.

I'm looking for help with Mujoco acting differently according to the 'group' attribute in xml.

Here is a model which explains my question:

<details>
  <summary>

</summary>

```XML
<mujoco model="test">
  <worldbody>
    <geom name="floor" size="35 35 0.1" type="plane" condim="6"  rgba="1 0.5 0.5 1"/>
    <light pos="0 0 0.5" dir="0 0 -1" directional="true" castshadow="false" cutoff="100" exponent="1" diffuse="1 1 1" specular="0 0 0"/>
    <body name="a" pos="-0.341536 0.286591 0.9" quat="-0.275254 0 0 0.961371">
      <freejoint name="a"></freejoint>
      <geom name="a" size="0.2 0.4" type="cylinder" group="1" density="0.001"/>
    </body>
  </worldbody>
</mujoco>
```

</details>

Here is a screenshot / video, illustrating my question:
When I set the 'group' attribute in geom 'a' to a number that is less than six, It works:
![image](https://user-images.githubusercontent.com/73703265/213642433-187ee02f-630c-486d-a60d-1193325f1a05.png)

When I set it to a number greater than or equal to six, Mujoco raises an error:
![image](https://user-images.githubusercontent.com/73703265/213642537-0d6bafcd-4377-4f01-bbdd-ee00b2033ee3.png)
My platform is Ubuntu 20.04 and my Mujoco version is 2.3.0.
I believe If users can define this value in a wider range, it will be much easier to do secondary development.
But I am not sure if it is a bug, so I try to propose my question here, it would be appreciated if you can provide any help, thanks!

**Comment by yuvaltassa** [comment]
Search the docs for `inertiagrouprange`
