### ISSUE TITLE
Reasoning for sim.busywait in simulate/main.cc

### ISSUE THREAD

**Issue by rohit-kumar-j** [deepmind/mujoco#704]
I would be grateful if someone could kindly explain the reason for the reasoning behind `sim.busywait` in [simulate/main.cc](https://github.com/deepmind/mujoco/blob/d7844aa5bea1f3cb3c1d0a576d42d61cf4b828cb/simulate/main.cc#L308). 😅

**Comment by yuvaltassa** [comment]
1. Load a model.
2. Hit F3 to see the built in profiler.
3. Turn `busywait` on/off to see how it affects timing values (on gives more accurate, lower variance readings).
4. Open your favourite whole-system profiler, see how `busywait` affects simulate's CPU usage (on increases it, decreases battery life).
