### ISSUE TITLE
Change position and/or spawn objects at runtime in Python

### ISSUE THREAD

**Issue by cowolff** [deepmind/mujoco#708]
Hi,

I'm a student and I'm trying to use MuJoCo for a study project at my university with Reinforcement Learning.

I'm looking for some help with spawning objects and moving objects at runtime in Python.

In general, I am just wondering if it is possible to simply change the position in Python of an object or geom by overwriting the position variable of the geom inside the mjData or mjModel class at runtime?
Additionally, I wonder if it is possible to spawn or duplicate an existing object at runtime? If yes for either of those, I would be very happy if you could provide some help.

I went through different issue threads and forum posts for hours by now, but couldn't find anything. Even if it is not possible at all, I would very much appreciate having an answer to this.

**Comment by yuvaltassa** [comment]
@aravindsiv is correct, you need to recompile the model.

As a medium term solution you can use dm_control's pyMJCF to modify your model in Python and recompile it as needed.

In the long term, we intend to make model recompilation much faster and accessible from C++.
