### ISSUE TITLE
Out of date documentation of `mjd_transitionFD`

### ISSUE THREAD

**Issue by lieskjur** [deepmind/mujoco#713]
Hi, The [2.2.2 changelog](https://mujoco.readthedocs.io/en/2.3.1/changelog.html#version-2-2-2-september-7-2022) contains: "Added sensor matrices to `mjd_transitionFD` (note this is an API change)." which only partially fits the [API reference](https://mujoco.readthedocs.io/en/2.3.1/APIreference.html#mjd-transitionfd). Do I assume correctly that the reference should read something like
"
Finite differenced state-transition and control-transition matrices dx(t+h) = A*dx(t) + B*du(t) as well as state-sensor and control-sensor matrices dy(t) = C*dx(t) + D*du(t). Required output matrix dimensions: A: (2*nv+na x 2*nv+na), B: (2*nv+na x nu), C: (nsensordata x 2*nv+na), B: (nsensordata x nu).
"
? If so this should most likely be also reflected in [Computation](https://mujoco.readthedocs.io/en/2.3.1/computation.html#derivatives).

**Comment by yuvaltassa** [comment]
Yes, thanks for this.
