### ISSUE TITLE
Post-simulation differentiation

### ISSUE THREAD

**Issue by lieskjur** [deepmind/mujoco#715]
Hi, in my code I first run a simulation using forward dynamics creating a series of discrete states with `mj_step`. At a later time, I would like to use `mjd_transitionFD` to calculate A, B, C and D matrices for each state (+controls) of the generated trajectory.

In [Programming -> State and Control](https://mujoco.readthedocs.io/en/2.3.1/programming.html?highlight=multi-threading#state-and-control) it is written that the system's state is `x = (mjData.time, mjData.qpos, mjData.qvel, mjData.act)` and user inputs are `u = (mjData.ctrl, mjData.qfrc_applied, mjData.xfrc_applied)`. There is also a mention of `mocap_pos`, `mocap_quat` and `userdata` but I don't think I need to concern myself with those at the moment.

Would saving, and at a later time copying components of `x` and `u` to `mjData`, calling `mj_forward` and then `mjd_transitionFD` yield the same (correct) results as if I were to call `mjd_transitionFD` at each step during the simulation? Also, should I save and copy `qacc_warmstart` to improve performance in this case as well? And lastly, is this approach likely to outperform filling an array of `mjData` with `mj_copyData` and calling `mjd_transitionFD` on each element?

---

On a slight tangent, if I do not define `mjcb_control` or call `mj_applyFT` at any point, do I need to consider `qfrc_applied` and `xfrc_applied`?

**Comment by yuvaltassa** [comment]
> Would saving, and at a later time copying components of x and u to mjData, calling mj_forward and then mjd_transitionFD yield the same (correct) results as if I were to call mjd_transitionFD at each step during the simulation? 

Yes. You don't need to call mj_forward, that [happens internally](https://github.com/deepmind/mujoco/blob/7251e7b900f0e1b09ce138f9a82ebdf72cc7a6cc/src/engine/engine_derivative.c#L1513) anyway.

> Also, should I save and copy qacc_warmstart to improve performance in this case as well? 

If you want the derivatives to perfectly match a step from a saved rollout, then yes. But the difference would likely be very tiny.

> And lastly, is this approach likely to outperform filling an array of mjData with mj_copyData and calling mjd_transitionFD on each element?

Yes. Copying mjData is usually expensive and unnecessary. This is the point of having a well-defined state.

> On a slight tangent, if I do not define mjcb_control or call mj_applyFT at any point, do I need to consider qfrc_applied and xfrc_applied?

No, you do not. The engine does not touch these, only the user.
