### ISSUE TITLE
How to change the friction coefficient at runtime as a function of some parameters?

### ISSUE THREAD

**Issue by diuuuuuuuuuuuuuu** [deepmind/mujoco#722]
Hi,

I'm a student and I'm trying to use MuJoCo for simulating a robot moving on a ball.

I want to change the value of friction coefficient during the simulation. 

But I do not know use which API to do it. 

I am very appreciate if you can tell me about this. Thanks.

**Comment by yuvaltassa** [comment]
Replied in #514
