### ISSUE TITLE
XML Error: unknown plugin 'mujoco.elasticity.cable' when running simulate

### ISSUE THREAD

**Issue by JohnChen1024a** [deepmind/mujoco#723]
When I loaded the model "belt.xml" in the directory of model/plugin to "simulate" program of MuJoCo, I got the following error message: 
XML Error: unknown plugin 'mujoco.elasticity.cable'
Element 'required', line 20
Any suggestion for fixing this error is welcome.
My environment: Ubuntu 20.04, MuJoCo version 2.3.1

**Comment by saran-t** [comment]
How did you obtain/install MuJoCo on your machine?

**Comment by JohnChen1024a** [comment]
I downloaded source code from github of MuJoCo, and built it using cmake. (make build;cd build;cmake ..;make -j 8) Under bin, run "simulate" and drag "belt.xml" to it.

**Comment by JohnChen1024a** [comment]
@saran-t Thank you for your help. It works. I suggest this information of searching for plugin directory should be added to the "build from source" section.

**Comment by yuvaltassa** [comment]
@JohnChen1024a, would you like to submit a PR to update the docs as you propose?

**Comment by tadashiK** [comment]
Hello, I encountered the same problem when I installed mujoco via pip or conda. Would you tell me how to fix the issue in this case too?

As for a PR, I would do including a solution fo this too.

To repicate the issue, please use the following colab: https://colab.research.google.com/drive/1tOP38GGEe6xyzKkhhBOgudmn69PDck87?usp=sharing

**Comment by DMackRus** [comment]
Hello, 

I am having similar issues to the ones in this post. I have a custom MuJoCo fork (it's a tiny change and I was hoping it could be added to MuJoCo directly, please see this request issue (https://github.com/google-deepmind/mujoco/issues/1453)). I just wanted public access to one function `mj_stepSkip()` for my own uses.

When i follow the instructions of building from source, I do not have the first party plugins? Currently I have a working hack where I build my custom fork from source, download the latest release and copy the plugins over. This seems fine at the moment I just dont know if it might break down the line.

**Comment by saran-t** [comment]
@DMackRus the plugins are actually built when you run `cmake --build`, the problem is that `cmake --install` isn't copying them over.

This is an oversight in our installation setup, but in the meantime you should be able to find these plugins in the `lib` directory of your build tree.

**Comment by DMackRus** [comment]
@saran-t 

Thank you for your reply, yes that makes sense and I can just add a quick command to my shell script to copy the plugins folder over then to automate my issue, thanks!

**Comment by traversaro** [comment]
@DMackRus if you already have a fork in which you are working, probably cherry-picking the changes in https://github.com/google-deepmind/mujoco/pull/1515 could help you.
