### ISSUE TITLE
Documentation of Keyboard Shortcuts in `simulate`

### ISSUE THREAD

**Issue by SimiPixel** [deepmind/mujoco#735]
Hey,

is there any documentation on the keyboard shortcuts of the `simulate` binary?
E.g. how to exit full screen mode? `ESC` does not work

Thanks :)

**Comment by yuvaltassa** [comment]
Basic GUI help is shown using F1, including how to toggle full screen mode.

**Comment by SimiPixel** [comment]
Thanks!
