### ISSUE TITLE
slider joint is not available

### ISSUE THREAD

**Issue by yuan0623** [deepmind/mujoco#749]
Hi,

I'm a student and I'm trying to use MuJoCo for robotic simulation.

I'm looking for some help with modeling. I tried to implement a linear motor in the MuJoCo. However, when I specify the joint type as `slider`, I receive this error: `Error: invalid keyword: 'slider'\nElement 'joint', line 303, column 7\n"` But if I specify the joint type as `hinge`, everything is fine. 

Here is a model :

<details>

```
<body name="platform" pos="2 2 0.5">
        <geom type="box" size="1 1 0.1" rgba="0.5 0.5 0.5 1"/>
      <joint name='platform_joint' type='slider' axis='0 0 1' range='-75 75' stiffness='0' frictionloss='2' damping='2' armature='0.173824' limited='true' pos='0 0 0'/>
</body>
```

</details>

**Comment by cidxb** [comment]
Hi,
type name of the "slider" is "slide".

 If you change the  type='slide'. It should be fine.  :)
