### ISSUE TITLE
Penetration resolving mechanism

### ISSUE THREAD

**Issue by rongakowang** [deepmind/mujoco#752]
I wonder where can I find the documentation for how MuJoCo resolving mechanism, especially for the below two cases:

1) what if two bodies start by colliding with each other? in this case what will be the direction of repulsive force and if the penetrated mesh points are considered as "contact points"?

2) If a body hits another body at a high speed, one would expect a high enough volume of penetration so that sufficient repulsive force exists to reduce the velocity. I wonder what parameters can be set related to the contact so that the penetration volume can be reduced (essentially close to hard contact, but preserves the continuity)?

**Comment by rongakowang** [comment]
Hi @nimrod-gileadi :

Thank your for your explanation, the issue that I am currently facing is that a free objects may start to be colliding with another static object. My understanding is that the free objects will gain velocity at the direction of contact normal (might be the translation vector you mentioned) to resolve the penetration. However, after the penetration is resolved, the velocity remains and artifacts can happen (e.g. slip or even fly away), which is something I wish to avoid. 

Imagine a box intersects with the ground diagonally, I'd wish the simulation to be that the box first gradually rise to the surface due to resolving the penetration, then fall to the ground. However, what I get is that the object just "ejects" for a distance, which is quite unstable. I wish to figure out why this can happen and is there anything I can do to fix this case?

A sample model for what I have described is as follow that produces the undesired behavior:

```xml
<mujoco model="init">
  <compiler autolimits="true" angle="radian"/>
  <option gravity="0 9.8 0"/>

  <asset>
    <material name="floor" reflectance=".1"/>
  </asset>

  
  <worldbody>
    <light directional='false' diffuse='.8 .8 .8' specular='0.3 0.3 0.3' pos='0 1.0 4.0' dir='0 -1.0 -4'/>

    <body name="box" pos="-0.28885 0.200108 -0.154244"  quat="0.625471 -0.4 0.780247 -1.91355e-12">
      <freejoint />
      <geom type="box" size=".1 .2 .3" />
    </body>

    <body name="ground">
      <geom type="plane" pos="0 0.3 0" euler="1.57079632679 0 0" size="5 5 .01" rgba="1 1 1 1" material="floor"/>
    </body>

  </worldbody>

</mujoco>
```

**Comment by nimrod-gileadi** [comment]
The reason is that the force applied at a contact depends on the depth - this is exactly to resolve the high velocity collision issue you mentioned before. If a ball bounces on the floor, we'll first see a penetration, and to bounce back we need a high force applied in the opposite direction.

Am I right in guessing that you're trying to solve a random initialization problem? The easiest solution is to start from a non-penetrating state, e.g. drop objects from some height. If that's not possible, I suppose you could temporarily add a lot of viscosity to the model during initialization (through the [viscosity](https://mujoco.readthedocs.io/en/stable/XMLreference.html#option) attribute of `<option>`), to quickly damp any high velocities. I haven't tried this myself.

**Comment by rongakowang** [comment]
Hi @nimrod-gileadi:

Thank you a lot for the suggestion. Like you said, I am working on optimizing and refining an initial pose estimation, where the penetration is inevitable (e.g. the quality of the initial poses between two objects can be quite bad with large penetration).

Nevertheless, your viscosity attribute suggestion is really what I want, however, you mentioned that this attribute can be "temporarily" set, does that mean one can set this attribute in run-time? In particular disable it when there is no longer penetration with larger depth? Could you point me where I may find the API for python? Thanks a lot for your assistance.

**Comment by saran-t** [comment]
If you only care about finding good initial poses, one thing that works reasonably well is to manually set all `qvel` to zero (or cap to some maximum limit) between each call to `mj_step`. That way intersection objects will still be pushed apart by contact forces, but they won't fly away at high speeds.

**Comment by saran-t** [comment]
How much penetration are we talking about? There's always going to be some (~millimeter) penetrations in MuJoCo even when things are working correctly.

**Comment by rongakowang** [comment]
Hi @saran-t :

should be ~ 1-2 cm

**Comment by saran-t** [comment]
If you set `qvel` to zero in the penetrating state and things don't move then that means the system has settled in equilibrium and everything is working as expected. If you want to reduce the penetration depth then you need to play with the [solver parameters](https://mujoco.readthedocs.io/en/stable/modeling.html#solver-parameters).

**Comment by nimrod-gileadi** [comment]
> Nevertheless, your viscosity attribute suggestion is really what I want, however, you mentioned that this attribute can be "temporarily" set, does that mean one can set this attribute in run-time? In particular disable it when there is no longer penetration with larger depth? Could you point me where I may find the API for python? Thanks a lot for your assistance.

I'm not sure it's officially documented, but attributes in mjModel.opt can be changed at runtime, yes.

If you're using the MuJoCo bindings directly, you can use `model.opt.viscosity = 0`, and if you're using dm_control `Physics` object, you could use `physics.model.opt.viscosity = 0`
