### ISSUE TITLE
Adding run-time collision geom 

### ISSUE THREAD

**Issue by rongakowang** [deepmind/mujoco#760]
I have a collision geom defined as mesh type, whose vertices `V` is estimated in run-time and faces `F` is predefined. I wonder if it's possible to add this geom in MuJoCo during run-time simulation, potentially multiple meshes as I have to convex decompose it first?

**Comment by yuvaltassa** [comment]
Yes, you can, but if your mesh collides and your changes will modify the vertices which constitute the convex hull, collisions will be strange.

Also, to visualize what you are doing you'll need to call [mjr_uploadmesh](https://mujoco.readthedocs.io/en/latest/APIreference/APIfunctions.html#mjr-uploadmesh) to send the updated vertices to the GPU.
