### ISSUE TITLE
Question about the rendering resource consume in graphic card

### ISSUE THREAD

**Issue by cidxb** [deepmind/mujoco#781]
Hey.
 
**Background Info**
I use the mujoco +  Stable-Baselines3 - ( Reinforcement Learning Implementations)
To train agent with multi-processing (using CPU core to open Mujoco threading parallelly as much as I need)

**Question about the rendering memory cast in graphic card** 
But I find a strange thing, the same script, the same procedure in two computers.

During the simulation, one shows 
![1](https://user-images.githubusercontent.com/32217136/226501753-d4e9c6ba-ec1d-4c75-8d1b-7072cde4bb3a.png)

The other one shows 
![2](https://user-images.githubusercontent.com/32217136/226501851-cc79f4fc-986c-4c82-a9b9-381b0581d836.png)

The first image indicates that I have so many mujoco threading running, and the rendering of them is consuming graphic card resources, which makes sense.

But the second image of another computer shows only one main threading, and it is doing calculation "C", not graphic rendering "G".

I try to set the environment variable `MUJOCO_Gl` into the same `MUJOCO_GL=GLFW`, and the consumption is the same.

Because the SB3 is just parallel opening MUJOCO, so I think I must do something different in setting up mujoco, but I don't know what I have done wrong, can some friends from the community point it out to me?
THX !

**Supplement Info** 
System 1 (The one using graphic card resources):
OS: Ubuntu 20.04.5 LTS
OS Type:64-bit
Graphic: GeForce GTX 1660 6G
Memory: 31.1GB (32)
Processor: Intel@Core i7-10700 CPU@2.90GHZ x16
Pyhton env:3.8.13

System 2 (The one using graphic card resources):
OS: Ubuntu 22.04.2 LTS
OS Type:64-bit
Graphic: GeForce RTX 3060 Mobile/MaxQ 6G
Memory: 15.7GB (16)
Processor: 12th Intel@Core i7-12700H x 20 
Pyhton env:3.10.8

both  MUJOCO_GL=GLFW

Script:
Because it is a project of the RL algorithm library SB3+ MUJOCO simulation of a pick and place task. 
So the mujoco was opened in multi-processing (using CPU core to open Mujoco threading parallelly as much as I need)

It is hard for me to provide a minimal script for it. because of the complexity, 
In the script I used a planted camera to render images for my RL agent, by using the self define a function  `get_image_data`, I think it should be the part really relevant to the rendering consuming problem.

```
def get_image_data(self, show=False, camera="head" ):
        """
        Returns the RGB and depth images of the provided camera.
        Args:
            show: If True displays the images.
            camera: String specifying the name of the camera to use.
        """
        renderer_rgb=mj.Renderer(self.model,width=self.IMAGE_WIDTH,height=self.IMAGE_HEIGHT)
        renderer_depth=mj.Renderer(self.model,width=self.IMAGE_WIDTH,height=self.IMAGE_HEIGHT)
        mj.mj_forward(self.model,self.data)
        renderer_depth.enable_depth_rendering()
        renderer_depth.update_scene(self.data,camera=camera)
        renderer_rgb.update_scene(self.data,camera=camera)
        rgb=renderer_rgb.render()  ###updating the reb image
        depth=renderer_depth.render()  ###updating the depth image
        if show:
            cv.namedWindow("rbg", cv.WINDOW_NORMAL)
            cv.resizeWindow("rbg",1000,1000)
            cv.imshow("rbg", cv.cvtColor(rgb, cv.COLOR_BGR2RGB))
            # cv.namedWindow("depth", cv.WINDOW_NORMAL)
            # cv.resizeWindow("depth",1000,1000)
            # cv.imshow("depth", cv.cvtColor(depth, cv.COLOR_BGR2RGB))
            cv.waitKey(1500)
            cv.destroyAllWindows()
        return np.array(rgb), np.array(depth)
```

**Comment by saran-t** [comment]
You haven't provided us with enough information to be able to tell what might be happening here. What's the script you're trying to run? What's the system configuration? How's your Python environment set up?

**Comment by cidxb** [comment]
> You haven't provided us with enough information to be able to tell what might be happening here. What's the script you're trying to run? What's the system configuration? How's your Python environment set up?

THX your replay! I have edited my original post, and added as much info as I can .

**Comment by saran-t** [comment]
Not really sure what's going on, but my suggested first thing to try is `MUJOCO_GL=EGL` instead of GLFW.

**Comment by cidxb** [comment]
> Not really sure what's going on, but my suggested first thing to try is `MUJOCO_GL=EGL` instead of GLFW.

I don't know why, but if I used `MUJOCO_GL=EGL`

There will be problems like this : 
`Exception ignored in: <function GLContext.__del__ at 0x7f1c14000dc0>
Traceback (most recent call last):
  File "/home/bjae/anaconda3/envs/RL-server/lib/python3.10/site-packages/mujoco/egl/__init__.py", line 130, in __del__
  File "/home/bjae/anaconda3/envs/RL-server/lib/python3.10/site-packages/mujoco/egl/__init__.py", line 123, in free
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.raw.EGL._errors.EGLError: <exception str() failed>`

I checked with this error alert script in errorchecker, still have no clue. 

and 


`X Error of failed request:  BadAccess (attempt to access private resource denied)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  5 (X_GLXMakeCurrent)
  Serial number of failed request:  191
  Current serial number in output stream:  191`

For this error, I also tried to fix it, from the information I gather, it should be an X server error that normally occurred in dueling with a remote SSH server is something with memory resources. BUt strange thing is, I get this problem in local host. And I have tried some solutions I found online. That's why I was using GLFW.

**Comment by saran-t** [comment]
It's very difficult for me to help since whatever is happening seems to be specific to your setup. Is there Docker involved in the run that's not utilising GPU?

**Comment by cidxb** [comment]
> 

Thank you for your reply! I solved this problem, it is kind of a dumb reason : 
This is because the Lenovo laptop runs a dynamic graphic setting that will automatically change the graphic for rendering. The GTX is used for calculation because in the script it chose a cuda device to do that, but for the rendering, the i915 intel graph card has taken over.

So I go to bios and set the dynamic graphic setting to Discrete Graphic, and the problem solved.

And the following command helped me debug 👍, I would to share:

`  $ gpustat`  helps me realize the GPU usage of GTX is 0%
` $  lspci -k | grep -A 2 -i "VGA"`   helps me to see how many graphic cards in the device
`  $ nvidia-setting` helps me realize the GTX GPU current is not in used because it does not show the window of X server setting, and it is almost empty.
  `$ sudo intel_gpu_top`  helps me confirm I am running the rendering of mujoco on the core graphic card

**Comment by simeon-ned** [comment]
> > It's very difficult for me to help since whatever is happening seems to be specific to your setup. Is there Docker involved in the run that's not utilising GPU?
> 
> Thank you for your reply! I solved this problem, it is kind of a dumb reason : This is because the Lenovo laptop runs a dynamic graphic setting that will automatically change the graphic for rendering. The GTX is used for calculation because in the script it chose a cuda device to do that, but for the rendering, the i915 intel graphic card has taken over.
> 
> So I go to bios and set the Dynamic Graphic setting to Discrete Graphic, and the problem was solved.( The original idea is to disable the security Bios boot according to the post I saw online, but instead, I found the dynamic graphic setting.)
> 
> And the following command helped me debug 👍, I would like to share:
> 
> ` $ gpustat` helps me realize the GPU usage of GTX is 0% ` $ lspci -k | grep -A 2 -i "VGA"` helps me to see how many graphic cards in the device ` $ nvidia-setting` helps me realize the GTX GPU current is not in used because it does not show the window of X server setting, and it is almost empty. `$ sudo intel_gpu_top` helps me confirm I am running the rendering of mujoco on the core graphic card

The setting to discrete graphics indeed helps, thanks!
