### ISSUE TITLE
Does mujoco have a formal way to solve ODE numerically?

### ISSUE THREAD

**Issue by yzd0014** [deepmind/mujoco#788]
I'm trying to use mujoco's build-in numerical integration scheme for other dynamical systems besides rigid body's positions. Currently what I did is to create dummy muscle actuators and define my own dynamics for activation of the muscle actuator. The downside for doing this is I need to modify xml file, which is a hack. I'm wondering if there is a more elegant way to serve the same purpose. Thanks in advance.

**Comment by yuvaltassa** [comment]
See also #305 and example custom stateful actuator therein.

**Comment by yzd0014** [comment]
> The best way to create a custom muscle actuator would be to use the actuator plugin functionality. See TestActuator in:
> 
> https://github.com/deepmind/mujoco/blob/main/test/engine/engine_plugin_test.cc
> 
> We don't have custom actuator examples but we have custom passive forces you can start from:
> 
> https://github.com/deepmind/mujoco/tree/main/plugin/elasticity

Thanks for your reply. Sorry, I think the way I asked my question is quite misleading. Instead of having my own custom actuator, I'm wondering if there is a way to simulate my own dynamics besides mujoco's dynamics. For example, what I hope is that, given y'=y-constant I can get y updated at each timestep. Currently what I did is to have something like "mjcb_act_dyn =act-constant".
