### ISSUE TITLE
run ./simulate on the ubuntu 18.04, there is the error:

### ISSUE THREAD

**Issue by 13253591602** [deepmind/mujoco#79]
MuJoCo Pro version 2.10 
Segmentation fault (core dumped)

**Comment by wpumacay** [comment]
Hi @13253591602 . Could you provide some more info (perhaps the call-stack after running gdb to check in which function it crashed). Just to double check: are you running the already compiled `simulate` binary that comes with the `tar.gz` file?, or are you building it yourself using the provided `Makefile` in the samples folder?

**Comment by 13253591602** [comment]
> Hi @13253591602 . Could you provide some more info? (perhaps the call-stack after running gdb to check in which function it crashed). Just to double check: are you running the already compiled `simulate` binary that comes with the `tar.gz` file?, or are you building it yourself using the provided `Makefile` in the samples folder?

thanks for your reply, maybe it is os's fault, this is the error message:
Starting program: /home/yh/.mujoco/mujoco210/bin/simulate
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
MuJoCo Pro version 2.10
[New Thread 0x7fffe8a2a700 (LWP 29081)]
[New Thread 0x7fffe8229700 (LWP 29082)]
[New Thread 0x7fffe7a28700 (LWP 29083)]
[New Thread 0x7fffe7227700 (LWP 29084)]
[New Thread 0x7fffe6a26700 (LWP 29085)]
[New Thread 0x7fffe6225700 (LWP 29086)]
[New Thread 0x7fffe5a24700 (LWP 29087)]
[New Thread 0x7fffe5223700 (LWP 29088)]
[New Thread 0x7fffe4a22700 (LWP 29089)]
[New Thread 0x7fffbffff700 (LWP 29090)]
[New Thread 0x7fffb7fff700 (LWP 29091)]
[New Thread 0x7fffbf7fe700 (LWP 29092)]
[New Thread 0x7fffbeffd700 (LWP 29093)]
[New Thread 0x7fffbe7fc700 (LWP 29094)]
[New Thread 0x7fffbdffb700 (LWP 29095)]
[New Thread 0x7fffbd7fa700 (LWP 29096)]

Thread 1 "simulate" received signal SIGSEGV, Segmentation fault.
__strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:31
31      ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S: No such file or directory.

But I don't know what is strcmp-sse2-unaligned.S and how to install it（please forgiving my poor English)

**Comment by wpumacay** [comment]
mmm, I think it's support for `SSE2`. Could you provide the specs of your CPU?. Perhaps it doesn't support `SIMD` (MuJoCo currently requires `AVX`, but `SSE` should be available in most modern processors)

**Comment by 13253591602** [comment]
> mmm, I think it's support for `SSE2`. Could you provide the specs of your CPU?. Perhaps it doesn't support `SIMD` (MuJoCo currently requires `AVX`, but `SSE` should be available in most modern processors)

 *-cpu:0
          product: Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
          vendor: Intel Corp.
          physical id: 6
          bus info: cpu@0
          size: 1236MHz
          capacity: 2900MHz
          width: 64 bits
          capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp x86-64 constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts md_clear flush_l1d cpufreq
     *-cpu:1
          product: Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
          vendor: Intel Corp.
          physical id: 7
          bus info: cpu@1
          size: 1203MHz
          capacity: 2900MHz
          width: 64 bits
          capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp x86-64 constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts md_clear flush_l1d cpufreq

**Comment by wpumacay** [comment]
mmm, that's expected. Your CPU supports `SIMD` (even `AVX2`). Can you recompile the binaries using the provided makefile? (it's on the samples folder I think)

**Comment by 13253591602** [comment]
> mmm, that's interesting. Your CPU does supports `SIMD` (even `AVX2`). Can you recompile the binaries using the provided makefile? (it's on the samples folder I think). Perhaps you used the provided binaries right out of the box, but your CPU is a tad different (has the same intruction set, but perhaps it complains for some instructions 🤔 ?)
> 
> Also, by any chance are you running it on a server? (I've never seen a Xeon on a Desktop computer unless you really like that many cores on Intel 😅)

Actually，I ran it on the server😅

**Comment by wpumacay** [comment]
Oh, that might be the error then xD. The provided `simulate` binary is compiled to use `glfw` as windowing library (creates a windows, e.g. in linux it might use X11 or wayland), so if you have no window session started (in Ubuntu it would be something like an Xorg session) then you can't use anything that tries to do graphics, unless you use the `EGL` version of it (which doesn't require to have an X11 session)

**Comment by 13253591602** [comment]
> Oh, that might be the error then xD. The provided `simulate` binary is compiled to use `glfw` as windowing library (creates a windows, e.g. in linux it might use X11 or wayland), so if you have no window session started (in Ubuntu it would be something like an Xorg session) then you can't use anything that tries to do graphics, unless you use the `EGL` version of it (which doesn't require to have an X11 session)

mmm,how to solve it?I'm sure that I have X11

**Comment by saran-t** [comment]
We've changed the GL linkage on `simulate` in our 2.1.1 release. Could you please try again with the new version and let us know if the issue persists? (Also, make sure you enable X forwarding on your SSH session -- `ssh -X`)

**Comment by kevinzakka** [comment]
Marking as resolved. Feel free to re-open if you are still encoutering any issues.
