### ISSUE TITLE
Accessing joint pos variable through Python 

### ISSUE THREAD

**Issue by studywolf** [deepmind/mujoco#808]
Hi,

I'm a researcher and I'm trying to use MuJoCo for modeling arm movement.

I'm trying to generate a symbolic representation of the forward kinematics for an arm model I built. I'm generating that now, but I'm trying to access the joint position offset (as specified in the XML with the 'pos' keyword in the 'joint' tag), but I'm having trouble figuring out how to do that from the Python bindings. The data.joint(name).pos command throws an error, asking if i mean 'qpos', which I don't.  
How can I access this?
Thanks very much!

**Comment by yuvaltassa** [comment]
This value is constant and therefore in model, not in data.
