### ISSUE TITLE
Mujoco render on browser

### ISSUE THREAD

**Issue by rajuptvs** [deepmind/mujoco#809]
Hi,

I'm a student and I'm trying to use MuJoCo using web interface  through the use of FastAPI, 

Is there any way to render the viewer on a browser instead of application? 
Would greatly appreciate it if anyone could give me any ideas or avenues to look at.

Thanking you in advance

**Comment by saran-t** [comment]
You can check out https://github.com/zalo/mujoco_wasm

**Comment by geyang** [comment]
This is a bit late, but we have managed to rewrite the rendering and interaction part of MuJoCo using a new stack that runs in the browser. 

- https://docs.vuer.ai/en/latest/tutorials/physics.html
