### ISSUE TITLE
Do not need compile options ${MUJOCO_SIMULATE_COMPILE_OPTIONS} passed by libsimulate

### ISSUE THREAD

**Issue by limymy** [deepmind/mujoco#814]
Compile options `MUJOCO_SIMULATE_COMPILE_OPTIONS` is marked as `PUBLIC` by target libsimulate and platform_ui_adapter in version `2.3.3`.

https://github.com/deepmind/mujoco/blob/34226bf52d07dc0d14d775d665999944d04570b2/simulate/CMakeLists.txt#L110

https://github.com/deepmind/mujoco/blob/34226bf52d07dc0d14d775d665999944d04570b2/simulate/CMakeLists.txt#L135

Please set it to `PRIVATE` for easy using.

**Comment by saran-t** [comment]
Can you send a PR?

**Comment by limymy** [comment]
I have sent a PR. #815
