### ISSUE TITLE
Custom camera view

### ISSUE THREAD

**Issue by QUIlToT** [deepmind/mujoco#820]
Hi!

I want to customize a camera view (pos and quat), which is obtained by adjusting it in the Mujoco window.

After I adjusted the current view, I wanted to treat it as my ideal camera view.

How do I get the current view (pos and quat)?

I want to add the pos and quat into the XML file, i.e.,

`   <camera mode="fixed" name="customview" pos="* * * " quat="* * * *" /> `

Help would be appreciated!

**Comment by yuvaltassa** [comment]
simulate has a "Copy camera" button that puts what you want in the clipboard.

<img width="249" alt="Screenshot 2023-04-15 at 19 15 46" src="https://user-images.githubusercontent.com/6387526/232246611-4da76112-72da-4f4f-a6e3-344c5f51745f.png">
