### ISSUE TITLE
Black screen from mujoco.viewer

### ISSUE THREAD

**Issue by C-monC** [deepmind/mujoco#821]
Hi,

I install mujoco using pip.
> pip show mujoco
> Name: mujoco
> Version: 2.3.3

I run the following code:
```
import mujoco
from mujoco import viewer

model = mujoco.MjModel.from_xml_path('model_testing/viscous_test.xml')
viewer.launch(model)
```
![screenshot](https://user-images.githubusercontent.com/17007879/232314088-27718214-422d-4706-b3c9-24c415303369.png)

The viewer always only shows this diagonal line. I can see the actual model through the "live" pixels.

I am using ubuntu through wsl (probably not supported). Is there anyway I can see extra logs from the viewer?
I've tried adding a camera in the XML as well but it had the same result.

Here is my xml for reference:
```
<mujoco>
  <option density="1.225" viscosity="1.8e-5" wind="0 0 1" integrator="implicit"/>

  <worldbody>
    <light pos="0 0 1"/>
    <geom type="plane" size="1 1 .01" pos="0 0 -1"/>
    <body>
      <freejoint/>
      <geom type="box" size=".025 .01 0.0001" pos=".025 0 0" euler="20 0 0" mass="1e-4" fluidshape="ellipsoid"/>
      <geom type="box" size=".025 .01 0.0001" pos="-.025 0 0" euler="-19 0 0" mass="1e-4" fluidshape="ellipsoid"/>
    </body>
  </worldbody>
</mujoco>
```

**Comment by yuvaltassa** [comment]
Do you get the same thing with other models? E.g. something from the `mujoco/model/` directory.

**Comment by C-monC** [comment]
I just tried the adhesion example but I get the same issue. 

![screenshot](https://user-images.githubusercontent.com/17007879/232322673-cc420719-5d03-4285-8f85-0a67bdc0b2ab.png)

**Comment by saran-t** [comment]
Could you please try setting the environment variables `MUJOCO_GL_DEBUG=1` and `LIBGL_DEBUG=verbose`, and see if you get any message?

**Comment by C-monC** [comment]
Thanks for the help but I just switched to a Linux host and it works.

**Comment by santoshchaganti** [comment]
Hi I am also facing same error. And i tried environment variables as mentioned by saran-t but no message sent back. Is there any other ways to fix this issue
