### ISSUE TITLE
Simulation

### ISSUE THREAD

**Issue by Anahide-Vanian** [deepmind/mujoco#846]
Hello to all, 
I have started to use Mujoco to simulate a robot interacting in its environment.
I have a python code that programs the robot to perform the pick and place task.

I would like to have a graphical display of my robot executing its task and be able to change the simulation state along the way using the interface buttons. Fr example, I would like to be able to change the configuration of the robot which would imply that I terminate its routine by taking over via  the interface. Also, I would like to be able to pause and restart the simulation execution.

In the documentation, I saw that there are 2 types of viewer for rendering. I tried to use the passive viewer and I could get a graphical window in which the robot executes the trajectories I command it. However, many buttons don't work like the ones to pause and restart the simulation.

Do someone know if there is a way to get what I want please ?

Thank you in advance :)

**Comment by saran-t** [comment]
I can try and pass along spacebar keypress event up to the Python side in the next release, but the idea behind the passive viewer is that the user's script is in charge of controlling the entire physics loop, which includes starting and stopping it.
