### ISSUE TITLE
Illegal Instruction (core dumped)

### ISSUE THREAD

**Issue by lzhhh93** [deepmind/mujoco#849]
Following along with https://github.com/openai/mujoco-py on Windows 11 running an Ubuntu 20.04 (64-bit) VM I run into the error:

![image](https://user-images.githubusercontent.com/38736831/236153993-dd278e3a-d4ff-4937-a3f4-2a42a4d6af35.png)

Here is the output of `cat /proc/cpuinfo:` (given that 6 processor are set in my VM, only the info of the first one is posted here)
![image](https://user-images.githubusercontent.com/38736831/236155216-4aa0240f-8996-4c47-ad9a-05489ef86993.png)

Since I have actually got mujoco-py to work using another Ubuntu 20.04 VM in my curent laptop (that one is unfortunately toasted), I believe my hardware should be fine to set up mujoco/mujoco-py.

On the other hand, if I want to get mujoco-py to work, how should I apply the solution from https://github.com/deepmind/mujoco/issues/487 ? In particular, how to build mujoco-py from source with AVX disabled? Or should I build mujoco from source with AVX disabled, then somehow get it linked to mujoco-py? A specific instruction will be greatly appreciated.

Appreciate for some help.

Sincerely.

**Comment by saran-t** [comment]
You should build MuJoCo without AVX following Nimrod's instructions in #487.

We don't support mujoco-py since it's not a something that we develop our maintain. However, I expect that you should be able to follow their installation instructions normally with your custom-built copy of MuJoCo.

**Comment by lzhhh93** [comment]
> You should build MuJoCo without AVX following Nimrod's instructions in #487.
> 
> We don't support mujoco-py since it's not a something that we develop our maintain. However, I expect that you should be able to follow their installation instructions normally with your custom-built copy of MuJoCo.

Thanks for a quick response. Since mujoco-py only supports Mujoco upto 2.1.0 version, could you also share the way to deactivate AVX there for Mujoco 2.1.0?

**Comment by yuvaltassa** [comment]
Did you try the same instructions for 2.1.0?

**Comment by saran-t** [comment]
@yuvaltassa There's no released source code for 2.1.0.

**Comment by lzhhh93** [comment]
> @yuvaltassa There's no released source code for 2.1.0.

Is there any possible way that I could get over this error? Since the project depends on mujoco-py, I can only stay at the Mujoco 2.1.0.

**Comment by yuvaltassa** [comment]
I'm afraid not, other than [switching away from mujoco-py](https://mujoco.readthedocs.io/en/latest/python.html#migration-from-mujoco-py) or bringing this up with mujoco-py maintainers.
