### ISSUE TITLE
Non-physical behavior happened when using Composite to simulate an elastic band

### ISSUE THREAD

**Issue by ZhaotingLi** [deepmind/mujoco#856]
Hi,

I'm a student and I'm trying to use MuJoCo for trajectory planning in deformable environments.

I need some assistance regarding the simulation of elastic bands using the composite object, specifically the 2D grid, in Mujoco. I have noticed that when the robot makes contact with the band and stretches it, the band penetrates the robot's body and returns to its stable state without any collisions. This behavior seems unrealistic, and I was wondering if there is a way to fix this in Mujoco. Could this issue be caused by the soft constraint of contact handling?  Thanks for the help in advance!

Here is a model which explains my question:

<details>
  <summary>minimal XML</summary>

```XML
<mujoco model="panda scene">

  <include file="panda.xml"/>

  <statistic center="0.3 0 0.4" extent="1"/>

  <visual>
    <headlight diffuse="0.6 0.6 0.6"  ambient="0.3 0.3 0.3" specular="0 0 0"/>
    <rgba haze="0.15 0.25 0.35 1"/>
    <global azimuth="120" elevation="-20"/>
  </visual>

  <asset>
    <texture type="skybox" builtin="gradient" rgb1="0.3 0.5 0.7" rgb2="0 0 0" width="512"
        height="3072"/>
    <texture type="2d" name="groundplane" builtin="checker" mark="edge" rgb1="0.2 0.3 0.4"
        rgb2="0.1 0.2 0.3" markrgb="0.8 0.8 0.8" width="300" height="300"/>
    <material name="groundplane" texture="groundplane" texuniform="true" texrepeat="5 5"
        reflectance="0.2"/>
  </asset>

  <worldbody>
    <light pos="0 0 1.5" dir="0 0 -1" directional="true"/>
    <geom name="floor" size="0 0 0.05" type="plane" material="groundplane"/>
    <body name="eb" pos="0 0 0" euler="0 0 -1.57">
      <composite type="grid" count="39 2 1" spacing="0.02" offset="0 0.50 0.6">
        <joint kind="main" damping="0.05" stiffness="5" />
        <geom size=".01"/>
        <pin coord="0 0"/>
        <pin coord="38 0"/>
        <pin coord="0 1"/>
        <pin coord="38 1"/>
      </composite>
    </body>
  </worldbody>

</mujoco>
```

</details>

Here is a  video, illustrating my question:

https://user-images.githubusercontent.com/91284814/236764399-e5a3c3e9-6202-4e0a-8c3b-caf635f2c3c8.mp4

Here is some images showing the problem:

![image_0032](https://user-images.githubusercontent.com/91284814/236766829-2c2bd12e-3068-4500-b60b-0d458bb05f1a.jpg)
![image_0035](https://user-images.githubusercontent.com/91284814/236766108-5f745ac0-175c-402c-a9db-e745ada6aaae.jpg)

**Comment by yuvaltassa** [comment]
All constraints in MuJoCo are fairly soft by default. You need to do some combination of:
1. Make the band softer (reduce stiffness).
2. Make the contacts stiffer (reduce solref[0], maybe increase solimp[0, 1]). Note that these values are averaged between the two contacting geoms. It might be enough to do it only for the band geoms, or maybe for all geoms in the scene. There are multiple ways to do this, see [Contact parameters](https://mujoco.readthedocs.io/en/latest/modeling.html#contact-parameters).

Even given these changes, you can still get "tunneling" if contacts are made with high velocity. In this case you might want to reduce the timestep.
