### ISSUE TITLE
Difference in Obj file behaviors 

### ISSUE THREAD

**Issue by vikashplus** [deepmind/mujoco#859]
Hi, 
I'm trying to use the obj files to build some models. I'm observing some difference in texturing between the behavior of the obj mesh between the mujoco(left) and other software (meshlab, right). Note the white diagonal patch. Maybe I'm missing something?

- Mujoco2.3.4
- Object meshes are exported from blender

<img src="https://user-images.githubusercontent.com/12837145/236934854-6b07e61e-2afe-43e9-8f0a-cf2af415288a.png?raw=true" height=200><img src="https://user-images.githubusercontent.com/12837145/236934861-9ea51b65-bbb9-406b-81a1-7bfa41d417c4.png" height=200>

[obj_difference.zip](https://github.com/deepmind/mujoco/files/11425182/obj_difference.zip)

**Comment by yuvaltassa** [comment]
This is a known issue, having to do with OBJ files allowing multiple textures on a single mesh, which is currently not possible with MuJoCo. The solution is to break up the OBJ into multiple submeshes, each referencing a single texture. Happily, @kevinzakka wrote a tool called [obj2mjcf](https://github.com/kevinzakka/obj2mjcf), which does exactly this 🙂

**Comment by vikashplus** [comment]
@yuvaltassa  -- the model I shared only uses a single texture (`scene.png`). No?

**Comment by vikashplus** [comment]
@quagla  -- Yes editing the `vt` fixes the issue in MuJoCo.

The mesh in its original form is an export from blender. It loads back well on other softwares likes like MeshLab. What I'm trying understand is why is the behavior different in MuJoCo, while okay in others.

**Comment by yuvaltassa** [comment]
@vikashplus, thanks for the bug report!
This is now fixed at head.
