### ISSUE TITLE
Analytical policy gradient using num diff with contacts

### ISSUE THREAD

**Issue by Jogima-cyber** [deepmind/mujoco#865]
Hi,

I'm trying to use MuJoCo to get gradients in contact situations with numerical differentiation (finite differences).
I'm currently using these lines to calculate the forward dynamics :
```
mujoco.mj_forward(mj_model, mj_data)
mujoco.mj_Euler(mj_model, mj_data)
```
and then later this line to get the num diff gradients : 
```
mujoco.mjd_transitionFD(mj_model, mj_data, eps, centered, Fx, Fu, None, None)
```
This works well when there are no contacts, I've checked the gradients.

I was wondering if this is still giving the correct num diff gradient in a contact situation. I've read [this issue](https://github.com/openai/gym/issues/1541) which seems to indicate that I have to add ```mujoco.mj_rnePostConstraint(mj_model, mj_data)``` before the call to ```mujoco.forward``` but I'm not sure, what do you think?

**Comment by erez-tom** [comment]
I expect things to Just Work.  Give it a try, and let us know how it goes!
