### ISSUE TITLE
Slow running speed after adding cables

### ISSUE THREAD

**Issue by zxwang96** [deepmind/mujoco#868]
Hi,

I'm a student trying to use mujoco for a cable grasping task. I found the running speed of mujoco became very slow after I added several (4) 'cable' objects to the environment. My script's basic structure is updating data.ctrl and calling mj.step() for each iteration of a for loop. There is a answer https://github.com/deepmind/mujoco/issues/85#issuecomment-1138635754 suggested that we can use c++ instead to generally accelerate the simulation. My questions are:

1. Could you suggest some approaches to accelerate mujoco in python?
2. If there is no good solution for 1, does switching to c++ apply to my case?

Thank you!

**Comment by yuvaltassa** [comment]
Unfortunately I think there is currently no easy way to speed up these simulations.

We are working on improvements to soft body modeling, including speed, but computation time will always grow with the number of degrees-of-freedom and soft bodies, by definition, have a large number of DoFs.
