### ISSUE TITLE
URDF substitute for Ellipsoid geom objects?

### ISSUE THREAD

**Issue by jimzers** [deepmind/mujoco#87]
Hi! Was looking into translating a MJCF file into a URDF file, and was wondering what the best substitute would be for the "ellipsoid" type geometry objects.

Would appreciate any tips. Thanks!

**Comment by yuvaltassa** [comment]
Does URDF not support ellipsoids?
If not then I think your best bet is to just create ellipsoidal meshes. 
Maybe in [MeshLab](https://www.meshlab.net/)?
