### ISSUE TITLE
Distance query between two geoms

### ISSUE THREAD

**Issue by QUIlToT** [deepmind/mujoco#872]
Hi!

I want to query the distance between two geoms. 

I have checked [this issue](https://github.com/deepmind/mujoco/issues/635#issue-1482112544), but setting margin cannot query the closet distance between two geoms by `contact.dist` when the closet distance larger than margin.

Is there a function to support this detection?

Thanks!

**Comment by yuvaltassa** [comment]
margin+gap is the current mechanism which allows you to do this.

Can you explain how this mechanism is insufficient for your needs? (ideally by providing a minimal example model)

**Comment by yuvaltassa** [comment]
Everywhere in your model I set `margin=gap=1`, this lets me detect inactive contacts at a distance of up to 1 meter. This also works for 10 or any positive number.

Does this solve your problem?

**Comment by erez-tom** [comment]
You can eliminate that via collision filtering, either with em explicit `exclude` clause, or by introducing collision masks using `contype` and `conaffinity`.

**Comment by yuvaltassa** [comment]
So make gap bigger than margin?

**Comment by yuvaltassa** [comment]
The [collision table](https://github.com/deepmind/mujoco/blob/main/src/engine/engine_collision_driver.c#L36) is [exposed in the API](https://github.com/deepmind/mujoco/blob/main/include/mujoco/mujoco.h#L78). If you know what you're colliding you should be able to just call these?

**Comment by yuvaltassa** [comment]
Calling the functions in collison table is exactly what you want. If you know the types of a pair of geoms these functions will just compute the distance (as well as frame etc).

However, in my attempt to write example code for you. I realised the [collision table](https://github.com/deepmind/mujoco/blob/e338034995340b6c7c62ae8f14e4ca100d77998a/include/mujoco/mujoco.h#L78) is not exposed to Python. @saran-t am I right that it's not exposed? Could we expose it?
