### ISSUE TITLE
UR5 with a soft gripper

### ISSUE THREAD

**Issue by hai-h-nguyen** [deepmind/mujoco#877]
Hi,

I'm a student and I'm trying to use MuJoCo for my research project.

I'm seeking some help with simulating a UR5 robot with a soft gripper similar to the attached figure. Essentially, there are several springs connecting the arm to the gripper so that the gripper becomes soft, suitable for contact-rich tasks. I want to ask whether it is doable using MuJoCo. And if yes, are there any pointers simulating such a robot? Thank you!

![soft_wrist](https://github.com/deepmind/mujoco/assets/32955308/dfcc8072-f47e-4460-a835-059635e24dad)

**Comment by yuvaltassa** [comment]
Yes this is very doable. 

Read the documentation, make a simple model to understand the components (you want spatial tendons with stiffness and probably damping to simulate the springs), and if something doesn't work, ask us here.
