### ISSUE TITLE
Unreliable force-torque readings

### ISSUE THREAD

**Issue by rollingball-3** [deepmind/mujoco#883]
Hi,
I'm a student and I'm trying to use MuJoCo for robot simulation.
![animated](https://github.com/deepmind/mujoco/assets/68270052/9f7c419c-e5de-484e-be59-235b8f32c400)
Here, a cylinder peg slipping while in contact with the desk(box).

Below is my contact force data read directly from force and torque sensor in mujoco.
![image](https://github.com/deepmind/mujoco/assets/68270052/f4a8081b-16c4-4dfa-aaef-6f384fb16548)
There exists lots of jumping datas which make me feel unreliable.

I have tried to adjust some parameters like **solref** **solimp** **friction** **condim**. But it seems not work pretty well.
How can I get reasonable force readings in this situation ? Thank you for your time.

**Comment by JeanElsner** [comment]
In my experience real data looks even more wild.

**Comment by rollingball-3** [comment]
@erez-tom Sorry for my late reply. First, cartesian impedance control is used to directly calculate desired joint torque. And I use **motor** actuator to control robot.  The stiffness is set to 100-200. As you said, I have made some attempts on physical franka robots, data was collected from the panda robot itself (estimation) not from the force-torque sensor.
![image](https://github.com/deepmind/mujoco/assets/68270052/30550f0b-a0e0-4ecc-b90b-f96eb865570a)
One thing makes me feel unreasonable is that during silpping , the state changes between contact and non-contact frequently. But it supposed to be contact always(?)

**Comment by rollingball-3** [comment]
@yuvaltassa Thank you for your reply. MultiCCD has small influence, while setting `solimp[0]=0` works much better.
