### ISSUE TITLE
Not able to wind the winch properly using rope composite.

### ISSUE THREAD

**Issue by haasithp** [deepmind/mujoco#885]
Hi,

I'm a student and I'm trying to use MuJoCo for Research.
Please find the attached video.
Could you please help me with how to wind the rope and also how to connect the other end to another body using the equality constraint(as seen in the image?

![screenshot](https://github.com/deepmind/mujoco/assets/99711236/6fc8d868-6860-44ca-8865-03185052b132)

https://github.com/deepmind/mujoco/assets/99711236/76748e42-9f26-4f8d-a219-91660258d175

**Comment by quagla** [comment]
Can you post the XML you are using? Also, the rope is deprecated in favour of the cable, but I have the feeling that you might actually want to use a 1d grid for this application because you actually need to stretch the cable to obtain what you want (i.e. the cable is in tensile stress).

**Comment by haasithp** [comment]
So, the rope winded on the winch drum shouldn't have any elasticity. Here, I am trying to simulate something like a slingshot. The rope winds around the drum, stretching the elastic material attached at the other end of the rope, storing enough energy to release an object.
