### ISSUE TITLE
Operational Space Control

### ISSUE THREAD

**Issue by acampos074** [deepmind/mujoco#89]
Can you help comment if the rotation jacobian with respect to the end effector can be used to assemble the basic jacobian (i.e. is it representation independent) or do we need to mutiply this jacobian by a representation inverse (e.g. direction cosines, quaternion, axis-angle,etc.) in order to implement position and orientation end effector control? If so, what is this 3x3 matrix inverse representation? I have succesfully implemented task space position control in a 7-axis robot, but I'm having issues with the orientation part, and I think the issue is related to the rotation jacobian from mju_jacBodyCom() function.

**Comment by yuvaltassa** [comment]
Hi,

I'm not sure I can parse your question.

In order for us to be able to help you we would need a minimal example. If you could make a **very simple** model, perhaps with only one joint, such that you know exactly what is the Jacobian you expect to get -- then please post it here with the associated expected and actual values that you get from MuJoCo, and we could resume this conversation.
