### ISSUE TITLE
how to set and change the body pos in the code writing while not in the xml?

### ISSUE THREAD

**Issue by wukongwong** [deepmind/mujoco#890]

**Comment by yuvaltassa** [comment]
Please provide a clearer description. Your question is ambiguous.

**Comment by wukongwong** [comment]
Pls see the supplementary info I provided above. Thanks a lot.

**Comment by saran-t** [comment]
Could you please post the full program code? It's unclear to me in the bit of code before the formatted block what belongs in the `hand_config_setting` function, and als where `hand_config_setting` is being called. Thanks!
