### ISSUE TITLE
Interaction with mujoco.viewer

### ISSUE THREAD

**Issue by alk21** [deepmind/mujoco#892]
Hi,

I'm a professor and I'm trying to use MuJoCo for teaching.

I'm looking for some help with how to interact with the pre-build Mujoco viewer in python. 
In the past, I was using mujoco haptix for teaching e.g., robot control in contact with the environment and grasping and it worked really well. The haptix run as a standalone program with which you interacted via communication channel,  with for example Matlab.  Can the same be achieved with running: python -m mujoco.viewer (with a loaded scene) in one window and then another python script communicating with the simulator?  
if yes is there a code example that you can provide just to establish the communication to read mj_data...?

thank you in advance,
A

**Comment by yuvaltassa** [comment]
There is currently no infrastructure for communicating with a remote process over sockets (like Haptix).

However we think the [passive viewer](https://mujoco.readthedocs.io/en/latest/python.html#passive-viewer) gives a better user experience for Python users and is currently the recommended viewer mode.

Could you try it and see what you think?

**Comment by saran-t** [comment]
I'm a little occupied with ICRA this week but can try and come up with a short example to get you started.

**Comment by alk21** [comment]
An example would be highly appreciated, I will combine it with some of my code for robot control and see if it makes sense for teaching.

**Comment by saran-t** [comment]
If I understand correctly, you want to be able to modify `mjModel` and/or `mjData` in a REPL session, e.g. through IPython, and see the modifications live in the viewer.

`launch_passive` supports this use case. After the physics state is modified, you need to call `v.sync()` where `v` is the handle that's returned by `launch_passive(m, d)`.

The only caveat is that if you're on macOS, you need to launch your IPython session using our special `mjpython` launcher, e.g. via `mjpython -m IPython`. On other platforms, just launch IPython normally.

Please see [my screencast](https://drive.google.com/file/d/1fHeEHceux-egVgCnZQsfobihfBrPnPK2/view) which demonstrates how this works.
