### ISSUE TITLE
Binary for Apple chip?

### ISSUE THREAD

**Issue by shuvoxcd01** [deepmind/mujoco#90]
Hi,
Will there be a binary for the apple-chip-based macs soon?

**Comment by matte-esse** [comment]
The main issues was just closed, https://github.com/deepmind/mujoco/issues/2 the new version has been released.

However before this issues is closed too I wanted to ask if it's all ready to be run using python or if we have to wait for an updated of the python library https://pypi.org/project/mujoco-py/#history and if we have to wait for a release on MuJoCo website https://mujoco.org/download

**Comment by matte-esse** [comment]
Duplicate of #2

**Comment by saran-t** [comment]
Closing this as a duplicate, let's continue the discussion in #2
