### ISSUE TITLE
date for the next release?

### ISSUE THREAD

**Issue by rsc9421** [deepmind/mujoco#900]
Hi, 
I am very excited to test mj_multiRay() because I need to simulate 3d lidars with a lot of points(800k points per second), is there a tentative date for the next release ? 

https://github.com/deepmind/mujoco/blob/main/src/engine/engine_ray.c#LL1090C6-L1090C17

**Comment by yuvaltassa** [comment]
We generally release every 6 weeks or so. Why don't you just [build from source](https://mujoco.readthedocs.io/en/latest/programming/index.html#building-from-source)?
