### ISSUE TITLE
Help needed viewer AttributeError__enter__

### ISSUE THREAD

**Issue by mertalagozlu** [deepmind/mujoco#901]
I'm a student and I'm trying to use MuJoCo for academic purposes.

I'm looking for some help with mujoco viewer. I am getting '    with mujoco.viewer.launch_passive(self.model, self.data) as viewer: AttributeError    with mujoco.viewer.launch_passive(self.model, self.data) as viewer:: 
AttributeError__enter__ : __enter__'. The code is basically exactly the same code in the documentation.

Here below is a code, which explains my question:

 def simulate(self):
        with mujoco.viewer.launch_passive(self.model, self.data) as viewer:
            while viewer.is_running():
                step_start = time.time()
                for i in range(len(self.data.ctrl)):  # get number of controls
                    if self.predicted_values is not None:
                        self.data.ctrl[i] = self.predicted_values[i]

I am using PyCharm Python 3.10.

Thank you very much

**Comment by kevinzakka** [comment]
What MuJoCo version are you using?

**Comment by mertalagozlu** [comment]
version is 2.3.3

**Comment by kevinzakka** [comment]
You need 2.3.5 (actually at least 2.3.4 but skip that one) for the context manager.
