### ISSUE TITLE
mj_ray() arguments issue 

### ISSUE THREAD

**Issue by MissMulledWine** [deepmind/mujoco#904]
Hello,

I'm a student and I'm trying to use MuJoCo for multi-agent RL.

I'm looking for some help with **mj_ray()** function.

I wanted to print **mj_ray()** after each step, but I constantly get the following error: 

```
TypeError: mj_ray(): incompatible function arguments. The following argument types are supported:
    1. (m: mujoco._structs.MjModel, d: mujoco._structs.MjData, pnt: numpy.ndarray[numpy.float64[3, 1]], vec: numpy.ndarray[numpy.float64[3, 1]], geomgroup: Optional[numpy.ndarray[numpy.uint8[6, 1]]], flg_static: int, bodyexclude: int, geomid: numpy.ndarray[numpy.int32[1, 1], flags.writeable]) -> float
```

My **step()** function works fine, but I am confused about **the arguments** for mj_ray() function, I have defined it as follows: 

   ```
 while (data.time - simstart < 1.0 / 60.0):
        # simulation step
        mj.mj_step(model, data)
        # Apply control
        data.ctrl[1] = 0.1
        data.ctrl[0] = -0.1
        mj.mj_kinematics(model, data)
        mj.mj_ray(model, data, pnt=np.array([0, 0, 3], dtype="float64"), vec=np.array([10, 0, 0], dtype="float64"),
                  geomgroup="NULL", flg_static=0, bodyexclude=-1, geomid=np.array([2], dtype='int32'))

    if (data.time >= simend):
        break
```
I am beginner and probably just can't see the very basic problem here, but I have tried a bunch
of arguments for this function and nothing works.... 

Also, I would like to ask, if there is some code on how to implement user sensor! 

Thanks in advance for any help!!!

**Comment by saran-t** [comment]
`mj_ray` expects `geomgroup: Optional[numpy.ndarray[numpy.uint8[6, 1]]]` but you've passed `geomgroup="NULL"`.

Should be `None`.

**Comment by MissMulledWine** [comment]
Thank you for your reply!

I set it to None, but I still keep getting the same error message

Am Mo., 5. Juni 2023 um 18:46 Uhr schrieb Saran Tunyasuvunakool <
***@***.***>:
