### ISSUE TITLE
multi-object OBJs not rendered correctly

### ISSUE THREAD

**Issue by PeterMitrano** [deepmind/mujoco#911]
@acsipos
Attached is an OBJ file that loads/renders correctly in software like blender, meshlab, etc... but shows up incorrectly in the mujoco viewer.

What seems to be happening is that the collision checker uses the convex hull (as usual) but the renderer only shows the first object? See the attached OBJ and XML file. If you load it in the viewer you will see just one of the two parts of the probe, but the collision checker seems to be taking the chull of the whole thing. 

[probe.zip](https://github.com/deepmind/mujoco/files/11691967/probe.zip)

![probe_mj](https://github.com/deepmind/mujoco/assets/4010770/83c4dbd7-d3e1-4534-8706-be4c99a00577)

![probe](https://github.com/deepmind/mujoco/assets/4010770/9c9fad9f-8568-40ae-b8ff-a462e273bb9d)

Tested with
  - Ubuntu 20
  - MuJoCo version 2.3.5

**Comment by kevinzakka** [comment]
See [this discussion](https://github.com/deepmind/mujoco/discussions/340#discussioncomment-2929469) for an explanation as to why MuJoCo won't support composite OBJ files. Fortunately, you can use [obj2mjcf](https://github.com/kevinzakka/obj2mjcf) to make it MuJoCo compatible.
