### ISSUE TITLE
API provided to record data

### ISSUE THREAD

**Issue by lyuyiqi** [deepmind/mujoco#922]
Hi, thank you for developing this tool. I am trying to run my robot and record some data from it. However, it was a pain to store data to a vector by using for loop and indexing the mjtNum data. Also, the function mj_printData stores all the data instead of what I need. Could you please give me some hint about this, like a built-in API for storing specific part of the data?

**Comment by saran-t** [comment]
Can you be more specific about exactly what it is that you're trying to save?

**Comment by lyuyiqi** [comment]
Thank you for your reply. I am trying to continuously save time, qpos, qvel, ctrl, sensordata, xpos and squat in mjData at each timestep. I failed to convert mjtNum to vectors and store them.
