### ISSUE TITLE
hField not updated on data change

### ISSUE THREAD

**Issue by ripkea** [deepmind/mujoco#930]
Hi,

I'm currently working on a school project where I need a heightfield, that changes dynamically during runtime. The end goal is to model a type of changeable terrain.

I'm currently stuck on how exactly to effectively change the heightfield data while running the viewer. In the code below I would like to set half of the heightfield to height 2, as soon as the user presses the 'h' key. While the data does change, I was able to confirm this while debugging, the rendered model does not and both the regular visualization and wireframe stay the same.

Here is the full code I have at the moment. Any input is appreciated! 
```
import mujoco
import mujoco.viewer as v
import time
import keyboard
import numpy as np

xml = """
<mujoco>
    <asset>
        <hfield name="terrain"  nrow="16" ncol="16" size="1 1 1 1"/>
    </asset>
  <worldbody>
    <light name="top" pos="0 0 1"/>
      <geom name="red_sphere"  size=".2 .2 .2" rgba="1 0 0 1" pos="0 0 2"/>
        <geom name="heightfield" type="hfield" hfield="terrain"
     />
  </worldbody>
</mujoco>
"""
```
```
model = mujoco.MjModel.from_xml_string(xml)

data = mujoco.MjData(model)

with v.launch_passive(model, data) as v:
  start = time.time()

  while v.is_running() and time.time() - start < 30:

    if keyboard.read_key() == "h":
      num_rows = model.hfield_nrow[0]
      num_cols = model.hfield_ncol[0]
      new_hfield = np.ones((num_rows * num_cols))
      new_hfield[:128] = 2.
      model.hfield_data = new_hfield

    step_start = time.time()
    mujoco.mj_step(model, data)
    v.sync()

    time_until_next_step = model.opt.timestep - (time.time() - step_start)
    if time_until_next_step > 0:
      time.sleep(time_until_next_step)
```

**Comment by saran-t** [comment]
You need to call `mjr_uploadHField` each time the height field is modified in order for it to be picked up by the renderer. Note that this can be expensive since it's a GPU data movement.
