### ISSUE TITLE
Matrix Vector Multiplication

### ISSUE THREAD

**Issue by annikas5** [deepmind/mujoco#932]
Hello. I am trying to multiply this 4 by 2 matrix by a 2 by 1 vector to produce a 4 by 1 vector. Not sure what I am doing wrong. Am receiving an error for line 288, as shown below in the second picture.

![image](https://github.com/deepmind/mujoco/assets/99372630/6f6cc843-d91c-4bc6-ab87-5f83575ed58b)
![image](https://github.com/deepmind/mujoco/assets/99372630/c2aaca4e-b960-468d-bc68-d7830510cf82)

**Comment by kevinzakka** [comment]
The error message is pretty informative -- and you can always check the source code for [`mju_mulMatVec`](https://github.com/deepmind/mujoco/blob/c9e9cd8b35fa5dd76bef3444d8e1823ca289c4f4/src/engine/engine_util_blas.c#L698) to understand what input it expects (and shapes).
