### ISSUE TITLE
Derivative of Jacobian

### ISSUE THREAD

**Issue by annikas5** [deepmind/mujoco#933]
Trying to complete this matrix for a simulation I am working on. Anyone know how to determine the derivative of the Jacobian?

![image](https://github.com/deepmind/mujoco/assets/99372630/4add7a86-86c6-43cd-b0ea-7216323263cb)

This is how I computed the Jacobian. 

![image](https://github.com/deepmind/mujoco/assets/99372630/1da32be1-4d12-4ebd-844b-af3b030b9018)

**Comment by dhruvthanki** [comment]
Hello!
If the application doesn't require the accuracy of analytical derivative of the jacobian, you could go with finite differences as shown in #411. If you need the accuracy, you might have to implement an algorithm from [Link](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=5663690), equation 31. With the latter you will only get the product $\dot{J}\dot{q}$ and not $\dot{J}$ explicitly which should be sufficient for the above application.
