### ISSUE TITLE
What is data in mjdata relative to?

### ISSUE THREAD

**Issue by vymao** [deepmind/mujoco#934]
I'm an engineer and I'm trying to use MuJoCo for exploration purposes.

I'm looking for clarification on the data that is [stored in mjdata](https://github.com/deepmind/mujoco/blob/main/include/mujoco/mjdata.h). For example, fields such as [cvel](https://github.com/deepmind/mujoco/blob/main/include/mujoco/mjdata.h#LL293C12-L293C15) and [geom_xpos](https://github.com/deepmind/mujoco/blob/main/include/mujoco/mjdata.h#L245) contain velocities and positions. What reference frame is this relative to? Is it always relative to the parent body? If so, is there an easy way of getting the positions and velocities relative to the viewing/outside frame?

**Comment by kevinzakka** [comment]
See [here](https://stackoverflow.com/questions/73296464/mujoco-what-is-the-difference-between-pos-qpos-and-xpos) and [here](https://mujoco.readthedocs.io/en/stable/APIreference/APItypes.html#mjdata) for more information.
