### ISSUE TITLE
Does Mujoco have plans to support Apple Metal?

### ISSUE THREAD

**Issue by awkr** [deepmind/mujoco#95]
Hi, since Apple releases M1 SoC which seems very powerful and efficient, does Mujoco have plans to support Apple Metal?

**Comment by Coder-RG** [comment]
The devs are already working on it. Refer to #2

**Comment by saran-t** [comment]
Do you mean for rendering or for compute?

**Comment by awkr** [comment]
> Do you mean for rendering or for compute?

Sorry for not clarifying, features sorted by priority are:
1. compute: powered by MetalKit running on M1 and A14/15 chips
2. rendering

**Comment by saran-t** [comment]
Sorry that it's taken a while to answer this one. I think at this point we can reasonably confidently say that Metal support isn't a priority for us, however we do intend to make it easier for people to plug MuJoCo into their own renderer. After open sourcing, if there is enough community interest in implementing parts of MuJoCo rendering in Metal we'd be supportive of the effort, but we probably won't be taking on the work ourselves.
