### ISSUE TITLE
Procedural method for creating/scaling MuJoCo humanoids

### ISSUE THREAD

**Issue by Balint-H** [deepmind/mujoco#950]
Hello,

What are some recommendations for programmatically generating/scaling an MJCF of a humanoid (e.g., as mentioned by the [Merel 2017](https://arxiv.org/abs/1707.02201) paper)? I'm interested in the cases of matching an experimentally captured participant (static calibration would be sufficient), but also sampling new humanoids from a distribution of parameters. My first guesses would be trying some least squares approach like OpenSim and using PyMJCF to generate the XML. 

Are there any pitfalls/key considerations or existing implementations I should be aware?

Thanks!

**Comment by yuvaltassa** [comment]
Yes, I think PyMJCF is your best bet right now. No real gotchas I can think of.
