### ISSUE TITLE
Derivative of end effector position w.r.t action/control signal?

### ISSUE THREAD

**Issue by biegunk** [deepmind/mujoco#952]
Hi,

I am a bit of a beginner with MuJoCo and am trying to compute the jacobian of the DM control suite environment observations w.r.t the action. I am able to compute the derivatives of the quantities within the mj_physics state with `mjd_transitionFD`, but some of the observation elements, like the distance of the end-effector to the target (computed using geom_xpos), depend implicitly on state but are not computed in the in-built finite difference method. How can I compute the derivative of these?

Thanks

**Comment by yuvaltassa** [comment]
I the observation code is in Python you'll have to do the finite-differencing in Python.

**Comment by biegunk** [comment]
Hi, the observation is in python but is a function of elements of the MJData struct, in particular `geom_xpos`. Given the jacobian d_geom_xpos/da it would be trivial to get the jacobian of the observation. Is there a simple way of computing this Jacobian without manual finite difference implementation?

**Comment by yuvaltassa** [comment]
https://mujoco.readthedocs.io/en/latest/APIreference/APIfunctions.html#mj-jacgeom
