### ISSUE TITLE
repeated name in body array, Object name = B_first

### ISSUE THREAD

**Issue by MohammadrezaDindarloo** [deepmind/mujoco#953]
Hi,

I'm a student and I'm trying to use MuJoCo for my project.

I'm looking for some help with using cable to simulate a cable robot.

Here is a model which explains my question:

    <body name="cable1">
	    <composite type="cable" curve="s" count="41 1 1" size="1" offset="0 0 .6" initial="ball" >
	      <plugin plugin="mujoco.elasticity.cable">
		
		<config key="twist" value="1e7"/>
		<config key="bend" value="4e6"/>
		<config key="vmax" value="0.05"/>
	      </plugin>
	      <joint kind="main" damping=".015"/>
	      <geom type="capsule" size=".005" rgba=".8 .2 .1 1" condim="1"/>
	    </composite>
   </body>
   
   <body name="cable2"> 
	    <composite type="cable" curve="s" count="45 1 1" size="1" offset="0 0 .8" initial="ball" >
	      <plugin plugin="mujoco.elasticity.cable">
		<config key="twist" value="1e7"/>
		<config key="bend" value="4e6"/>
		<config key="vmax" value="0.05"/>
	      </plugin>
	      <joint kind="main" damping=".015"/>
	      <geom type="capsule" size=".005" rgba=".1 .2 .1 1" condim="1"/>
	    </composite>
    </body>

In my work at first I want to add four cables in my model but when I add the second it gives me an error because the name of body are same. you know when we add a cable composite to model it actually add n (the number of geom) geom and create a cable model and the first geom name will be B_first and the n'th will be B_last, now when I add the second cable composite model I give error below:
Error: repeated name in body array, position 43
Object name = B_first, id = 43

I suppose that this error refer to the name of first and last body of cable but don't know how to fix it. 
I will be thankful for any help or suggestion to solve my problem.

**Comment by yuvaltassa** [comment]
[This](https://mujoco.readthedocs.io/en/latest/XMLreference.html#body-composite-prefix) is what you want.
