### ISSUE TITLE
Custom decorative objects

### ISSUE THREAD

**Issue by zxwang96** [deepmind/mujoco#962]
Hi,

I'm using mujoco for a project that moves a cuboid to the target area. I use a thin `cylinder` object as the receptacle/target area indicator. But I found no matter how thin the cylinder is, the cuboid will be stuck near the edge of the cylinder. My question is: is there any way to add custom decorative objects, which are not considered by the physics engine of mujoco, to my MJCF? If not, could you suggest possible solutions to my problem?

**Comment by yuvaltassa** [comment]
Yes, of course. Run the tutorial colab, this is explained in the last cell.

**Comment by zxwang96** [comment]
Thanks. And there is a more direct solution: set `contype="2" conaffinity="2"` in MJCF to avoid collision

**Comment by saran-t** [comment]
> Thanks. I found there is a more direct solution: set `contype="2" conaffinity="2"` in MJCF to avoid collision

This isn't correct. You should set both to zero.

**Comment by yuvaltassa** [comment]
Or just use sites instead of geoms. Sites are designed for this.

https://mujoco.readthedocs.io/en/latest/overview.html#kinematic-tree

**Comment by zxwang96** [comment]
Thanks, both using site and setting cons to zero work.
