### ISSUE TITLE
Multiple Raycasts with mj_ray quite slow

### ISSUE THREAD

**Issue by simon-armleder** [deepmind/mujoco#969]
Hi, 

I want to implement something similar to the [TouchGrid Sensor Plugin](https://github.com/deepmind/mujoco/tree/7401d6786a87fee8b3108fde44c941e81c8c3f19/plugin/sensor), but instead of building a grid from contact points, I want to use distance measures.

Mujoco offers the function [mj_ray](https://roboti.us/book/APIreference.html#mj_ray) to shoot and intersect a single ray (p + x*v, x>=0). However, using a lot of these individual ray casts significantly slows down the simulation speed.

There exists a function called [mj_multiRay](https://github.com/deepmind/mujoco/blob/7401d6786a87fee8b3108fde44c941e81c8c3f19/src/engine/engine_ray.h#L34), but it only works if all rays have a common origin (and internally it does single ray casts).

Is there any more performant way to batch up ray casts and speed up the simulation?
Or any other way to measure short distances (0.1 m) to the environment at arbitrary sensing points?
 In similar application using [gazbeo](https://github.com/gazebosim/gazebo-classic/blob/gazebo11/plugins/RayPlugin.hh) the performance stays okay.

Here are some sim times:

Without any raycasts in my model I get:

```
Running 10000 steps at dt = 0.001 ...

 Simulation time      : 0.48 s
 Steps per second     : 20781
 Realtime factor      : 20.78 x
 Time per step        : 0.0481 ms

 Broadphase accuracy  : 17.69%
 Midphase accuracy    : 17.69%
 Contacts per step    : 3.53
 Constraints per step : 16.98
 Degrees of freedom   : 36
```

If I add 1000 mj_ray calls (distributed over the surface of the same model) I get down to:

```
Running 10000 steps at dt = 0.001 ...

 Simulation time      : 27.53 s
 Steps per second     : 363
 Realtime factor      : 0.36 x
 Time per step        : 2.7526 ms

 Broadphase accuracy  : 17.69%
 Midphase accuracy    : 17.69%
 Contacts per step    : 3.53
 Constraints per step : 16.98
 Degrees of freedom   : 36
```

The code in my plugin compute function looks something like this:
```
    int geomid = -1;
    for(size_t i = 0; i < patch_dyn.dist.size(); ++i)
    {
      // position world
      cell_pos_w[0] = patch_stat.positions(0, i);
      cell_pos_w[1] = patch_stat.positions(1, i);
      cell_pos_w[2] = patch_stat.positions(2, i);
      mju_rotVecMat(cell_pos_w, cell_pos_w, mat_w);
      mju_addTo3(cell_pos_w, pos_w);

      // orientation in world
      cell_n_w[0] = patch_stat.normals(0, i);
      cell_n_w[1] = patch_stat.normals(1, i);
      cell_n_w[2] = patch_stat.normals(2, i);
      mju_rotVecMat(cell_n_w, cell_n_w, mat_w);

      // raycast
      patch_dyn.dist[i]  = mj_ray(m, d, cell_pos_w, cell_n_w, nullptr, 1, body_id_, &geomid);
   }
```

 Thanks

**Comment by yuvaltassa** [comment]
Ray casting calls are thread safe and can be trivially parallelised.
