### ISSUE TITLE
Does the behavior of `mujoco` change across version due to floating point arithmetic errors

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [deepmind/mujoco#970]
Hi,

I'm a Gymnasium and Gymnasium-Robotics maintainer.

It is the case that across different `mujoco` versions the behavior may not be identical because of floating point arithmetic order inside `mujoco` 
(give same model & control)

Thanks!

**Comment by yuvaltassa** [comment]
Yes, as [explained and documented](https://mujoco.readthedocs.io/en/latest/computation.html#reproducibility).
