### ISSUE TITLE
needing guidence for cable driven robot simulation

### ISSUE THREAD

**Issue by MohammadrezaDindarloo** [deepmind/mujoco#973]
hi to everyone

I have some questions in simulating a cabel robot in mujoco. actually my problem is to modeling the cables. at first I used tendon to modeling my cables because of some good features but I ended up to using cable for this means because the cable have some features like bending and twisting that are suitable. my simulation in cable comming up with this: 
![Screenshot from 2023-07-08 14-50-23](https://github.com/deepmind/mujoco/assets/96303354/93e87bfd-56f0-41c2-9be6-e8049bd2bf0e)

this was good but thre was a problem that when I increase the count of composite type of cable the simulation time was very slow and it couldn't be handeled to working with this(my cable length are almost 4*10 meters) and when I decrease the count of cable composite the simulation couldn't handle the simulating and it get unstable and reset simulation. I tried a lot to find the solution but I couldn't. if anyone have any seggestion please help in this matter.
In second scenario I tried to simulate the robots cables with tendon. in this matter I did some simulation like bellow:
![Screenshot from 2023-07-08 15-06-49](https://github.com/deepmind/mujoco/assets/96303354/e68b24a4-cac9-4a1d-be18-d3a57b905421)

this simulation will be good fore me if I could measure the force in tendons and also impelement a scenario that an actuator handle my cable length (in reality we see that if we want to drive a box with two cable when we pull one of the cables the other cable get sag with out supporting any force) I tried to simulate this reality but I couldn't. I don't want the tendon haveing any push when I get the motor free but is do like the below :
![Screenshot from 2023-07-08 15-14-20](https://github.com/deepmind/mujoco/assets/96303354/e8a78360-aa93-4dc4-8f78-20fa5ecf8453)
now I don't know if there is any solution for me? can I handle this with tendon module? or any idea to handle my cable model? (I expect to have 4 motos in the top an endeffector that can drive the end effector with these motors through cables) thank you anyone for your helping.

**Comment by quagla** [comment]
Have you tried to decrease the cable stiffness to make the simulation stable? I would recommend using tendons if your cable is in a tensile configuration and the cable composite if it is in a bent/twisted configuration. What do you mean by the tendon not having any push?

**Comment by quagla** [comment]
I will close it as there is no update I assume you managed to solve the issue.
