### ISSUE TITLE
how to build a helmet camera?

### ISSUE THREAD

**Issue by Gariscat** [deepmind/mujoco#975]
Hi! I'm a student and I'm trying to use MuJoCo for building a sport simulator.

This question might sound stupid but is there any elegant way to **build a camera tied to the head of a humanoid** (like a helmet camera)? I have thought of creating a void MjModel instance and use its built-in camera. Is there a more straightforward way to do that by modifying the XML file?

BTW, thanks for officially maintaining the MuJoCo Python API! Looking forward to hear any advice!

**Comment by yuvaltassa** [comment]
You can attach cameras to bodies. [Here](https://github.com/deepmind/dm_control/blob/ccbaf9193ea147ad963558549202299ac07c69dc/dm_control/suite/humanoid.xml#L45) is an example.
