### ISSUE TITLE
Torque being global applied in Unity

### ISSUE THREAD

**Issue by LeeVangraefschepe** [deepmind/mujoco#977]
Hi,

I'm a student and I'm trying to use MuJoCo for simulating robotics. I’m looking for some help with applying forces/torque in Unity.

Before I applied the torque by using xfrc_applied. But now with multiple hinges connected to each other I started to run in some issues. I think the torque is being applied globally.

When I rotate it towards the Z axis it stops rotating but the torque is still applied? The torque is applied on the X axis so that’s why I think its applied globally. The hinge itself doesn’t rotate (see gif).

Here is a gif illustrating my question:
![RotationNotWorking](https://github.com/deepmind/mujoco/assets/104838894/bad8f0fa-17d1-44a0-85b1-03275e9544b1)

I tried different methods of applying forces but none of these worked except setting the velocity but that’s not what I need for this problem.

```cpp
private unsafe void SetTorque(Vector3 torque)
{
        torque = MjEngineTool.MjVector3(torque);
        int numDOFs = MjScene.Instance.Model->nu;

        //MjScene.Instance.Data->xfrc_applied[6 * _body.MujocoId + 3] = torque.x;
        //MjScene.Instance.Data->xfrc_applied[6 * _body.MujocoId + 4] = torque.y;
        //MjScene.Instance.Data->xfrc_applied[6 * _body.MujocoId + 5] = torque.z;
        MjEngineTool.SetMjVector3(&MjScene.Instance.Data->xfrc_applied[6 * _body.MujocoId + 3], torque);

        //MjEngineTool.SetMjVector3(&MjScene.Instance.Data->xfrc_applied[6 * _joint.MujocoId + 3], torque);

        //MjScene.Instance.Data->qfrc_applied[6 * _joint.MujocoId + 3] = torque.x;
        //MjScene.Instance.Data->qfrc_applied[6 * _joint.MujocoId + 4] = torque.y;
        //MjScene.Instance.Data->qfrc_applied[6 * _joint.MujocoId + 5] = torque.z;

        //MjScene.Instance.Data->qfrc_applied[numDOFs * _joint.MujocoId + 3] = torque.x;
        //MjScene.Instance.Data->qfrc_applied[numDOFs * _joint.MujocoId + 4] = torque.y;
        //MjScene.Instance.Data->qfrc_applied[numDOFs * _joint.MujocoId + 5] = torque.z;

        //MjScene.Instance.Data->ctrl[_joint.MujocoId] = _strength;

        //MjScene.Instance.Data->qvel[_joint.DofAddress + 0] = torque.x;
        //MjScene.Instance.Data->qvel[_joint.DofAddress + 1] = torque.y;
        //MjScene.Instance.Data->qvel[_joint.DofAddress + 2] = torque.z;

        //MjScene.Instance.Data->qfrc_applied[_joint.MujocoId + 6] = _strength;

        //MjScene.Instance.Data->ctrl[_joint.MujocoId] = _strength;
}
```

Is there a way to apply the torque locally or am I doing something wrong? The above commented lines are all attempts I tried without result. Only the qvel had result but that one is using the velocity and I need to use and measure forces.

**Comment by Balint-H** [comment]
Hello,

You are correct, `xfrc` is global force+torque. `qfrc` is what you are looking for, and you were close t the correct usage.

Note that for hinges the joint space is one dimensional, so you would only have one value to apply.

```c#
private unsafe void SetTorque(float torque)
{
    MjScene.Instance.Data -> qfrc_applied[_joint.DofAddress] = torque
}
```

If you want to apply 3D torque regardless of the body degrees of freedom, you can instead convert from desired local to global forces using the body's transform: https://docs.unity3d.com/ScriptReference/Transform.TransformVector.html
After converting to global space you can apply it using xfrc like you have done.

Lastly consider if using `MjActuators` would be more appropriate in your case, as it looks like they would cover your needs.
