### ISSUE TITLE
WebGL build with Unity plugin?

### ISSUE THREAD

**Issue by Norite-dev** [deepmind/mujoco#981]
Hi,

I'm an engineer and trying to use MuJoCo with Unity for education.
My Windows builds works good, but is there any way to build WebGL project with Unity and Mujoco?

Thank you guys!

**Comment by saran-t** [comment]
Not sure about Unity to WebGL specifically, but there's a [good example](https://github.com/zalo/mujoco_wasm) of MuJoCo running rather well in a web browser.
