### ISSUE TITLE
How to train mujoco model using Gymnasium on Unity?

### ISSUE THREAD

**Issue by tiago2820** [deepmind/mujoco#988]
**How to ask for help**

First, read our quick guide to
[asking good questions](https://github.com/deepmind/mujoco#asking-questions).
Below is a template for you to use:

Hi,

I'm a student and I'm trying to use MuJoCo to train a model using Gymnasium API on Unity.

I'm looking for some help with how to do the connection between mujoco, Gymnasium and Unity.

The main objective is to train inverted double pendulum model from mujoco using Gymnasium on Unity.

**Comment by kevinzakka** [comment]
Could you please start a discussion? Going to close this as it's not really an issue.
