### ISSUE TITLE
How to increasing CPU usage in order ro make the simulation faster

### ISSUE THREAD

**Issue by MohammadrezaDindarloo** [deepmind/mujoco#998]
Hi everyone,
I am trying to use mujoco to simulate cable driven parallel robot. I use cable composite to model my cables and as illustrated in the documentation it have multibody to create the cable behaviour. Now when I run my xml file the time passage is slow while my CPU usage just fill 20%. We have already adjusted the step time but the problem didn't fix (simulating in real time is very slow yet). 
How we can increase the CPU usage or any other solution to help? I am working in ubuntu 20.04 and using mujoco 2.3.6. 
xml model:
[XML_FILE.zip](https://github.com/deepmind/mujoco/files/12146448/XML_FILE.zip)

screanshut from my cpu usage information when using model:

![Screenshot from 2023-07-24 17-10-24](https://github.com/deepmind/mujoco/assets/96303354/2d21f8d8-a5ca-4985-ba35-699a8ac51652)
thaks in advance for your replying.

**Comment by nimrod-gileadi** [comment]
As of today, there is no way to speed up simulating a single model by throwing more CPUs at it.
MuJoCo is single-threaded, and there's a certain amount of computation that needs to be done on each step. For things like reinforcement learning training of live MPC, we benefit from running many instances of the same model in parallel, and getting a high throughput that way.

We will be looking to introduce multithreading into MuJoCo in the near future, to speed up things like collision detection that can be parallelised.
