### ISSUE TITLE
Integrate Motion Planning Algorithms

### ISSUE THREAD

**Issue by STAY-Melody** [deepmind/mujoco#999]
Hi!

Would it be considered to integrate motion planning algorithms, e.g., RRT, into Mujoco? 

Open Motion Planning Library could be a good choice.

Thanks!

**Comment by yuvaltassa** [comment]
Planning algorithms should not be integrated into MuJoCo itself.

Are you familiar with our [MJPC project](https://github.com/deepmind/mujoco_mpc)? This is a package for shooting-based trajectory optimisation, we are working on a direct (aka simultaneous) trajectory optimisation package now, based on inverse dynamics.
